DECLARE SUB ZAPRASCHET (Xc1 AS SINGLE, Xc2 AS SINGLE, Xc3 AS SINGLE, Yc1 AS SINGLE, Yc2 AS SINGLE, Yc3 AS SINGLE, hc1 AS SINGLE, hc2 AS SINGLE, hc3 AS SINGLE, opn1$, opn2$, opn3$, OH1 AS SINGLE, OH2 AS SINGLE, OH3 AS SINGLE)
DECLARE SUB ZAPRASCH1 (rep1 AS SINGLE, rep2 AS SINGLE, rep3 AS SINGLE, vsem AS SINGLE, zar1 AS SINGLE, zar2 AS SINGLE, zar3 AS SINGLE, snvz1 AS SINGLE, snvz2 AS SINGLE, snvz3 AS SINGLE, pr.eps1 AS SINGLE, pr.eps2 AS SINGLE, pr.eps3 AS SINGLE, N1 AS SINGLE, N2 AS SINGLE, N3 AS SINGLE, dov.isch1 AS SINGLE, dov.isch2 AS SINGLE, dov.isch3 AS SINGLE)
DECLARE SUB ZAPRASCH2 (Veer1B AS SINGLE, Veer2B AS SINGLE, Veer3B AS SINGLE, sk.shk1 AS SINGLE, sk.shk2 AS SINGLE, sk.shk3 AS SINGLE, dXtus11 AS SINGLE, dNtus1 AS SINGLE, dXtus2 AS SINGLE, dXtus3 AS SINGLE, dNtus2 AS SINGLE, dNtus3 AS SINGLE, ts1 AS SINGLE, ts2 AS SINGLE, ts3 AS SINGLE, zo11 AS SINGLE)
DECLARE SUB ZAPRASCH3 (Dt1 AS SINGLE, Dt2 AS SINGLE, Dt3 AS SINGLE, pop.v.d1 AS SINGLE, pop.v.d2 AS SINGLE, pop.v.d3 AS SINGLE, Ygol.t1 AS SINGLE, Ygol.t2 AS SINGLE, Ygol.t3 AS SINGLE, pop.v.nap.1 AS SINGLE, pop.v.nap.2 AS SINGLE, pop.v.nap.3 AS SINGLE, Yr1 AS SINGLE, Yr2 AS SINGLE, Yr3 AS SINGLE, vrv AS SINGLE, pover AS SINGLE, Ygpad1 AS SINGLE, Ygpad2 AS SINGLE, Ygpad3 AS SINGLE, snvz1 AS SINGLE, snvz2 AS SINGLE, snvz3 AS SINGLE)
DECLARE SUB PRICELOFRGM (zar AS SINGLE, Disch AS SINGLE, ts AS SINGLE, dXtus AS SINGLE, Ygvozv AS SINGLE, Vustra AS SINGLE, Pric.isch AS SINGLE)
DECLARE SUB SOPRIAGENKA (Xl AS SINGLE, Yl AS SINGLE, hl AS SINGLE, Xp AS SINGLE, Yp AS SINGLE, hp AS SINGLE, Alev AS SINGLE, Aprav AS SINGLE, Mcl AS SINGLE, Mcp AS SINGLE, hc AS SINGLE, Xc AS SINGLE, Yc AS SINGLE)
DECLARE SUB dV0111 (tz AS SINGLE, zar AS SINGLE, dV0 AS SINGLE)
DECLARE SUB PECHSNAR (nb AS SINGLE, snvz1 AS SINGLE, snvz2 AS SINGLE, snvz3 AS SINGLE, snvz$)
DECLARE SUB PRICAR5 (zar AS SINGLE, Disch AS SINGLE, Pric.isch AS SINGLE, N AS SINGLE)
DECLARE SUB POSMOTRETZELI ()
DECLARE SUB ZASGRYPZELI (Gl1 AS SINGLE, Fr1 AS SINGLE, A AS SINGLE, D AS SINGLE, Mc AS SINGLE)
DECLARE SUB WETER (vvod AS SINGLE, W AS SINGLE, Dsnos AS SINGLE, w200 AS SINGLE, w400 AS SINGLE, w800 AS SINGLE, w1200 AS SINGLE, w1600 AS SINGLE, w2000 AS SINGLE, w2400 AS SINGLE, w3000 AS SINGLE, w4000 AS SINGLE)
DECLARE SUB ZAPISATZEL ()
DECLARE SUB OBIEKTATAKI ()
DECLARE SUB POSMOTRETV0 (v0pol1 AS SINGLE, v0ymen1 AS SINGLE, v0perv1 AS SINGLE, v0vtor1 AS SINGLE, v0tret1 AS SINGLE, v0chetv1 AS SINGLE, v0pol2 AS SINGLE, v0ymen2 AS SINGLE, v0perv2 AS SINGLE, v0vtor2 AS SINGLE, v0tret2 AS SINGLE, v0chetv2 AS SINGLE, v0pol3 AS SINGLE, v0ymen3 AS SINGLE, v0perv3 AS SINGLE, v0vtor3 AS SINGLE, v0tret3 AS SINGLE, v0chetv4 AS SINGLE)
DECLARE SUB BBODOH (OH1 AS SINGLE, OH2 AS SINGLE, OH3 AS SINGLE)
DECLARE SUB ZAPISNP ()
DECLARE SUB ZAPISOP ()
DECLARE SUB REPERN (snvz AS SINGLE, zar AS SINGLE, Pric.pris AS SINGLE, dN AS SINGLE, N AS SINGLE, dXtus AS SINGLE, Dprisn AS SINGLE)
DECLARE SUB NZOKRASIVU ()
DECLARE SUB SPRAVKA ()
DECLARE SUB SERVZADmeny ()
DECLARE SUB PODGOTOVKAmeny ()
DECLARE SUB REPERmeny ()
DECLARE SUB OGNZADmeny ()
DECLARE SUB POSMOTRETOP ()
DECLARE SUB PORAGNENABZELI ()
DECLARE SUB POKAZBP (Xkp1 AS SINGLE, Ykp1 AS SINGLE, hkp1 AS SINGLE, Xkp2 AS SINGLE, Ykp2 AS SINGLE, hkp2 AS SINGLE, Xkp3 AS SINGLE, Ykp3 AS SINGLE, hkp3 AS SINGLE, Xkp4 AS SINGLE, Ykp4 AS SINGLE, hkp4 AS SINGLE, Xop1 AS SINGLE, Yop1 AS SINGLE, hop1 AS SINGLE, Xop2 AS SINGLE, Yop2 AS ANY, hop2 AS SINGLE, Xop3 AS SINGLE, Yop3 AS ANY, hop3 AS SINGLE, OH1 AS SINGLE, OH2 AS SINGLE, OH3 AS SINGLE)
DECLARE SUB T90 (Disch AS SINGLE, zar AS SINGLE, dNtus AS SINGLE, Pric.isch AS SINGLE, N AS SINGLE)
DECLARE SUB DOBAVITBP (Xkp1 AS SINGLE, Ykp1 AS SINGLE, hkp1 AS SINGLE, Xkp2 AS SINGLE, Ykp2 AS SINGLE, hkp2 AS SINGLE, Xkp3 AS SINGLE, Ykp3 AS SINGLE, hkp3 AS SINGLE, Xkp4 AS SINGLE, Ykp4 AS SINGLE, hkp4 AS SINGLE, Xop1 AS SINGLE, Yop1 AS SINGLE, hop1 AS SINGLE, Xop2 AS SINGLE, Yop2 AS SINGLE, hop2 AS SINGLE, Xop3 AS SINGLE, Yop3 AS SINGLE, hop3 AS SINGLE, opn1 AS SINGLE, opn2 AS SINGLE, opn3 AS SINGLE)
DECLARE SUB VVODVO ()
DECLARE SUB BALISTIKA (tz1 AS SINGLE, v0pol1 AS SINGLE, v0ymen1 AS SINGLE, v0perv1 AS SINGLE, v0vtor1 AS SINGLE, v0tret1 AS SINGLE, v0chetv1 AS SINGLE, tz2 AS SINGLE, v0pol2 AS SINGLE, v0ymen2 AS SINGLE, v0perv2 AS SINGLE, v0vtor2 AS SINGLE, v0tret2 AS SINGLE, v0chetv2 AS SINGLE, tz3 AS SINGLE, v0pol3 AS SINGLE, v0ymen3 AS SINGLE, v0perv3 AS SINGLE, v0vtor3 AS SINGLE, v0tret3 AS SINGLE, v0chetv3 AS SINGLE)
DECLARE SUB TABISCHYST (zar1 AS SINGLE, zar2 AS SINGLE, zar3 AS SINGLE, pr.eps1 AS SINGLE, pr.eps2 AS SINGLE, pr.eps3 AS SINGLE, dov.isch1 AS SINGLE, dov.isch2 AS SINGLE, dov.isch3 AS SINGLE, sk.shk1 AS SINGLE, sk.shk2 AS SINGLE, sk.shk3 AS SINGLE, opn1$, opn2$, opn3$, OH1 AS SINGLE, OH2 AS SINGLE, OH3 AS SINGLE, Xop1 AS SINGLE, Xop2 AS SINGLE, Xop3 AS SINGLE, Yop1 AS SINGLE, Yop2 AS SINGLE, Yop3 AS SINGLE, hop1 AS SINGLE, hop2 AS SINGLE, hop3 AS SINGLE)
DECLARE SUB PRICMORT (zar AS SINGLE, Disch AS SINGLE, ts AS SINGLE, Pric.isch AS SINGLE)
DECLARE SUB BLOKNOTSOB (snvz1 AS SINGLE, snvz2 AS SINGLE, snvz3 AS SINGLE, zar1 AS SINGLE, zar2 AS SINGLE, zar3 AS SINGLE, pr.eps1 AS SINGLE, pr.eps2 AS SINGLE, pr.eps3 AS SINGLE, dov.isch1 AS SINGLE, dov.isch2 AS SINGLE, dov.isch3 AS SINGLE, sk.shk1 AS SINGLE, sk.shk2 AS SINGLE, sk.shk3 AS SINGLE, t91 AS SINGLE, t92 AS SINGLE, t93 AS SINGLE, t94 AS SINGLE, t95 AS SINGLE, t96 AS SINGLE, osnov AS SINGLE, v01 AS SINGLE, v02 AS SINGLE, v03 AS SINGLE, v04 AS SINGLE, v05 AS SINGLE, v06 AS SINGLE, v0os AS SINGLE, raznob1 AS SINGLE, raznob2 AS SINGLE, raznob3 AS SINGLE, raznob4 AS SINGLE, raznob5 AS SINGLE, raznob6 AS SINGLE)
DECLARE SUB OCHISTKA (chza AS SINGLE)
DECLARE SUB KPEnast (zar AS SINGLE, Pric AS SINGLE, kpew AS SINGLE, kpen AS SINGLE, Yrr AS SINGLE, kpe AS SINGLE)
DECLARE SUB KKPEE (zar AS SINGLE, Pric.isch AS SINGLE, kpew AS SINGLE, kpen AS SINGLE, Yrr AS SINGLE, kpe AS SINGLE)
DECLARE SUB POREPERY (vsem AS SINGLE, dDr1 AS SINGLE, dDr AS SINGLE, dDov1 AS SINGLE, dDovre AS SINGLE, Dret1 AS SINGLE, Dret AS SINGLE, dDr2 AS SINGLE, dDov2 AS SINGLE, Dret2 AS SINGLE, dDr3 AS SINGLE, dDov3 AS SINGLE, Dret3 AS SINGLE, Nop AS SINGLE, dN AS SINGLE, dN1 AS SINGLE, dN2 AS SINGLE, dN3 AS SINGLE)
DECLARE SUB YGLUKNP (Xc AS SINGLE, Yc AS SINGLE, hc AS SINGLE, Dtkp AS SINGLE, Yrkp AS SINGLE, Ygol.tkp AS SINGLE, Xkp AS SINGLE, Ykp AS SINGLE, hkp AS SINGLE)
DIM N AS SINGLE
0.1 COLOR 14, 0
CLS : PRINT TAB(20); "'''''YO Div. 2C1'''''"
 PRINT "1-MENY PODGOTOVKA"; TAB(30); "2-MENY OGNEVAIA ZADACHA"
 PRINT "3-MENY REPER"; TAB(30); "4-MENY SERVISNUE ZADACHI"
 PRINT TAB(20); "0-BBOD"
 PRINT "................................................................"
DIM A11 AS INTEGER
INPUT A11
IF A11 = 1 THEN GOTO 0.101
IF A11 = 2 THEN GOTO 0.102
IF A11 = 3 THEN GOTO 0.103
IF A11 = 4 THEN GOTO 0.104
IF A11 = 0 THEN GOTO 0.42
0.101 PODGOTOVKAmeny
GOTO 0.42
0.102 OGNZADmeny
GOTO 0.42
0.103 REPERmeny
GOTO 0.42
0.104 SERVZADmeny
0.42 COLOR 10, 0
PRINT "................................................................"
PRINT "BBOD 3 V OSNOV.MENY, 8 STAR.ZEL, 10 NOV.ZEL, 11 PRISTR, 9 END"
COLOR 15, 0
1 DIM q AS INTEGER
INPUT q
IF q = 4 THEN h.met. = 0: h = 0: Tv = 0: Aw = 0: W = 0: t200 = 0: t400 = 0: t800 = 0: t1200 = 0: t1600 = 0: t2000 = 0: t2400 = 0: t3000 = 0: t4000 = 0: w200 = 0: w400 = 0: w800 = 0: w1200 = 0: w1600 = 0: w2000 = 0: w2400 = 0: w3000 = 0: w4000 = 0
IF q = 44 THEN h.met. = 0: h = 0: Tv = 0: Aw = 0: W = 0: t200 = 0: t400 = 0: t800 = 0: t1200 = 0: t1600 = 0: t2000 = 0: t2400 = 0: t3000 = 0: t4000 = 0: w200 = 0: w400 = 0: w800 = 0: w1200 = 0: w1600 = 0: w2000 = 0: w2400 = 0: w3000 = 0: w4000 = 0
GOTO 2
1.1
INPUT "SO-0 ZO-1"; zo11
 IF zo11 = 1 THEN GOTO 230
 IF zo11 <> 1 THEN GOTO 1
2 IF q = 7 THEN GOTO 5.21
IF q = 8 AND zo11 = 1 THEN GOTO 17
IF q <> 14 THEN zo11 = 0
    IF q = 1 THEN GOTO 2.62
2.1 IF q = 2 THEN GOTO 4
2.2 IF q = 9 THEN END
2.3 IF q = 3 THEN GOTO 0.1
2.31 IF q = 4 THEN GOTO 2.4
2.312  IF q = 5 THEN GOTO 5
2.313 IF q = 6 THEN GOTO 2.6
2.315 IF q = 10 THEN GOTO 10
2.316 IF q = 8 THEN GOTO 17
2.317 IF q = 11 THEN GOTO 150
2.318 IF q = 12 THEN GOTO 220
2.319 IF q = 13 THEN GOTO 2010
2.320 IF q = 14 THEN GOTO 1.1
2.321 IF q = 15 THEN GOTO 260
2.322 IF q = 16 THEN GOTO 10
2.323 IF q = 17 THEN GOTO 280
2.324 IF q = 18 THEN GOTO 290
2.325 IF q = 44 THEN GOTO 2.56
2.326 IF q = 19 THEN GOTO 2.61
IF q = 20 THEN GOTO 2.611
IF q = 21 THEN GOTO 700
IF q = 22 THEN GOTO 800
IF q = 23 THEN GOTO 900
IF q = 24 THEN GOTO 2.3261
IF q = 25 THEN GOTO 1000
IF q = 27 THEN INPUT "SHKVAL 1-Da, 0-Net"; shkval
IF q = 28 THEN GOTO 6
IF q = 29 THEN GOTO 950
IF q = 31 THEN GOTO 3200
IF q = 32 THEN GOTO 2.603
IF q = 33 THEN GOTO 4.2
IF q = 34 THEN GOTO 4.3
IF q = 35 THEN GOTO 50.001
IF q = 37 THEN GOTO 910
IF q = 39 THEN GOTO 6000
IF q = 40 THEN GOTO 6010
IF q = 41 THEN GOTO 7000
IF shkval = 1 THEN
        stre = 1
        GOTO 17
        ELSE
END IF
GOTO 0.42
2010
INPUT "Ispolz. pristrelannue 1-VSEM, Net-0"; vsem
        IF vsem = 1 THEN
        rep1 = 1: rep2 = 1: rep3 = 1
        INPUT "Popravki s REPERA - 0, BBOD v RYCHNYU - 1 "; vvod
        IF vvod = 1 THEN
                PRINT " << VVOD POPRAVOK VRYCHNYU >> "
                INPUT " 1Bat Dt, dD, dDov "; Dret1, dDr1, dDov1
                INPUT " 2B 1-vvodit, 0-Net "; vvod
                IF vvod = 1 THEN
                INPUT " 2Bat Dt, dD, dDov "; Dret2, dDr2, dDov2
                ELSE
                END IF
                INPUT " 3B 1-vvodit, 0-Net "; vvod
                IF vvod = 1 THEN
                INPUT " 3Bat Dt, dD, dDov "; Dret3, dDr3, dDov3
                ELSE
                END IF
        ELSE
        END IF
        GOTO 0.42
        ELSE
        INPUT "1B PRISTRELANNUE Da-1, Net-0"; rep1
        INPUT "2B PRISTRELANNUE Da-1, Net-0"; rep2
        INPUT "3B PRISTRELANNUE Da-1, Net-0"; rep3
        IF rep1 = 0 AND rep2 = 0 AND rep3 = 0 THEN GOTO 0.42
        INPUT "Popravki s REPERA - 0, BBOD v RYCHNYU - 1 "; vvod
        IF vvod = 1 THEN
                PRINT " << VVOD POPRAVOK VRYCHNYU >> "
                INPUT " 1Bat Dt, dD, dDov "; Dret1, dDr1, dDov1
                INPUT " 2B 1-vvodit, 0-Net "; vvod
                IF vvod = 1 THEN
                INPUT " 2Bat Dt, dD, dDov "; Dret2, dDr2, dDov2
                ELSE
                END IF
                INPUT " 3B 1-vvodit, 0-Net "; vvod
                IF vvod = 1 THEN
                INPUT " 3Bat Dt, dD, dDov "; Dret3, dDr3, dDov3
                ELSE
                END IF
        ELSE
        END IF
END IF
GOTO 0.42
'''''''''''''''''''''''''''''''''MORT/NAST''''''''''''''''''''''''''''''''''''''''
2.3261 INPUT " Strelba Mortirnaia-1, Nastilnaia-0 "; stre
GOTO 0.42
''''''''''''''''''''''''''''''''METEO''''''''''''''''''''''''''''''''''''
2.4 INPUT " METEO h.meteo, H, Tv, "; h.met., h, Tv
IF q = 4 THEN met = 0
INPUT " Weter DMK - 0, VR2 - 1 "; vvod
IF vvod = 0 THEN
        INPUT " DMK  Aw, W "; Aw, W
        ELSE
        INPUT " VR2  Aw, D(snos pyl) "; Aw, Dsnos
        IF Aw = 0 THEN Aw = 60
        Aw = Aw - 1
END IF
 IF Tv > 0 AND Tv <= 15 THEN
        Tv = Tv + 1
        ELSEIF Tv > 15 AND Tv <= 20 THEN
        Tv = Tv + 2
        ELSEIF Tv > 20 AND Tv <= 25 THEN
        Tv = Tv + 3
        ELSEIF Tv > 25 AND Tv <= 30 THEN
        Tv = Tv + 4
        ELSEIF Tv > 30 THEN Tv = Tv + 5
        ELSE
 END IF
        ddt = Tv - 15
  IF ddt > 0 THEN
        t200 = ddt: t400 = ddt: t800 = ddt: t1200 = ddt: t1600 = ddt: t2000 = ddt: t2400 = ddt: t3000 = ddt: t4000 = ddt: GOTO 2.53
        ELSE
  END IF
    IF ddt <= 0 THEN OPEN "I", #1, "T"
    IF ddt <= 0 THEN ddt = ddt * (-1) + 50
2.41 IF EOF(1) THEN GOTO 2.42
 INPUT #1, t1, t2, t3, t4, t5, t6, t7, t8, t9, t10
 IF ddt = t1 THEN t200 = t2: t400 = t3: t800 = t4: t1200 = t5: t1600 = t6: t2000 = t7: t2400 = t8: t3000 = t9: t4000 = t10
 IF t200 <> 0 THEN GOTO 2.42
  GOTO 2.41
2.412
2.42   CLOSE #1
2.53
WETER vvod, W, Dsnos, w200, w400, w800, w1200, w1600, w2000, w2400, w3000, w4000
GOTO 0.42
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
'''''''''''''''''''''''''''''BBOD GRYPPU''''''''''''''''''''''''''''''''''''''
2.56 PRINT "BBOD GRYPPU"
IF q = 44 THEN met = 1
INPUT " h.meteo, H "; h.met., h
INPUT " gr200 dT, Aw, W "; t200, Aw200, w200
INPUT " gr400 dT, Aw, W "; t400, Aw400, w400
INPUT " gr800 dT, Aw, W "; t800, Aw800, w800
INPUT " gr1200 dT, Aw, W "; t1200, Aw1200, w1200
INPUT " gr1600 dT, Aw, W "; t1600, Aw1600, w1600
INPUT " gr2000 dT, Aw, W "; t2000, Aw2000, w2000
INPUT " gr2400 dT, Aw, W "; t2400, Aw2400, w2400
INPUT " gr3000 dT, Aw, W "; t3000, Aw3000, w3000
INPUT " gr4000 dT, Aw, W "; t4000, Aw4000, w4000
Aw200 = Aw200 * 100
Aw400 = Aw400 * 100
Aw800 = Aw800 * 100
Aw1200 = Aw1200 * 100
Aw1600 = Aw1600 * 100
Aw2000 = Aw2000 * 100
Aw2400 = Aw2400 * 100
Aw3000 = Aw3000 * 100
Aw4000 = Aw4000 * 100
GOTO 0.42
''''''''''''''''''''''''''''''BALISTIKA''''''''''''''''''''''''''''''''''''
2.6
BALISTIKA tz1, v0pol1, v0ymen1, v0perv1, v0vtor1, v0tret1, v0chetv1, tz2, v0pol2, v0ymen2, v0perv2, v0vtor2, v0tret2, v0chetv2, tz3, v0pol3, v0ymen3, v0perv3, v0vtor3, v0tret3, v0chetv3
GOTO 0.42
2.603 VVODVO
GOTO 0.42
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
'''''''''''''''''VYBOR SNAR.VZRUV''''''''''''''''''''''''''''''''''''''''''''''''''
2.61 PRINT "VUBOR SNARIAD/VZRUVATEL"
PRINT " _OF/RGM-0, OF/AR-5-1, 3SH1/DT-2, OF/B-90-3, C4/T-90-4 "
INPUT " 1B Sn/Vz = "; snvz1
INPUT " 2B Sn/Vz = "; snvz2
INPUT " 3B Sn/Vz = "; snvz3
IF snvz1 = 1 OR snvz2 = 1 OR snvz3 = 1 THEN
INPUT " Vlagnui grynt - 0, Syhoi grynt - 1 "; pover
ELSE
END IF
GOTO 0.42
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
'''''''''''''''''''''''KOGO PRIVLECH K STRELBE''''''''''''''''''''''''''''''''''
2.611 PRINT " KOGO PRIVLECH "
INPUT " 1B 0-Da, 1-Net "; kop1
INPUT " 2B 0-Da, 1-Net "; kop2
INPUT " 3B 0-Da, 1-Net "; kop3
GOTO 0.42
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''''''''''''''''''''VVOD BP''''''''''''''''''''''''''''''''''''''''''''''''''
2.62 INPUT " 1-ne podg.OP 0-podg.OP "; Wubor
  IF Wubor = 1 THEN Xop1 = 0: Yop1 = 0: hop1 = 0: opn1 = 0: Xop2 = 0: Yop2 = 0: hop2 = 0: opn2 = 0: Xop3 = 0: Yop3 = 0: hop3 = 0: opn3 = 0: GOTO 3
  IF Wubor = 0 THEN OPEN "I", #1, "optabl"
  INPUT " OP 1B, 2B, 3B "; opn1$, opn2$, opn3$
2.621  IF EOF(1) THEN GOTO 2.6211
  INPUT #1, q1$, q2, q3, q4
  IF opn1$ = q1$ THEN Xop1 = q2: Yop1 = q3: hop1 = q4
  IF opn2$ = q1$ THEN Xop2 = q2: Yop2 = q3: hop2 = q4
  IF opn3$ = q1$ THEN Xop3 = q2: Yop3 = q3: hop3 = q4
  GOTO 2.621
2.6211 PRINT " OP 1 "; Xop1; Yop1, " OP 2 "; Xop2; Yop2, " OP 3 "; Xop3; Yop3
2.63  CLOSE
  GOTO 5
3 INPUT " OP1 X, Y, h "; Xop1, Yop1, hop1
3.1 INPUT " OP2 X, Y, h "; Xop2, Yop2, hop2
3.2 INPUT " OP3 X, Y, h "; Xop3, Yop3, hop3
5  BBODOH OH1, OH2, OH3
GOTO 0.42
4 INPUT " Ne podg Np-1, podg Np-0 "; N
  IF N = 1 THEN GOTO 4.1
  IF N = 0 THEN INPUT " NKP-1, 2, 3, 4 "; nkp1$, nkp2$, nkp3$, nkp4$
  OPEN "i", #1, "knptabl"
4.12  IF EOF(1) THEN GOTO 4.11
  INPUT #1, t1$, t2, t3, t4
  IF t1$ = nkp1$ THEN Xkp1 = t2: Ykp1 = t3: hkp1 = t4
  IF t1$ = nkp2$ THEN Xkp2 = t2: Ykp2 = t3: hkp2 = t4
  IF t1$ = nkp3$ THEN Xkp3 = t2: Ykp3 = t3: hkp3 = t4
  IF t1$ = nkp4$ THEN Xkp4 = t2: Ykp4 = t3: hkp4 = t4
  GOTO 4.12
4.11 CLOSE
PRINT " NP1 "; Xkp1; Ykp1; " NP2 "; Xkp2; Ykp2; " NP3 "; Xkp3; Ykp3; " NP4 "; Xkp4; Ykp4
GOTO 0.42
4.1 INPUT " KP1 X, Y, h "; Xkp1, Ykp1, hkp1
  INPUT " KP2 X, Y, h "; Xkp2, Ykp2, hkp2
  INPUT " KP3 X, Y, h "; Xkp3, Ykp3, hkp3
  INPUT " KP4 X, Y, h "; Xkp4, Ykp4, hkp4: GOTO 0.42
4.2 DOBAVITBP Xkp1, Ykp1, hkp1, Xkp2, Ykp2, hkp2, Xkp3, Ykp3, hkp3, Xkp4, Ykp4, hkp4, Xop1, Yop1, hop1, Xop2, Yop2, hop2, Xop3, Yop3, hop3, opn1, opn2, opn3
GOTO 0.42
4.3 POKAZBP Xkp1, Ykp1, hkp1, Xkp2, Ykp2, hkp2, Xkp3, Ykp3, hkp3, Xkp4, Ykp4, hkp4, Xop1, Yop1, hop1, Xop2, Yop2, hop2, Xop3, Yop3, hop3, OH1, OH2, OH3
GOTO 0.42
'''''''''''''''''''''''''VUBOR ZARIADA''''''''''''''''''''''''''''''''''''''
5.21 PRINT " Zariad: 0(P)_5(Y)_1_2_3_4 "
INPUT " 1B Zariad = "; zar1
INPUT " 2B Zariad = "; zar2
INPUT " 3B Zariad = "; zar3
GOTO 0.42
''''''''''''''''''''''''''''YGLU DLA KNP'''''''''''''''''''''''''''''''''''''
6
Xkp = Xkp1: Ykp = Ykp1: hkp = hkp1
YGLUKNP Xc, Yc, hc, Dtkp, Yrkp, Ygol.tkp, Xkp, Ykp, hkp
PRINT " KNP1 A = "; INT(Ygol.tkp + .001); " D = "; INT(Dtkp + .001); " Mc = "; INT(Yrkp + .001)
Xkp = Xkp2: Ykp = Ykp2: hkp = hkp2: Akp1 = Ygol.tkp
YGLUKNP Xc, Yc, hc, Dtkp, Yrkp, Ygol.tkp, Xkp, Ykp, hkp
IF Xkp <> 0 THEN
        PRINT " KNP2 A = "; INT(Ygol.tkp + .001); " D = "; INT(Dtkp + .001); " Mc = "; INT(Yrkp + .001)
        ELSE
END IF
Xkp = Xkp3: Ykp = Ykp3: hkp = hkp3: Akp2 = Ygol.tkp
YGLUKNP Xc, Yc, hc, Dtkp, Yrkp, Ygol.tkp, Xkp, Ykp, hkp
IF Xkp <> 0 THEN
        PRINT " KNP3 A = "; INT(Ygol.tkp + .001); " D = "; INT(Dtkp + .001); " Mc = "; INT(Yrkp + .001)
        ELSE
END IF
Xkp = Xkp4: Ykp = Ykp4: hkp = hkp4: Akp3 = Ygol.tkp
YGLUKNP Xc, Yc, hc, Dtkp, Yrkp, Ygol.tkp, Xkp, Ykp, hkp
IF Xkp <> 0 THEN
        PRINT " KNP4 A = "; INT(Ygol.tkp + .001); " D = "; INT(Dtkp + .001); " Mc = "; INT(Yrkp + .001)
        ELSE
END IF
Akp4 = Ygol.tkp
IF vvodp = 1 THEN RETURN
GOTO 0.42
'''''''''''''''''''''''''BBOD ZELI''''''''''''''''''''''''''''''''''''''''''
10 INPUT " Zasechka gryp zeli - 1, Net - 0 "; vvod
IF vvod = 1 THEN
A = 0: D = 0: Mc = 0: hc = 0
ZASGRYPZELI Gl1, Fr1, A, D, Mc
GOTO 13
        ELSE
        INPUT " Front = "; Fr1
        INPUT " Glybina = "; Gl1
END IF
   IF q = 16 THEN GOTO 0.42
        IF q = 10 THEN Xc = 0: Yc = 0: hc = 0
        INPUT " 0-ne plan zel, 1-plan zel "; vvz
        IF vvz = 1 THEN
        INPUT " 0-Zeli, 1-NZO, 2-Toch.Vst, PZO-3 "; chvu
        ELSE GOTO 10.21
        END IF
        IF chvu = 0 THEN GOTO 10.1
        IF chvu = 1 THEN GOTO 10.3
        IF chvu = 2 THEN GOTO 10.4
        IF chvu = 3 THEN GOTO 10.5
10.1 OPEN "Zeli" FOR INPUT AS #1
INPUT " N.zeli "; nz$
10.111 IF EOF(1) THEN GOTO 10.2
   INPUT #1, z1$, z2, z3, z4
   IF z1$ = nz$ THEN Xc = z2: Yc = z3: hc = z4: GOTO 10.2
        GOTO 10.111
10.2 CLOSE #1
        GOTO 17
10.3  INPUT " N.zeli "; nz$
         OPEN "NZO" FOR INPUT AS #1
10.311   IF EOF(1) THEN GOTO 10.32
         INPUT #1, z1$, z2, z3, z4, z5, z6
         IF z1$ = nz$ THEN Xlev = z2: Ylev = z3: Xpr = z4: Ypr = z5: hc = z6: GOTO 10.32
         GOTO 10.311
10.32    CLOSE #1
        GOTO 231.1
10.4 OPEN "toch.vst" FOR INPUT AS #1
        INPUT " N.zeli "; nz$
10.41   IF EOF(1) THEN GOTO 10.43
        INPUT #1, z1$, z2, z3, z4
        IF z1$ = nz$ THEN Xc = z2: Yc = z3: hc = z4: GOTO 10.43
        GOTO 10.41
10.43   CLOSE #1
PRINT " Xc, Yc, hc "; Xc, Yc, hc
        GOTO 17
10.5 OPEN "PZO" FOR INPUT AS #1
        INPUT " N.zeli "; nz$
10.51   IF EOF(1) THEN GOTO 10.53
        INPUT #1, z1$, z2, z3, z4, z5
        IF z1$ = nz$ THEN Xze = z2: Yze = z3: hc = z4: Aat = z5: GOTO 10.53
        GOTO 10.51
10.53   CLOSE #1
PRINT Xze, Yze, hc, Aat
        GOTO 231.1
10.21 IF Xc <> 0 AND Yc <> 0 THEN GOTO 17
        INPUT " Zel X, Y, h "; Xc, Yc, hc
11.1 IF Xc = 0 AND Yc = 0 THEN GOTO 13
11.11 IF Xc <> 0 AND Yc <> 0 THEN GOTO 17
13 INPUT " NKP = "; nkp
IF vvod = 0 THEN
        INPUT " A, D, Mc "; A, D, Mc
        ELSE
END IF
   IF nkp = 1 THEN Xkp = Xkp1: Ykp = Ykp1: hkp = hkp1
   IF nkp = 2 THEN Xkp = Xkp2: Ykp = Ykp2: hkp = hkp2
   IF nkp = 3 THEN Xkp = Xkp3: Ykp = Ykp3: hkp = hkp3
   IF nkp = 4 THEN Xkp = Xkp4: Ykp = Ykp4: hkp = hkp4
   IF Mc = 0 THEN INPUT " hc = "; hc
   IF A <> 0 AND D <> 0 THEN GOTO 13.1
   IF A = 0 AND D = 0 THEN INPUT " ygol s LEV, Mcl, NNP "; Alev, Mcl, nnpl: INPUT " ygol s PRAV, Mcp, NNP "; Aprav, Mcp, nnpp
   IF Mcl = 0 AND Mcp = 0 THEN INPUT " hc = "; hc
   GOSUB 228
   GOTO 17
13.1 Pi = 3.14159265358#
13.11
14  Xc = COS(A / 100 * 6 * Pi / 180) * D + Xkp
15  Yc = SIN(A / 100 * 6 * Pi / 180) * D + Ykp
IF hc = 0 THEN
16       hc = (Mc * (D * .001)) * 1.05 + hkp
        ELSE
END IF
17  GOSUB 50
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
104.2 IF shkval = 1 THEN
        COLOR 12, 0
        PRINT TAB(25); " SHKVAL!!!SHKVAL!!!SHKVAL!!! "
        COLOR 15, 0
        ELSE
        COLOR 12, 0
        PRINT TAB(25); " 2C1(GVOZDIKA) DANNUE PO ZELI "
        COLOR 15, 0
END IF
 GOSUB 105.1
140 GOTO 0.42

'''''''''''''''''''''''''''''''PRISTRELKA'''''''''''''''''''''''''''''''''''''
150 INPUT " Postavit zadachy na pristrelky 0 - Net, 1 - Da "; vvodp
        IF vvodp = 1 THEN
                PRINT TAB(25); " << POSTANOVKA ZADACHI NA PRISTRELKY >> "
                PRINT " BBOD  1 - DAK, 2 - SOPR, 3 - NZR, 4 - PZK, 5 - RLS(ROP), 6 - RLS(RNDC) "
                INPUT p
                        IF p = 0 OR p = 1 THEN
                                PRINT "---------------------------------------------------------"
                                GOTO 151
                                ELSEIF p = 3 THEN
                                PRINT "---------------------------------------------------------"
                                GOTO 160
                                ELSEIF p = 2 THEN
                                PRINT "---------------------------------------------------------"
                                GOTO 190
                                ELSEIF p = 4 THEN
                                INPUT " NBat = "; nb
                                PRINT "---------------------------------------------------------"
                                PRINT nb; " Batareia  122mm "
                                IF nb = 0 OR nb = 1 THEN PRINT " X = "; Xop1; " Y ="; Yop1; " h = "; hop1
                                IF nb = 2 THEN PRINT " X = "; Xop2; " Y ="; Yop2; " hop = "; hop2
                                IF nb = 3 THEN PRINT " X = "; Xop3; " Y ="; Yop3; " hop = "; hop3
                                PRINT " ZEL "; nz$; " X = "; Xc; " Y = "; Yc; " hc = "; hc
                                IF nb = 0 OR nb = 1 THEN PRINT " Poletnoe = "; ts1
                                IF nb = 2 THEN PRINT " Poletnoe = "; ts2
                                IF nb = 3 THEN PRINT " Poletnoe = "; ts3
                                PRINT "---------------------------------------------------------"
                                GOTO 0.42
                                ELSEIF p = 5 THEN
                                INPUT " NBat = "; nb
                                PRINT "---------------------------------------------------------"
                                PRINT " 122mm 2C1 "
                                IF nb = 1 THEN
                                   PRINT nb; "BATAREIA "; " OH = "; OH1; " X = "; Xop1; " Y = "; Yop1; " h = "; hop1
                                   ELSEIF nb = 2 THEN
                                   PRINT nb; "BATAREIA "; " OH = "; OH2; " X = "; Xop2; " Y = "; Yop2; " h = "; hop2
                                   ELSEIF nb = 3 THEN
                                   PRINT nb; "BATAREIA "; " OH = "; OH3; " X = "; Xop3; " Y = "; Yop3; " h = "; hop3
                                   ELSE
                                END IF
                                PRINT "ZEL X = "; Xc; " Y ="; Yc; " h = "; hc
                                PECHSNAR nb, snvz1, snvz2, snvz3, snvz$
                                PRINT "SNZR/VZR "; snvz$; " OH ";
                                IF nb = 1 OR nb = 0 THEN PRINT dov.isch1;
                                IF nb = 2 THEN PRINT dov.isch2;
                                IF nb = 3 THEN PRINT dov.isch3;
                                PRINT " PRICEL ";
                                IF nb = 1 OR nb = 0 THEN PRINT CINT(pric1 + .001);
                                IF nb = 2 THEN PRINT CINT(pric2 + .001);
                                IF nb = 3 THEN PRINT CINT(pric3 + .001);
                                PRINT "(";
                                IF nb = 1 OR nb = 0 THEN PRINT Ygvozv1;
                                IF nb = 2 THEN PRINT Ygvozv2;
                                IF nb = 3 THEN PRINT Ygvozv3;
                                PRINT ")";
                                PRINT " Disch = ";
                                IF nb = 1 OR nb = 0 THEN PRINT CINT(Disch1 + .001);
                                IF nb = 2 THEN PRINT CINT(Disch2 + .001);
                                IF nb = 3 THEN PRINT CINT(Disch3 + .001);
                                PRINT " Vus.Traektor = ";
                                IF nb = 1 OR nb = 0 THEN PRINT Vustra1;
                                IF nb = 2 THEN PRINT Vustra2;
                                IF nb = 3 THEN PRINT Vustra3;
                                PRINT " Poletnoe = ";
                                IF nb = 1 OR nb = 0 THEN PRINT ts1;
                                IF nb = 2 THEN PRINT ts2;
                                IF nb = 3 THEN PRINT ts3;
                                PRINT " Derivacia = ";
                                IF nb = 1 OR nb = 0 THEN PRINT CINT(zc1 + .001);
                                IF nb = 2 THEN PRINT CINT(zc2 + .001);
                                IF nb = 3 THEN PRINT CINT(zc3 + .001)
                                PRINT "---------------------------------------------------------"
                                GOTO 0.42
                                ELSEIF p = 6 THEN
                                INPUT " NBat = "; nb
                                PRINT "---------------------------------------------------------"
                                GOSUB 6
                                PRINT " ZEL X = "; Xc; " Y = "; Yc; " hc = "; hc
                                IF nb = 0 OR nb = 1 THEN PRINT " Poletnoe = "; ts1
                                IF nb = 2 THEN PRINT " Poletnoe = "; ts2
                                IF nb = 3 THEN PRINT " Poletnoe = "; ts3
                                PRINT "---------------------------------------------------------"
                                GOTO 0.42
                                ELSE
                        END IF
                ELSE
        END IF
INPUT " Pristrelka Podrychnoi-1, 0-Kagdoi "; podr
INPUT " Poschitat sredniy? 1-Da, 0-Net "; posch
IF posch = 0 THEN GOTO 150.1
INPUT " 1-Razriv A/Lev, D/Prav, Mc "; AL1, DP1, Mc1
INPUT " 2-Razriv A/Lev, D/Prav, Mc "; AL2, DP2, Mc2
INPUT " 3-Razriv A/Lev, D/Prav, Mc "; AL3, DP3, Mc3
INPUT " 4-Razriv A/Lev, D/Prav, Mc "; AL4, DP4, Mc4
IF AL4 = 0 THEN Al = (AL1 + AL2 + AL3) / 3: DP = (DP1 + DP2 + DP3) / 3: Mc = (Mc1 + Mc2 + Mc3) / 3
IF AL4 <> 0 THEN Al = (AL1 + AL2 + AL3 + AL4) / 4: DP = (DP1 + DP2 + DP3 + DP4) / 4: Mc = (Mc1 + Mc2 + Mc3 + Mc4) / 4
PRINT " SR po gryp A/Lev, D/Prav, Mc "; INT(Al + .001), INT(DP + .001), INT(Mc + .001)
INPUT " PRISTR-1: REPER-2: Drygoe-0: "; perex
IF perex = 1 THEN GOTO 150.1
IF perex = 2 THEN GOTO 220
IF perex = 0 THEN GOTO 0.42
150.1 PRINT " (DAK-1) :"; "(NZR-2) :"; " (Po.str.svet-3) :"; " (X,Y-4) :"; " (SOPR.A-5) :"; " (SOPR.dA-6) :"; " (PEREHVAT-7) "
INPUT p
IF p = 1 THEN GOTO 151
IF p = 2 THEN GOTO 160
IF p = 3 THEN GOTO 170
IF p = 4 THEN GOTO 180
IF p = 5 THEN GOTO 190
IF p = 6 THEN GOTO 200
IF p = 7 THEN GOTO 180
''''''''' 'DAK'''''''''''''''''
151
INPUT " NBat = "; nb
INPUT " NKP = "; nkp
IF vvodp = 0 THEN
        INPUT "Ar, Dr, Mcr "; Ar, Dr, Mcr
        IF Mcr = 0 THEN INPUT " hr = "; hr
        ELSE
        Ar = A: Dr = D: Mcr = Mc
END IF
   IF nkp = 1 OR nkp = 0 THEN Xkp = Xkp1: Ykp = Ykp1: hkp = hkp1
   IF nkp = 2 THEN Xkp = Xkp2: Ykp = Ykp2: hkp = hkp2
   IF nkp = 3 THEN Xkp = Xkp3: Ykp = Ykp3: hkp = hkp3
   IF nkp = 4 THEN Xkp = Xkp4: Ykp = Ykp4: hkp = hkp4
 GOSUB 152
   IF nb = 1 OR nb = 0 THEN Xc = Xc1: Yc = Yc1: hc = hc1: Dt = Dt1: Ygol.t = Ygol.t1
   IF nb = 2 THEN Xc = Xc2: Yc = Yc2: hc = hc2: Dt = Dt2: Ygol.t = Ygol.t2
   IF nb = 3 THEN Xc = Xc3: Yc = Yc3: hc = hc3: Dt = Dt3: Ygol.t = Ygol.t3
   dxc = Xc - Xkp
   dyc = Yc - Ykp
   Dc = SQR(dxc ^ 2 + dyc ^ 2)
 Ac = ABS(ATN(dyc / (dxc + .1)) / 3.141592 * 30) * 100
 IF dxc > 0 AND dyc > 0 THEN Ygolc = INT(Ac)
 IF dxc < 0 AND dyc > 0 THEN Ygolc = INT(3000 - Ac)
 IF dxc < 0 AND dyc < 0 THEN Ygolc = INT(3000 + Ac)
 IF dxc > 0 AND dyc < 0 THEN Ygolc = INT(6000 - Ac)
 IF Ygolc < 1500 AND Ygol.t > 4500 THEN
        PS = Ygolc + 6000 - Ygol.t
    ELSEIF Ygolc > 4500 AND Ygol.t < 1500 THEN
        PS = Ygolc - (Ygol.t + 6000)
    ELSE
        PS = Ygolc - Ygol.t
    END IF
 Ky = (INT(((Dc + .001) / 100) / ((Dt + .001) / 1000))) / 10
 SHy = INT(ABS(((PS + .001) / 10) / ((Dt + .001) / 1000)))
  IF PS < 0 THEN PRINT "Polog. Batarei = OP SLEVA!!!"
  IF PS > 0 THEN PRINT "Polog. Batarei = OP SPRAVA!!!"
PRINT " PS = "; INT(ABS(PS + .001)); ":"; " Ky = "; Ky; ":"; " SHy = "; SHy; ":"
IF vvodp = 0 THEN
        IF podr = 0 THEN
                PRINT " KORREKTYRA Daln = "; dD; " PRICEL = "; DPr; " Dovorot = "; dDov; " Yrov = "; dYrr; " dN = "; dN
                ELSE
                PRINT "<<KORREKTYRA>>"
                PRINT "Daln = "; dD
                PRINT "PRICEL"; ":"; "1B="; dPr1; ":"; "2B="; dPr2; ":"; "3B="; dPr3
                PRINT "Dovorot="; dDov
                PRINT "Yrov="; dYrr; "dN="; dN
        END IF
        ELSE
        GOSUB 6
END IF
vvodp = 0
INPUT "Prodolgit pristrelky - 0, Vuhod - 1"; prod
IF prod = 0 THEN
        GOTO 151
        ELSE
END IF
 GOTO 0.42
  
160
''''''''''NZR'''''''''''''''''''''''
INPUT " NBat = "; nb
INPUT " NKP = "; nkp
IF vvodp = 0 THEN
        INPUT " dAr, dDr "; dAr, dDr
        ELSE
        dAr = 0: dDr = 0
END IF
   IF nkp = 1 THEN Xkp = Xkp1: Ykp = Ykp1: hkp = hkp1
   IF nkp = 2 THEN Xkp = Xkp2: Ykp = Ykp2: hkp = hkp2
   IF nkp = 3 THEN Xkp = Xkp3: Ykp = Ykp3: hkp = hkp3
   IF nkp = 4 THEN Xkp = Xkp4: Ykp = Ykp4: hkp = hkp4
   IF nb = 1 THEN Xc = Xc1: Yc = Yc1: hc = hc1: Dt = Dt1: Ygol.t = Ygol.t1
   IF nb = 2 THEN Xc = Xc2: Yc = Yc2: hc = hc2: Dt = Dt2: Ygol.t = Ygol.t2
   IF nb = 3 THEN Xc = Xc3: Yc = Yc3: hc = hc3: Dt = Dt3: Ygol.t = Ygol.t3
   dxc = Xc - Xkp
   dyc = Yc - Ykp
   Dc = SQR(dxc ^ 2 + dyc ^ 2)
 Ac = ABS(ATN(dyc / (dxc + .1)) / 3.141592 * 30) * 100
 IF dxc > 0 AND dyc > 0 THEN Ygolc = INT(Ac)
 IF dxc < 0 AND dyc > 0 THEN Ygolc = INT(3000 - Ac)
 IF dxc < 0 AND dyc < 0 THEN Ygolc = INT(3000 + Ac)
 IF dxc > 0 AND dyc < 0 THEN Ygolc = INT(6000 - Ac)
 IF Ygolc < 1500 AND Ygol.t > 4500 THEN
        PS = Ygolc + 6000 - Ygol.t
    ELSEIF Ygolc > 4500 AND Ygol.t < 1500 THEN
        PS = Ygolc - (Ygol.t + 6000)
    ELSE
        PS = Ygolc - Ygol.t
    END IF
 Ky = (INT(((Dc + .001) / 100) / ((Dt + .001) / 1000))) / 10
 SHy = INT(ABS(((PS + .001) / 10) / ((Dt + .001) / 1000)))
 Ar = Ygolc + dAr
 Dr = Dc + dDr
  GOSUB 152
  IF PS < 0 THEN PRINT "Polog. Batarei= OP SLEVA!!!"
  IF PS > 0 THEN PRINT "Polog. Batarei= OP SPRAVA!!!"
PRINT "PS="; INT(ABS(PS + .001)); ":"; "Ky="; Ky; ":"; "SHy="; SHy; ":"
IF vvodp = 0 THEN
        IF podr = 0 THEN
                PRINT " KORREKTYRA Daln = "; dD; " PRICEL = "; DPr; " Dovorot = "; dDov
                ELSE
                PRINT "<<KORREKTYRA>>"
                PRINT "Daln = "; dD
                PRINT "PRICEL"; ":"; "1B="; dPr1; ":"; "2B="; dPr2; ":"; "3B="; dPr3
                PRINT "Dovorot="; dDov
        END IF
        ELSE
        GOSUB 6
END IF
vvodp = 0
INPUT "Prodolgit pristrelky-0, Vuhod-1"; prod
IF prod = 0 THEN
        GOTO 160
        ELSE
END IF
  GOTO 0.42

170
''''''''''''Po.str.sveta ''''''''''''''''''
INPUT " NBat = "; nb
 INPUT " dX, dY "; dxrc, dyrc
   IF nb = 1 THEN Xc = Xc1: Yc = Yc1: hc = hc1
   IF nb = 2 THEN Xc = Xc2: Yc = Yc2: hc = hc2
   IF nb = 3 THEN Xc = Xc3: Yc = Yc3: hc = hc3
   Xr = Xc + dxrc: Yr = Yc + dyrc
 GOSUB 153
IF podr = 0 THEN
 PRINT "<<KORREKTYRA>>Daln="; dD, "PRICEL="; DPr, "Dovorot="; dDov
ELSE
 PRINT "<<KORREKTYRA>>"
 PRINT "Daln = "; dD
PRINT "PRICEL"; ":"; "1B="; dPr1; ":"; "2B="; dPr2; ":"; "3B="; dPr3
PRINT "Dovorot="; dDov
END IF
INPUT "Prodolgit pristrelky-0, Vuhod-1"; prod
IF prod = 0 THEN
        GOTO 170
        ELSE
END IF
  GOTO 0.42

''''''''''''''X,Y'''''''''''''''''''''''''
180 IF p = 7 THEN
        INPUT " NBat. = "; nb
        INPUT " Toch. Perenosa X, Y "; Xper, Yper
        INPUT " Toch. Vstrechi X, Y "; Xvst, Yvst
      ELSE
        INPUT " NBat. = "; nb
        INPUT " X, Y, "; Xr, Yr
    END IF
GOSUB 153
IF podr = 0 THEN
 PRINT "<<KORREKTYRA>>Daln="; dD, "PRICEL="; DPr, "Dovorot="; dDov
ELSE
 PRINT "<<KORREKTYRA>>"
 PRINT "Daln = "; dD
PRINT "PRICEL"; ":"; "1B="; dPr1; ":"; "2B="; dPr2; ":"; "3B="; dPr3
PRINT "Dovorot="; dDov
END IF
INPUT " Prodolgit pristrelky-0, Vuhod-1 "; prod
IF prod = 0 THEN
        GOTO 180
        ELSE
END IF
GOTO 0.42

'''''''''''''''SOPR-A'''''''''''''''''''''''
190 IF vvodp = 1 THEN
        GOSUB 6
        INPUT " LEV Nkp = "; nkpl
        INPUT " PRAV Nkp = "; nkpp
        IF nkpl = 1 OR nkpl = 0 THEN Al = Akp1
        IF nkpl = 2 THEN Al = Akp2
        IF nkpl = 3 THEN Al = Akp3
        IF nkpl = 4 THEN Al = Akp4
        IF nkpp = 1 OR nkpp = 0 THEN Ap = Akp1
        IF nkpp = 2 THEN Ap = Akp2
        IF nkpp = 3 THEN Ap = Akp3
        IF nkpp = 4 THEN Ap = Akp4
        IF Al < 1500 AND Ap > 4500 THEN
                Ygzas = Al + 6000 - Ap
                ELSE
                Ygzas = Al - Ap
        END IF
        PRINT " Ygol Zasechki = "; INT(Ygzas + .001)
        GOTO 195
        ELSE
END IF
PRINT " PO RAZRUVY "
INPUT " NBat = "; nb
INPUT " LEV Ar, Mcr, NKP "; Alevr, Mclr, nnpl
INPUT " PRAV Ar, Mcr, NKP "; Apravr, Mcpr, nnpp
IF Mclr = 0 AND Mcpr = 0 THEN INPUT " hr = "; hr
   GOSUB 210
   GOSUB 153
IF podr = 0 THEN
 PRINT " KORREKTYRA Daln = "; dD; " PRICEL = "; DPr; " Dovorot = "; dDov; " Yrov = "; dYrr; " dN = "; dN
ELSE
 PRINT "<<KORREKTYRA>>"
 PRINT "Daln = "; dD
PRINT "PRICEL"; ":"; "1B="; dPr1; ":"; "2B="; dPr2; ":"; "3B="; dPr3
PRINT "Dovorot="; dDov
PRINT "Yrov="; dYrr; "dN="; dN
END IF
195 vvodp = 0
INPUT " Prodolgit pristrelky-0, Vuhod-1 "; prod
IF prod = 0 THEN
        GOTO 190
        ELSE
END IF
    GOTO 0.42
''''''''''''''''''''''''SOPR-dA''''''''''''''''''
200 PRINT " PO RAZRUVY "
INPUT " NBat = "; nb
INPUT " LEV dA, Mc, NKP, NBat "; dAlevr, Mclr, nnpl
INPUT " PRAV dA, Mc, NKP "; dApravr, Mcpr, nnpp
Alevr = Alev + dAlevr: Apravr = Aprav + dApravr
IF Mclr = 0 AND Mcpr = 0 THEN INPUT " hr = "; hr
  GOSUB 210
  GOSUB 153
IF podr = 0 THEN
 PRINT "<<KORREKTYRA>>Daln="; dD, "PRICEL="; DPr, "Dovorot="; dDov
ELSE
 PRINT "<<KORREKTYRA>>"
 PRINT "Daln = "; dD
PRINT "PRICEL"; ":"; "1B="; dPr1; ":"; "2B="; dPr2; ":"; "3B="; dPr3
PRINT "Dovorot="; dDov
END IF
INPUT " Prodolgit pristrelky-0, Vuhod-1 "; prod
IF prod = 0 THEN
        GOTO 200
        ELSE
END IF
  GOTO 0.42

'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
152 Xr = COS(Ar / 100 * 6 * 3.141592 / 180) * Dr + Xkp
 Yr = SIN(Ar / 100 * 6 * 3.141592 / 180) * Dr + Ykp
 hr = (Mcr * (Dr * .001)) * 1.05 + hkp
153
    IF nb = 1 THEN Xb = Xop1: Yb = Yop1: hb = hop1: dXtus = dXtus11: dNtus = dNtus1
    IF nb = 2 THEN Xb = Xop2: Yb = Yop2: hb = hop2: dXtus = dXtus2: dNtus = dNtus2
    IF nb = 3 THEN Xb = Xop3: Yb = Yop3: hb = hop3: dXtus = dXtus3: dNtus = dNtus3
 IF p = 7 THEN
        dxr = Xper - Xb: dyr = Yper - Yb
        ELSE
        dxr = Xr - Xb
        dyr = Yr - Yb
 END IF
 Dtr = SQR(dxr ^ 2 + dyr ^ 2)
 Ar = ABS(ATN(dyr / (dxr + .1)) / 3.141592 * 30) * 100
 IF dxr > 0 AND dyr > 0 THEN Ygol.tr = INT(Ar)
 IF dxr < 0 AND dyr > 0 THEN Ygol.tr = INT(3000 - Ar)
 IF dxr < 0 AND dyr < 0 THEN Ygol.tr = INT(3000 + Ar)
 IF dxr > 0 AND dyr < 0 THEN Ygol.tr = INT(6000 - Ar)
 IF p = 7 THEN
        dxper = Xvst - Xb: dyper = Yvst - Yb
      Dt = SQR(dxper ^ 2 + dyper ^ 2)
      Ar = ABS(ATN(dyper / (dxper + .1)) / 3.141592 * 30) * 100
        IF dxper > 0 AND dyper > 0 THEN Ygol.t = INT(Ar)
        IF dxper < 0 AND dyper > 0 THEN Ygol.t = INT(3000 - Ar)
        IF dxper < 0 AND dyper < 0 THEN Ygol.t = INT(3000 + Ar)
        IF dxper > 0 AND dyper < 0 THEN Ygol.t = INT(6000 - Ar)
      ELSE
        IF nb = 1 THEN Dt = Dt1: Ygol.t = Ygol.t1: dXtus = dXtus11: snvz = snvz1
        IF nb = 2 THEN Dt = Dt2: Ygol.t = Ygol.t2: dXtus = dXtus2: snvz = snvz2
        IF nb = 3 THEN Dt = Dt3: Ygol.t = Ygol.t3: dXtus = dXtus3: snvz = snvz3
 END IF
 dD = INT(Dt - Dtr)
 dDov = INT(Ygol.t - Ygol.tr)
 IF podr = 0 THEN
 DPr = INT(dD / (dXtus + .01))
 ELSE
 dPr1 = INT(dD / (dXtus11 + .01)): dPr2 = INT(dD / (dXtus2 + .01)): dPr3 = INT(dD / (dXtus3 + .01))
 END IF
        dYrr = CINT(((hc - hr + .001) / ((Dt + .001) * .001)) * .95)
        dN = INT(DPr * dNtus)
 RETURN

' SOPR KORREKT
210
'LEV
  IF nnpl = 1 THEN Xl = Xkp1: Yl = Ykp1: hl = hkp1
  IF nnpl = 2 THEN Xl = Xkp2: Yl = Ykp2: hl = hkp2
  IF nnpl = 3 THEN Xl = Xkp3: Yl = Ykp3: hl = hkp3
  IF nnpl = 4 THEN Xl = Xkp4: Yl = Ykp4: hl = hkp4
'PRAV
  IF nnpp = 1 THEN Xp = Xkp1: Yp = Ykp1: hp = hkp1
  IF nnpp = 2 THEN Xp = Xkp2: Yp = Ykp2: hp = hkp2
  IF nnpp = 3 THEN Xp = Xkp3: Yp = Ykp3: hp = hkp3
  IF nnpp = 4 THEN Xp = Xkp4: Yp = Ykp4: hp = hkp4
  dxso = Xp - Xl: dyso = Yp - Yl
  baz = SQR(dxso ^ 2 + dyso ^ 2)
  aso = ABS(ATN(dyso / (dxso + .1)) / 3.141592 * 30) * 100

  IF dxso > 0 AND dyso > 0 THEN ygol.baz = INT(aso)
  IF dxso < 0 AND dyso > 0 THEN ygol.baz = INT(3000 - aso)
  IF dxso < 0 AND dyso < 0 THEN ygol.baz = INT(3000 + aso)
  IF dxso > 0 AND dyso < 0 THEN ygol.baz = INT(6000 - aso)


  IF Alevr < 1500 AND Apravr > 4500 THEN fir = ABS(Alevr + 6000 - Apravr)
  IF Alevr > 4500 AND Apravr < 1500 THEN fir = ABS(Alevr - (Apravr + 6000))
  IF Alevr > Apravr THEN fir = ABS(Alevr - Apravr)

  IF Alevr < 1500 AND ygol.baz > 4500 THEN
        blevr = ABS(Alevr + 6000 - ygol.baz)
      ELSEIF Alevr > 4500 AND ygol.baz < 1500 THEN
        blevr = ABS(Alevr - (ygol.baz + 6000))
      ELSE
        blevr = ABS(Alevr - ygol.baz)
  END IF

  IF ygol.baz - 3000 < 0 THEN
  ybazp = ygol.baz + 3000
  ELSE
  ybazp = ygol.baz - 3000
  END IF

  IF Apravr < 1500 AND ybazp > 4500 THEN
  bpravr = ABS(Apravr + 6000 - ybazp)
  ELSEIF Apravr > 4500 AND ybazp < 1500 THEN
  bpravr = ABS(Apravr - (ybazp + 6000))
  ELSE
  bpravr = ABS(Apravr - ybazp)
  END IF


  Dlevr = ABS(baz / (SIN(fir / 100 * 6 * 3.141592 / 180) + .001) * SIN(bpravr / 100 * 6 * 3.141592 / 180))
  Dpravr = ABS(baz / (SIN(fir / 100 * 6 * 3.141592 / 180) + .001) * SIN(blevr / 100 * 6 * 3.141592 / 180))
  Xcsor = COS(Alevr / 100 * 6 * 3.141592 / 180) * Dlevr + Xl
  Ycsor = SIN(Alevr / 100 * 6 * 3.141592 / 180) * Dlevr + Yl
  IF Mclr = 0 THEN hr = Mcpr * (Dpravr * .001) * 1.05 + hp
  IF Mcpr = 0 THEN hr = Mclr * (Dlevr * .001) * 1.05 + hl
  Xr = Xcsor: Yr = Ycsor
  RETURN
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
'''''''''''''''''''''''''REPER''''''''''''''''''''''''''''''''''''''''''''
220 PRINT "<<<<<<<<<<<<<<<<<REPER>>>>>>>>>>>>>>>>>>>>>>>>>"
INPUT " OF/RGM-0, OF/AR5-1, OF/V90-2, 3SH1/DT-3 "; snvz
INPUT "Zar, Pric, N, Dov, NBat, OH"; zar, Pric, N, dov, Nop, OH
INPUT " Koord.Reper X, Y, h "; Xre, Yre, hre
 IF Xre = 0 THEN GOTO 221
 GOTO 222.1
221 INPUT " A, D, Mc, NKP "; Are, Dre, Mcre, nkp
   IF nkp = 1 THEN Xkp = Xkp1: Ykp = Ykp1: hkp = hkp1
   IF nkp = 2 THEN Xkp = Xkp2: Ykp = Ykp2: hkp = hkp2
   IF nkp = 3 THEN Xkp = Xkp3: Ykp = Ykp3: hkp = hkp3
   IF nkp = 4 THEN Xkp = Xkp4: Ykp = Ykp4: hkp = hkp4
 Xre = COS(Are / 100 * 6 * 3.141592 / 180) * Dre + Xkp
 Yre = SIN(Are / 100 * 6 * 3.141592 / 180) * Dre + Ykp
 hre = Mcre * (Dre * .001) * 1.05 + hkp
  IF Are = 0 THEN GOTO 222
  GOTO 222.1
222
    INPUT " LEV A, Mc, NKP "; Alev, Mcl, nnpl
    INPUT " PRAV A, Mc, NKP "; Aprav, Mcp, nnpp
    GOSUB 228
    Xre = Xc: Yre = Yc: hre = hc

222.1 IF Nop = 1 THEN Xb = Xop1: Yb = Yop1: hb = hop1
      IF Nop = 2 THEN Xb = Xop2: Yb = Yop2: hb = hop2
      IF Nop = 3 THEN Xb = Xop3: Yb = Yop3: hb = hop3

 dxre = Xre - Xb: dyre = Yre - Yb: dhre = hre - hb
 Dret = SQR(dxre ^ 2 + dyre ^ 2)
 Are = ABS(ATN(dyre / (dxre + .1)) / 3.141592 * 30) * 100
 Yrre = dhre / (Dret * .001 + .01) * .95
  IF dxre > 0 AND dyre > 0 THEN Ygol.re = INT(Are)
  IF dxre < 0 AND dyre > 0 THEN Ygol.re = INT(3000 - Are)
  IF dxre < 0 AND dyre < 0 THEN Ygol.re = INT(3000 + Are)
  IF dxre > 0 AND dyre < 0 THEN Ygol.re = INT(6000 - Are)
  IF OH <= 1500 AND Ygol.re >= 4500 THEN
         Dov.ret = Ygol.re - (OH + 6000)
     ELSE
         Dov.ret = Ygol.re - (OH)
       END IF

'''''KPE''''''
KPEnast zar, Pric, kpew, kpen, Yrr, kpe
    daep = Yrre * kpe: Pric.pris = Pric - Yrre - daep
   IF zar = 0 THEN
   OPEN "I", #1, "2c1P"
   ELSEIF zar = 5 THEN
   OPEN "I", #1, "2c1y"
   ELSEIF zar = 1 THEN
   OPEN "I", #1, "2c11"
   ELSEIF zar = 2 THEN
   OPEN "I", #1, "2c12"
   ELSEIF zar = 3 THEN
   OPEN "I", #1, "2c13"
   ELSEIF zar = 4 THEN
   OPEN "I", #1, "2c14"
   ELSE
   OPEN "I", #1, "2c1P"
END IF
224 IF EOF(1) THEN GOTO 227
225 INPUT #1, ta1, ta2, ta3, ta4, ta5, ta6, ta7, ta8, ta9, ta10, ta11, ta12, ta13, ta14, ta15, ta16, ta17, ta18, ta19, ta20, ta21, ta22, ta23, ta24, ta25, ta26, ta27, ta28, ta29, ta30, ta31, ta32, ta33, ta34, ta35, ta36, ta37
226 IF ta2 <= Pric.pris THEN GOTO 226.1
 GOTO 224
226.1 Prta = ta2: dXtus = ta3: Dta = ta1
227 CLOSE #1
  Dpris = (Pric.pris - Prta) * dXtus + Dta
REPERN snvz, zar, Pric.pris, dN, N, dXtus, Dprisn
IF snvz = 2 OR snvz = 3 THEN
        Dpris = Dprisn
        ELSE
        Dpris = Dpris
END IF
dDr = Dpris - Dret: dDovre = dov - Dov.ret
PRINT "Yst.prist.Zar="; zar; ": Pric="; Pric; ": Dov="; dov; ": N="; N
PRINT "Koord,Reper X="; INT(Xre); ": Y="; INT(Yre); ": h="; INT(hre)
PRINT "Topo Drt="; INT(Dret); ": Dovt="; INT(Dov.ret); ": dhre="; INT(dhre)
PRINT "Dprist="; INT(Dpris); ": pop.v.Dal.="; INT(dDr); ": pop.v.nap="; dDovre; ": dN="; INT(dN)
GOSUB 2000
GOTO 0.42
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''''''''''''''''''''''''ZO'''''''''''''''''''''''''''''''''''''''''''''
230 vvz = 0: hc = 0
230.1 PRINT "ZAGRAD OGON"
INPUT "Ognevoe proches-1, ZO-0"; vidog
PRINT "Flangi (X,Y-1)_(A,D-2)_(SOPR-3)___Zentr,Ygol ataki (X,Y-4)_(A,D-5)_(SOPR-6)"
INPUT z
231.1 INPUT " K-vo.ryb, interval, Front "; ryb, inter1, Front
PRINT " Privlech  (1B,2B,3B-1) : (1B,2B-2) : (1B,3B-3) : (2B,3B-4) "
PRINT " (1B-5) : (2B-6) : (3B-7) "
INPUT kto.str
 IF vvz = 0 THEN
        Xlev = 0
        ELSE
 END IF
 IF vvz = 1 AND chvu = 1 THEN
        zo11 = 1
        ELSE
 END IF
 IF chvu = 4 THEN
        zo11 = 1: GOTO 234.11
        ELSE
 END IF
        IF Xlev <> 0 AND vvz = 1 THEN GOTO 231.11
230.11  IF z = 1 THEN GOTO 231
  IF z = 2 THEN GOTO 232
  IF z = 3 THEN GOTO 233
  IF z = 4 THEN GOTO 234
  IF z = 5 THEN GOTO 235
  IF z = 6 THEN GOTO 236
 
231  INPUT " Prav.krai X, Y "; Xpr, Ypr
     INPUT " Lev.krai X, Y "; Xlev, Ylev
     INPUT " h ZO = "; hc
231.11 GOTO 240
232  INPUT " NKP "; nkp
     INPUT " Prav.krai A, D, Mc "; Apr, DPr, Mcpr
     INPUT " Lev.krai A, D, Mc "; Alev, Dlev, Mclev
     IF Mcpr = 0 AND Mclev = 0 THEN INPUT " h ZO = "; hc
   IF nkp = 1 THEN Xkp = Xkp1: Ykp = Ykp1: hkp = hkp1
   IF nkp = 2 THEN Xkp = Xkp2: Ykp = Ykp2: hkp = hkp2
   IF nkp = 3 THEN Xkp = Xkp3: Ykp = Ykp3: hkp = hkp3
   IF nkp = 4 THEN Xkp = Xkp4: Ykp = Ykp4: hkp = hkp4

      Xpr = COS(Apr / 100 * 6 * 3.141592 / 180) * DPr + Xkp
      Ypr = SIN(Apr / 100 * 6 * 3.141592 / 180) * DPr + Ykp
      hpr = Mcpr * (DPr * .001) * 1.05 + hkp
      Xlev = COS(Alev / 100 * 6 * 3.141592 / 180) * Dlev + Xkp
      Ylev = SIN(Alev / 100 * 6 * 3.141592 / 180) * Dlev + Ykp
      hlev = Mclev * (Dlev * .001) * 1.05 + hkp
      IF hc = 0 THEN hc = (hpr - hlev) / 2 + hlev

     GOTO 240
233  INPUT " NKP-LEV, PRAV "; nnpl, nnpp
     INPUT " Prav.krai Alev, Aprav "; Alevp, Aprp
     INPUT " Lev.krai Alev, Aprav "; Alevl, Aprl
     INPUT " h ZO = "; hc
     Alev = Alevp: Aprav = Aprp
     GOSUB 228
     Xpr = Xc: Ypr = Yc
     Alev = Alevl: Aprav = Aprl
     GOSUB 228
     Xlev = Xc: Ylev = Yc
     GOTO 240
234  INPUT " Zentr X, Y, Aat "; Xze, Yze, Aat
     INPUT " hze "; hc
234.11  GOSUB 234.1
   GOTO 240.1
235  INPUT " NKP "; nkp
   IF nkp = 1 THEN Xkp = Xkp1: Ykp = Ykp1: hkp = hkp1
   IF nkp = 2 THEN Xkp = Xkp2: Ykp = Ykp2: hkp = hkp2
   IF nkp = 3 THEN Xkp = Xkp3: Ykp = Ykp3: hkp = hkp3
   IF nkp = 4 THEN Xkp = Xkp4: Ykp = Ykp4: hkp = hkp4
     INPUT " Zentr A, D, Mc, Aat "; Aze, Dze, Mc, Aat
     IF Mc = 0 THEN INPUT " hze "; hc
   Xze = COS(Aze / 100 * 6 * 3.141592 / 180) * Dze + Xkp
   Yze = SIN(Aze / 100 * 6 * 3.141592 / 180) * Dze + Ykp
   IF hc = 0 THEN hc = Mc * (Dze * .001) * 1.05 + hkp
      GOSUB 234.1
      GOTO 240.1
236  INPUT " Zentr Alev.ze, NKP "; Alev, nnpl
     INPUT " Zentr Apr.ze, NKP"; Aprav, nnpp
     INPUT " Aat "; Aat
     INPUT " hze "; hc
     GOSUB 228
     Xze = Xc: Yze = Yc
     GOSUB 234.1
     GOTO 240.1
'''Flangi
240 dxzo = Xlev - Xpr: dyzo = Ylev - Ypr
    Fr.zo = SQR(dxzo ^ 2 + dyzo ^ 2)
    Azo = ABS(ATN(dyzo / (dxzo + .1)) / 3.141592 * 30) * 100
  IF dxzo > 0 AND dyzo > 0 THEN Ygol.zo = INT(Azo)
  IF dxzo < 0 AND dyzo > 0 THEN Ygol.zo = INT(3000 - Azo)
  IF dxzo < 0 AND dyzo < 0 THEN Ygol.zo = INT(3000 + Azo)
  IF dxzo > 0 AND dyzo < 0 THEN Ygol.zo = INT(6000 - Azo)
 
  IF kto.str = 1 AND Fr.zo < Front THEN dzo = Fr.zo / 6
  IF kto.str = 1 AND Fr.zo > Front THEN dzo = Front / 6
  IF kto.str = 2 OR kto.str = 3 OR kto.str = 4 AND Fr.zo < Front THEN dzo = Fr.zo / 4
  IF kto.str = 2 OR kto.str = 3 OR kto.str = 4 AND Fr.zo > Front THEN dzo = Front / 4
  IF kto.str = 5 OR kto.str = 6 OR kto.str = 7 AND Fr.zo < Front THEN dzo = Fr.zo / 2
  IF kto.str = 5 OR kto.str = 6 OR kto.str = 7 AND Fr.zo > Front THEN dzo = Front / 2
240.01
'1B
   Xzzo1 = COS(Ygol.zo / 100 * 6 * 3.141592 / 180) * dzo + Xpr
   Yzzo1 = SIN(Ygol.zo / 100 * 6 * 3.141592 / 180) * dzo + Ypr
'2B
   Xzzo2 = COS(Ygol.zo / 100 * 6 * 3.141592 / 180) * dzo * 3 + Xpr
   Yzzo2 = SIN(Ygol.zo / 100 * 6 * 3.141592 / 180) * dzo * 3 + Ypr
'3B
   Xzzo3 = COS(Ygol.zo / 100 * 6 * 3.141592 / 180) * dzo * 5 + Xpr
   Yzzo3 = SIN(Ygol.zo / 100 * 6 * 3.141592 / 180) * dzo * 5 + Ypr
 IF kto.str = 3 THEN Xzzo3 = Xzzo2: Yzzo3 = Yzzo2: Xzzo2 = 0: Yzzo2 = 0
 IF kto.str = 4 THEN Xzzo3 = Xzzo2: Yzzo3 = Yzzo2: Xzzo2 = Xzzo1: Yzzo2 = Yzzo1: Xzzo1 = 0: Yzzo1 = 0
 IF kto.str = 6 THEN Xzzo2 = Xzzo1: Yzzo2 = Yzzo1: Xzzo1 = 0: Yzzo1 = 0: Xzzo3 = 0: Yzzo3 = 0
 IF kto.str = 5 THEN Xzzo2 = 0: Yzzo2 = 0: Xzzo3 = 0: Yzzo3 = 0
 IF kto.str = 7 THEN Xzzo3 = Xzzo1: Yzzo3 = Yzzo1: Xzzo1 = 0: Yzzo1 = 0: Xzzo2 = 0: Yzzo2 = 0
240.1  Xc1 = Xzzo1: Yc1 = Yzzo1: Xc2 = Xzzo2: Yc2 = Yzzo2: Xc3 = Xzzo3: Yc3 = Yzzo3
 
 IF Fr.zo > Front THEN
 Front = Front
 ELSEIF Fr.zo < Front AND Fr.zo > 0 THEN
 Front = Fr.zo
 ELSE
 Front = Front
 END IF
 IF kto.str = 1 THEN bat.ych = Front / 3
 IF kto.str > 1 AND kto.str < 5 THEN bat.ych = Front / 2
 IF kto.str > 4 THEN bat.ych = Front
 IF kto.str = 1 OR kto.str = 2 OR kto.str = 3 OR kto.str = 5 THEN bat.ych1 = bat.ych
 IF kto.str = 1 OR kto.str = 2 OR kto.str = 4 OR kto.str = 6 THEN bat.ych2 = bat.ych
 IF kto.str = 1 OR kto.str = 3 OR kto.str = 4 OR kto.str = 7 THEN bat.ych3 = bat.ych
 IF Aat <> 0 AND z > 3 THEN
 Aatzo = Aat
 ELSE
        IF vidog = 1 THEN
                IF Ygol.zo + 1500 >= 6000 THEN
                Aatzo = Ygol.zo + 1500 - 6000
                ELSE
                Aatzo = Ygol.zo + 1500
                END IF
        ELSE
                IF Ygol.zo - 1500 <= 0 THEN
                Aatzo = Ygol.zo + 6000 - 1500
                ELSE
                Aatzo = Ygol.zo - 1500
                END IF
        END IF
 END IF
        IF vidog = 1 THEN
                Pr.Aat = Aatzo
                ELSE
                        IF Aatzo + 3000 >= 6000 THEN
                        Pr.Aat = Aatzo + 3000 - 6000
                        ELSE
                        Pr.Aat = Aatzo + 3000
                        END IF
 END IF
 
 PRINT "<< RYB1 >>"; " Front = "; INT(Front); " Realnui Front = "; INT(Fr.zo)

 GOSUB 50
 IF Ygol.t1 <= 1500 AND Pr.Aat >= 4500 THEN
 Yg.s1 = ABS(Ygol.t1 + 6000 - Pr.Aat)
 ELSEIF Ygol.t1 > 4500 AND Pr.Aat < 1500 THEN
 Yg.s1 = ABS(Ygol.t1 - (Pr.Aat + 6000))
 ELSE
 Yg.s1 = ABS(Ygol.t1 - Pr.Aat)
 END IF

 IF Ygol.t2 <= 1500 AND Pr.Aat >= 4500 THEN
 Yg.s2 = ABS(Ygol.t2 + 6000 - Pr.Aat)
 ELSEIF Ygol.t2 > 4500 AND Pr.Aat < 1500 THEN
 Yg.s2 = ABS(Ygol.t2 - (Pr.Aat + 6000))
 ELSE
 Yg.s2 = ABS(Ygol.t2 - Pr.Aat)
 END IF

 IF Ygol.t3 <= 1500 AND Pr.Aat >= 4500 THEN
 Yg.s3 = ABS(Ygol.t3 + 6000 - Pr.Aat)
 ELSEIF Ygol.t3 > 4500 AND Pr.Aat < 1500 THEN
 Yg.s3 = ABS(Ygol.t3 - (Pr.Aat + 6000))
 ELSE
 Yg.s3 = ABS(Ygol.t3 - Pr.Aat)
 END IF

 int.ve1 = INT(bat.ych1 / (Dt1 * .001 + .001) * .95)
 int.ve2 = INT(bat.ych2 / (Dt2 * .001 + .001) * .95)
 int.ve3 = INT(bat.ych3 / (Dt3 * .001 + .001) * .95)
  sk1 = INT(bat.ych1 / 4 / (dXtus11 + .001)): sk2 = INT(bat.ych2 / 4 / (dXtus2 + .001)): sk3 = INT(bat.ych3 / 4 / (dXtus3 + .001))
 GOSUB 240.11
 GOSUB 105.1
SLEEP

'''''''''''''''''''''2RYB
'1B'2B'3B
N = 1
ryb = ryb - 1
inter = 0
241 FOR ryb = 1 TO ryb
N = N + 1
inter = inter + inter1
GOSUB 250
 Xc1 = Xryb1: Yc1 = Yryb1: Xc2 = Xryb2: Yc2 = Yryb2: Xc3 = Xryb3: Yc3 = Yryb3
GOSUB 50
241.1
PRINT "<< RYB >>"; "("; N; ")"
 GOSUB 240.11
 GOSUB 105.1
SLEEP

NEXT ryb
  
 GOTO 0.42
'''''''''''''''''''''''''''''''KOLONNA'''''''''''''''''''''''''''''''''
260 PRINT "KOLONNA"
    INPUT " Vr.ypregd "; Vy
    INPUT " Vr.zasechki "; VZ
    PRINT " Zasechka (X,Y-1)_(A,D-2)_(SOPR-3)"
    INPUT ksc
    IF ksc = 1 THEN GOTO 261
    IF ksc = 2 THEN GOTO 262
    IF ksc = 3 THEN GOTO 263
261 INPUT " X1, Y1 "; X1, Y1
    INPUT " X2, Y2 "; X2, Y2
    INPUT " hc "; hc
    GOTO 265
262 INPUT " NKP "; nkp
    INPUT " A1, D1 "; a1, D1
    INPUT " A2, D2 "; a2, D2
    INPUT " hc "; hc
    GOTO 264
263 INPUT " NP-LEV, PRAV "; nnpl, nnpp
    INPUT " A-LEV1, PRAV1 "; Alev, Aprav
    GOSUB 228
    X1 = Xc: Y1 = Yc
    INPUT " A-LEV2, PRAV2 "; Alev, Aprav
    GOSUB 228
    X2 = Xc: Y2 = Yc
    INPUT "hc"; hc
    GOTO 265
264
   IF nkp = 1 THEN Xkp = Xkp1: Ykp = Ykp1: hkp = hkp1
   IF nkp = 2 THEN Xkp = Xkp2: Ykp = Ykp2: hkp = hkp2
   IF nkp = 3 THEN Xkp = Xkp3: Ykp = Ykp3: hkp = hkp3
   IF nkp = 4 THEN Xkp = Xkp4: Ykp = Ykp4: hkp = hkp4
   X1 = COS(a1 / 100 * 6 * 3.141592 / 180) * D1 + Xkp
   Y1 = SIN(a1 / 100 * 6 * 3.141592 / 180) * D1 + Ykp
   X2 = COS(a2 / 100 * 6 * 3.141592 / 180) * D2 + Xkp
   Y2 = SIN(a2 / 100 * 6 * 3.141592 / 180) * D2 + Ykp
265 dx = X2 - X1: DY = Y2 - Y1
   D = INT(SQR(dx ^ 2 + DY ^ 2))
   Ak = ABS(ATN(DY / (dx + .1)) / 3.141592 * 30) * 100
 IF dx > 0 AND DY > 0 THEN Ygol.t = INT(Ak)
 IF dx < 0 AND DY > 0 THEN Ygol.t = INT(3000 - Ak)
 IF dx < 0 AND DY < 0 THEN Ygol.t = INT(3000 + Ak)
 IF dx > 0 AND DY < 0 THEN Ygol.t = INT(6000 - Ak)
   Xc = COS(Ygol.t / 100 * 6 * 3.141592 / 180) * D * (Vy / VZ) + X2
   Yc = SIN(Ygol.t / 100 * 6 * 3.141592 / 180) * D * (Vy / VZ) + Y2
 GOSUB 50
 GOTO 104.2
''''''''''''''''''''''RAZMERU ZELI'''''''''''''''''''''''''''''''''''
270
271 IF q = 15 THEN
        Fr1 = 300: Gl1 = 300
        ELSE
        Fr1 = Fr1: Gl1 = Gl1
        END IF
    Veer1B = INT(Fr1 / ((Dt1 + .001) * .001) * .95)
    Veer2B = INT(Fr1 / ((Dt2 + .001) * .001) * .95)
    Veer3B = INT(Fr1 / ((Dt3 + .001) * .001) * .95)
    sk.shk1 = CINT(CINT(Gl1 / 3) / (dXtus11 + .001))
    sk.shk2 = INT(CINT((Gl1 + .001) / 3) / (dXtus2 + .001))
    sk.shk3 = INT(CINT((Gl1 + .001) / 3) / (dXtus3 + .001))
    IF Gl1 < 100 THEN sk.shk1 = 0: sk.shk2 = 0: sk.shk3 = 0
 GOTO 104.1995
'''''''''''''''''''''''''PORAG NENAB ZELI''''''''''''''''''''''''''''''
280 PRINT "PORAGEN NENABLYD ZELI"
PORAGNENABZELI
GOTO 0.42
'''''''''''''''''''''''''''''OBEKT ATAKI''''''''''''''''''''''''''''''''''''
290
OBIEKTATAKI
GOTO 0.42
''''''''''''''''''''''''SPRAVKA''''''''''''''''''''''''''''''''''''''''''''''''''
700 PRINT "SPRAVKA"
SPRAVKA
 GOTO 0.42
''''''''''''''''''''''''''''''''ZAPIS ZEL''''''''''''''''''''''''''''''''''''''
800 PRINT "<<ZAPISAT ZEL>>"
ZAPISATZEL
805 GOTO 0.42
''''''''''''''''''''''''''''''Posmotret Zeli''''''''''''''''''''''''''''''''''''''
900 PRINT "<<POSMOTRET ZELI>>"
POSMOTRETZELI
905 GOTO 0.42
'''''''''''''''''''''''''POSMOTRET OP,NP'''''''''''''''''''''''''''''''''''''''''''''''
910
POSMOTRETOP
GOTO 0.42
'''''''''''''''''''''''''''''''OCHISTIT ZELI''''''''''''''''''''''''''''''''''''''
950  INPUT "Ochistit Zel-0, NZO-1, Tochk.Vstrech-2, PZO-3"; chza
OCHISTKA chza
GOTO 0.42
''''''''''''''''''''''''''''A-ataki''''''''''''''''''''''''''''''''''''''''''''''''''
1000 PRINT " A-ataki "
INPUT " X,Y-0, A,D-1, SOPR-2"; va
IF va = 0 THEN GOTO 1010
IF va = 1 THEN GOTO 1020
IF va = 2 THEN GOTO 1030
1010 INPUT "X1, Y1 "; X1, Y1
        INPUT "X2, Y2 "; X2, Y2
        GOTO 1040
1020 INPUT " NKP "; nkp
        INPUT " A1, D1 "; a1, D1
        INPUT " A2, D2 "; a2, D2
   IF nkp = 1 THEN Xkp = Xkp1: Ykp = Ykp1: hkp = hkp1
   IF nkp = 2 THEN Xkp = Xkp2: Ykp = Ykp2: hkp = hkp2
   IF nkp = 3 THEN Xkp = Xkp3: Ykp = Ykp3: hkp = hkp3
   IF nkp = 4 THEN Xkp = Xkp4: Ykp = Ykp4: hkp = hkp4
   X1 = COS(a1 / 100 * 6 * 3.141592 / 180) * D1 + Xkp
   Y1 = SIN(a1 / 100 * 6 * 3.141592 / 180) * D1 + Ykp
   X2 = COS(a2 / 100 * 6 * 3.141592 / 180) * D2 + Xkp
   Y2 = SIN(a2 / 100 * 6 * 3.141592 / 180) * D2 + Ykp
        GOTO 1040
1030 INPUT " NKP LEV, PRAV "; nnpl, nnpp
        INPUT " A1-LEV, PRAV "; Alev, Aprav
        GOSUB 228
        X1 = Xc: Y1 = Yc
        INPUT " A2-LEV, PRAV "; Alev, Aprav
        GOSUB 228
        X2 = Xc: Y2 = Yc
1040  dxa = X2 - X1: dya = Y2 - Y1
        Dta = INT(SQR(dxa ^ 2 + dya ^ 2))
        Aa = ABS(ATN(dya / (dxa + .1)) / 3.141592 * 30) * 100
         IF dxa > 0 AND dya > 0 THEN Aat = INT(Aa)
         IF dxa < 0 AND dya > 0 THEN Aat = INT(3000 - Aa)
         IF dxa < 0 AND dya < 0 THEN Aat = INT(3000 + Aa)
         IF dxa > 0 AND dya < 0 THEN Aat = INT(6000 - Aa)
PRINT " Dt = "; Dta; " Aat = "; Aat
GOTO 0.42
'''''''''''''''''''''''''''''''''''OGNEVUE podprogr'''''''''''''''''''''
      '1B
50.001 INPUT " RASCET POPRAVOK 1-Da, 0-Net "; ras
IF ras = 0 THEN GOTO 0.42
7100 IF ras = 1 THEN
        IF zar1 = 0 THEN
        PRINT " Zariad = POLNIY "
        ELSEIF zar1 = 5 THEN
        PRINT " Zariad = YMENSHENIY "
        ELSEIF zar1 = 1 THEN
        PRINT " Zariad = PERVIY "
        ELSEIF zar1 = 2 THEN
        PRINT " Zariad = VTOROI "
        ELSEIF zar1 = 3 THEN
        PRINT " Zariad = TRETIY "
        ELSEIF zar1 = 4 THEN PRINT " Zariad = CHETVERTIY "
        ELSE
        PRINT " Zariad = POLNIY "
        END IF
        INPUT " Ygol.t = "; Ygol.t1
        dhh1 = (h - 750) + ((h.met. - hop1) / 10)
        PRINT "..............................................................................."
7120 INPUT " Dt = "; Dt1
        IF Dt1 = 0 THEN GOTO 0.42
        GOTO 104.1
ELSE
END IF
50
ras = 0
2.5 dhh1 = (h - 750) + ((h.met. - hop1) / 10)
IF kop1 = 1 THEN GOTO 104.111
   IF zo11 = 1 THEN
   Xc = Xc1: Yc = Yc1: hc = hc
   ELSE
   Xc = Xc: Yc = Yc: hc = hc
   END IF
   Xc1 = Xc: Yc1 = Yc: hc1 = hc
   dx1 = Xc - Xop1
60 dy1 = Yc - Yop1
61 dh1 = hc - hop1
   Pi = 3.14159265358#
90.0 Dt1 = INT(SQR(dx1 ^ 2 + dy1 ^ 2) + .001)
91.0 Yr1 = CINT((dh1 / (Dt1 * .001 + .001)) * .95)
100 a1 = ABS(ATN(dy1 / (dx1 + .001)) / Pi * 30) * 100
101 IF dx1 > 0 AND dy1 > 0 THEN Ygol.t1 = CINT(a1)
102 IF dx1 < 0 AND dy1 > 0 THEN Ygol.t1 = CINT(3000 - a1)
103 IF dx1 < 0 AND dy1 < 0 THEN Ygol.t1 = CINT(3000 + a1)
104 IF dx1 > 0 AND dy1 < 0 THEN Ygol.t1 = CINT(6000 - a1)
104.1 IF Ygol.t1 <= 1500 AND OH1 >= 4500 THEN
      Dovor.t1 = Ygol.t1 + 6000 - OH1
      ELSEIF OH1 <= 1500 AND Ygol.t1 >= 4500 THEN
      Dovor.t1 = Ygol.t1 - (OH1 + 6000)
      ELSE
      Dovor.t1 = Ygol.t1 - OH1
      END IF
       Dt = Dt1: Ygol.t = Ygol.t1: dh = dh1
       IF zar1 = 0 THEN
       v01 = v0pol1
       ELSEIF zar1 = 5 THEN
       v01 = v0ymen1
       ELSEIF zar1 = 1 THEN
       v01 = v0perv1
       ELSEIF zar1 = 2 THEN
       v01 = v0vtor1
       ELSEIF zar1 = 3 THEN
       v01 = v0tret1
       ELSEIF zar1 = 4 THEN
       v01 = v0chetv1
       ELSE
       v01 = v0pol1
END IF
       zar = zar1
       IF stre = 1 THEN
       GOSUB 390
       ELSE
       GOSUB 90
       END IF
       IF snvz1 <> 0 THEN ts1 = ts: dXtus11 = dXtus
       dddt1 = dddt: tz = tz1: zc1 = zc
       GOSUB 320
       IF rep1 = 1 OR vsem = 1 THEN
       pop.v.nap. = (dDov1 / (Dret1 + .001)) * Dt1
       ELSE
       pop.v.nap. = dzwc * wz + zc
       END IF
       ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
       IF rep1 = 1 OR vsem = 1 THEN
       pop.v.d = (dDr1 / (Dret1 + .001)) * Dt1
       ELSE
        pop.v.d = dXwc * Wx + dXhc * dhh1 + dXtc * dddt1 + dXv0c * (v01 + dV0)
        IF q = 35 THEN GOTO 9200
        IF pop.v.d <= 0 THEN
        Dtk = Dt1 - 2000
        ELSE
        Dtk = Dt1 + 2000
        END IF
        Dt = Dtk
        IF stre = 1 THEN
                GOSUB 390
                ELSE
                GOSUB 90
        END IF
        pop.v.dk = dXwc * Wx + dXhc * dhh1 + dXtc * dddt1 + dXv0c * (v01 + dV0)
        pop.v.napk = dzwc * wz + zc
       END IF
       Dtisch = Dt1 - pop.v.d
       Dtischk = Dtk - pop.v.dk:
       IF pop.v.d < 0 THEN
                Kpop = (pop.v.d - pop.v.dk) / (Dtisch - Dtischk)
       ELSE
       Kpop = (pop.v.dk - pop.v.d) / (Dtischk - Dtisch)
       END IF
       IF pop.v.d < 0 THEN
       pop.v.d = (ABS(pop.v.d) * Kpop - pop.v.d) * -1
       ELSE
       pop.v.d = ABS(pop.v.d) * Kpop + pop.v.d
       END IF
       ''''''''''''''''''''''''''''''''''''''''''''''''''
9200   pop.v.d1 = pop.v.d: Disch = Dt1 + pop.v.d: Disch1 = Disch
        IF q = 35 THEN
                ELSE
                Kpopnap = pop.v.nap. - pop.v.napk
                Kpopnap = ABS(Kpopnap + .001) / ABS(Dtisch - Dtischk)
                IF pop.v.nap. <= 0 AND pop.v.napk >= 0 THEN
                        pop.v.nap. = Kpopnap * ABS(pop.v.d) + pop.v.nap.
                        ELSEIF pop.v.nap. < 0 AND pop.v.napk <= 0 AND pop.v.napk > pop.v.nap. THEN
                        pop.v.nap. = Kpopnap * ABS(pop.v.d) + pop.v.nap.
                        ELSEIF pop.v.nap. < 0 AND pop.v.napk <= 0 AND pop.v.napk < pop.v.nap. THEN
                        pop.v.nap. = (Kpopnap * ABS(pop.v.d) * -1) + pop.v.nap.
                        ELSEIF pop.v.nap. > 0 AND pop.v.napk > 0 AND pop.v.nap. > pop.v.napk THEN
                        pop.v.nap. = (Kpopnap * ABS(pop.v.d) * -1) + pop.v.nap.
                        ELSE
                        pop.v.nap. = Kpopnap * ABS(pop.v.d) + pop.v.nap.
                END IF
       END IF
       pop.v.nap.1 = pop.v.nap.: dov.isch1 = INT(Dovor.t1 + pop.v.nap.)
        dhh = dhh1: dddt = dddt1: dV00 = (v01 + dV0): rep = rep1
      IF rep1 = 1 THEN
        dN = (dN / (Dret1 + .001)) * Dt1
        ELSE
      END IF
IF q = 35 THEN
ELSE
      IF snvz1 = 0 AND stre = 1 THEN
      GOSUB 392.01
      ELSEIF snvz1 = 0 AND stre = 0 THEN
      GOSUB 92.01
      ELSEIF snvz1 = 1 AND stre = 0 THEN
      GOSUB 300
      ELSEIF snvz1 = 2 AND stre = 0 THEN
      GOSUB 400
      ELSEIF snvz1 = 3 AND stre = 0 THEN
      GOSUB 500
      ELSEIF snvz1 = 4 AND stre = 0 THEN
      GOSUB 600
      ELSE
      GOSUB 392.01
END IF
END IF
       IF stre = 1 THEN
        pric1 = Pric.isch - Yr1
        ELSE
        pric1 = Pric.isch + Yr1
       END IF
        Yr = ABS(Yr1): Yrr = Yr1: N1 = N: dNtus1 = dNtus: Ygpad1 = Ygpad: Ygvozv1 = Ygvozv: Vustra1 = Vustra
       IF snvz1 = 0 THEN ts1 = ts: dXtus11 = dXtus
       IF snvz1 = 0 OR snvz = 1 THEN dNtus1 = 0
       IF stre = 1 THEN
       GOSUB 392.331
       daep = kpe * Yr1: pr.eps1 = CINT(pric1 - daep)
       ELSE
       GOSUB 92.331
       daep = kpe * Yr1: pr.eps1 = CINT(pric1 + daep)
       END IF
        Xc1 = Xc: Yc1 = Yc: hc1 = hc
104.111
 ' 2B
50.002
7200 IF ras = 1 THEN
        zar2 = zar1
         Ygol.t2 = Ygol.t1
        dhh2 = (h - 750) + ((h.met. - hop2) / 10)
7220
         Dt2 = Dt1
        IF Dt1 = 0 THEN GOTO 0.42
        GOTO 104.192
        ELSE
END IF
104.11 ras = 0
2.51 dhh2 = (h - 750) + ((h.met. - hop2) / 10)
IF kop2 = 1 THEN GOTO 104.193
        IF zo11 = 1 THEN
         Xc = Xc2: Yc = Yc2: hc = hc
         ELSE
         Xc = Xc: Yc = Yc: hc = hc
         END IF
         Xc2 = Xc: Yc2 = Yc: hc2 = hc
        dx2 = Xc - Xop2
104.12  dy2 = Yc - Yop2
104.13  dh2 = hc - hop2
104.14  Dt2 = INT(SQR(dx2 ^ 2 + dy2 ^ 2))
104.15  Yr2 = CINT((dh2 / (Dt2 * .001 + .1)) * .95)
104.16  a2 = ABS(ATN(dy2 / (dx2 + .001)) / Pi * 30) * 100
104.17  IF dx2 > 0 AND dy2 > 0 THEN Ygol.t2 = CINT(a2)
104.18  IF dx2 < 0 AND dy2 > 0 THEN Ygol.t2 = CINT(3000 - a2)
104.19  IF dx2 < 0 AND dy2 < 0 THEN Ygol.t2 = CINT(3000 + a2)
104.191  IF dx2 > 0 AND dy2 < 0 THEN Ygol.t2 = CINT(6000 - a2)
104.192 IF Ygol.t2 <= 1500 AND OH2 >= 4500 THEN
        dovor.t2 = Ygol.t2 + 6000 - OH2
        ELSEIF OH2 <= 1500 AND Ygol.t2 >= 4500 THEN
         dovor.t2 = Ygol.t2 - (OH2 + 6000)
     ELSE
         dovor.t2 = Ygol.t2 - (OH2)
       END IF
       Dt = Dt2: Ygol.t = Ygol.t2: dh = dh2
       IF zar2 = 0 THEN
       v02 = v0pol2
       ELSEIF zar2 = 5 THEN
       v02 = v0ymen2
       ELSEIF zar2 = 1 THEN
       v02 = v0perv2
       ELSEIF zar2 = 2 THEN
       v02 = v0vtor2
       ELSEIF zar2 = 3 THEN
       v02 = v0tret2
       ELSEIF zar2 = 4 THEN
       v02 = v0chetv2
       ELSE
       v02 = v0pol2
     END IF
       zar = zar2
       IF stre = 1 THEN
       GOSUB 390
       ELSE
       GOSUB 90
       END IF
       IF snvz2 <> 0 THEN ts2 = ts: dXtus2 = dXtus
        tz = tz2: zc2 = zc
        GOSUB 320
       IF rep2 = 1 OR vsem = 1 THEN
       pop.v.nap. = (dDov2 / (Dret2 + .001)) * Dt2
       ELSE
       pop.v.nap. = dzwc * wz + zc
       END IF
       dddt2 = dddt
       IF rep2 = 1 OR vsem = 1 THEN
       pop.v.d = (dDr2 / (Dret2 + .001)) * Dt2
       ELSE
       pop.v.d = dXwc * Wx + dXhc * dhh2 + dXtc * dddt2 + dXv0c * (v02 + dV0)
       IF q = 35 THEN GOTO 9300
        IF pop.v.d < 0 THEN
        Dtk = Dt2 - 1000
        ELSE
        Dtk = Dt2 + 1000
        END IF
        Dt = Dtk
        IF stre = 1 THEN
                GOSUB 390
                ELSE
                GOSUB 90
        END IF
        pop.v.dk = dXwc * Wx + dXhc * dhh2 + dXtc * dddt2 + dXv0c * (v02 + dV0)
        pop.v.napk = dzwc * wz + zc
       END IF
       Dtisch = Dt2 - pop.v.d
       Dtischk = Dtk - pop.v.dk
       IF pop.v.d < 0 THEN
       Kpop = (pop.v.d - pop.v.dk) / (Dtisch - Dtischk)
       ELSE
       Kpop = (pop.v.dk - pop.v.d) / (Dtischk - Dtisch)
       END IF
       IF pop.v.d < 0 THEN
       pop.v.d = (ABS(pop.v.d) * Kpop - pop.v.d) * -1
       ELSE
       pop.v.d = ABS(pop.v.d) * Kpop + pop.v.d
       END IF
9300   pop.v.d2 = pop.v.d: Disch = Dt2 + pop.v.d: Disch2 = Disch
        IF q = 35 THEN
                ELSE
                Kpopnap = pop.v.nap. - pop.v.napk
                Kpopnap = ABS(Kpopnap + .001) / ABS(Dtisch - Dtischk)
                IF pop.v.nap. <= 0 AND pop.v.napk >= 0 THEN
                        pop.v.nap. = Kpopnap * ABS(pop.v.d) + pop.v.nap.
                        ELSEIF pop.v.nap. < 0 AND pop.v.napk <= 0 AND pop.v.napk > pop.v.nap. THEN
                        pop.v.nap. = Kpopnap * ABS(pop.v.d) + pop.v.nap.
                        ELSEIF pop.v.nap. < 0 AND pop.v.napk <= 0 AND pop.v.napk < pop.v.nap. THEN
                        pop.v.nap. = (Kpopnap * ABS(pop.v.d) * -1) + pop.v.nap.
                        ELSEIF pop.v.nap. > 0 AND pop.v.napk > 0 AND pop.v.nap. > pop.v.napk THEN
                        pop.v.nap. = (Kpopnap * ABS(pop.v.d) * -1) + pop.v.nap.
                        ELSE
                        pop.v.nap. = Kpopnap * ABS(pop.v.d) + pop.v.nap.
                END IF
       END IF
       pop.v.nap.2 = pop.v.nap.: dov.isch2 = CINT(dovor.t2 + pop.v.nap.)
      dhh = dhh2: dddt = dddt2: dV00 = (v02 + dV0): rep = rep2
      IF rep2 = 1 THEN
        dN = (dN / (Dret2 + .001)) * Dt2
        ELSE
      END IF
IF q = 35 THEN
ELSE
      IF snvz2 = 0 AND stre = 1 THEN
      GOSUB 392.01
      ELSEIF snvz2 = 0 AND stre = 0 THEN
      GOSUB 92.01
      ELSEIF snvz2 = 1 AND stre = 0 THEN
      GOSUB 300
      ELSEIF snvz2 = 2 AND stre = 0 THEN
      GOSUB 400
      ELSEIF snvz2 = 3 AND stre = 0 THEN
      GOSUB 500
      ELSEIF snvz2 = 4 AND stre = 0 THEN
      GOSUB 600
      ELSE
      GOSUB 392.01
      END IF
END IF
       Yr = ABS(Yr2): Yrr = Yr2: N2 = N: dNtus2 = dNtus: Ygpad2 = Ygpad: Ygvozv2 = Ygvozv: Vustra2 = Vustra
        IF snvz2 = 0 THEN ts2 = ts: dXtus2 = dXtus
        IF snvz2 = 0 OR snvz = 1 THEN dNtus2 = 0
       IF stre = 1 THEN
        pric2 = Pric.isch - Yr2
        ELSE
        pric2 = Pric.isch + Yr2
       END IF
       IF stre = 1 THEN
       GOSUB 392.331
       daep = kpe * Yr2: pr.eps2 = INT(pric2 - daep)
       ELSE
       GOSUB 92.331
       daep = kpe * Yr2: pr.eps2 = INT(pric2 + daep)
       END IF
      Xc2 = Xc: Yc2 = Yc: hc2 = hc
  '3B
50.003
7300 IF ras = 1 THEN
        zar3 = zar1
         Ygol.t3 = Ygol.t1
        dhh3 = (h - 750) + ((h.met. - hop3) / 10)
7320    Dt3 = Dt1
        IF Dt1 = 0 THEN GOTO 0.42
        GOTO 104.1994
ELSE
END IF
104.193 ras = 0
2.52 dhh3 = (h - 750) + ((h.met. - hop3) / 10)
IF kop3 = 1 THEN GOTO 104.19941
        IF zo11 = 1 THEN
          Xc = Xc3: Yc = Yc3: hc = hc
          ELSE
          Xc = Xc: Yc = Yc: hc = hc
          END IF
          Xc3 = Xc: Yc3 = Yc: hc3 = hc
         dx3 = Xc - Xop3
104.194  dy3 = Yc - Yop3
104.195  dh3 = hc - hop3
104.196   Dt3 = INT(SQR(dx3 ^ 2 + dy3 ^ 2))
104.197   Yr3 = CINT((dh3 / (Dt3 * .001 + .1)) * .95)
104.198  a3 = ABS(ATN(dy3 / (dx3 + .001)) / Pi * 30) * 100
104.199  IF dx3 > 0 AND dy3 > 0 THEN Ygol.t3 = CINT(a3)
104.1991  IF dx3 < 0 AND dy3 > 0 THEN Ygol.t3 = CINT(3000 - a3)
104.1992  IF dx3 < 0 AND dy3 < 0 THEN Ygol.t3 = CINT(3000 + a3)
104.1993  IF dx3 > 0 AND dy3 < 0 THEN Ygol.t3 = CINT(6000 - a3)
104.1994  IF Ygol.t3 <= 1500 AND OH3 >= 4500 THEN
          dovor.t3 = Ygol.t3 + 6000 - OH3
          ELSEIF OH3 <= 1500 AND Ygol.t3 >= 4500 THEN
         dovor.t3 = Ygol.t3 - (OH3 + 6000)
     ELSE
         dovor.t3 = Ygol.t3 - (OH3)
       END IF
     Dt = Dt3: Ygol.t = Ygol.t3: dh = dh3
       IF zar3 = 0 THEN
       v03 = v0pol3
       ELSEIF zar3 = 5 THEN
       v03 = v0ymen3
       ELSEIF zar3 = 1 THEN
       v03 = v0perv3
       ELSEIF zar3 = 2 THEN
       v03 = v0vtor3
       ELSEIF zar3 = 3 THEN
       v03 = v0tret3
       ELSEIF zar3 = 4 THEN
       v03 = v0chet3
       ELSE
       v03 = v0pol3
       END IF
     zar = zar3
       IF stre = 1 THEN
       GOSUB 390
       ELSE
       GOSUB 90
       END IF
       IF snvz3 <> 0 THEN ts3 = ts: dXtus3 = dXtus
     tz = tz3: zc3 = zc
     GOSUB 320
       IF rep3 = 1 OR vsem = 1 THEN
       pop.v.nap. = (dDov3 / (Dret3 + .001)) * Dt3
       ELSE
       pop.v.nap. = dzwc * wz + zc
       END IF
       dddt3 = dddt
       IF rep3 = 1 OR vsem = 1 THEN
       pop.v.d = (dDr3 / (Dret3 + .001)) * Dt3
       ELSE
       pop.v.d = dXwc * Wx + dXhc * dhh3 + dXtc * dddt3 + dXv0c * (v03 + dV0)
        IF q = 35 THEN GOTO 9400
        IF pop.v.d < 0 THEN
        Dtk = Dt3 - 1000
        ELSE
        Dtk = Dt3 + 1000
        END IF
        Dt = Dtk
        IF stre = 1 THEN
                GOSUB 390
                ELSE
                GOSUB 90
        END IF
        pop.v.dk = dXwc * Wx + dXhc * dhh3 + dXtc * dddt3 + dXv0c * (v03 + dV0)
        pop.v.napk = dzwc * wz + zc
       END IF
       Dtisch = Dt3 - pop.v.d
       Dtischk = Dtk - pop.v.dk
       IF pop.v.d < 0 THEN
       Kpop = (pop.v.d - pop.v.dk) / (Dtisch - Dtischk)
       ELSE
       Kpop = (pop.v.dk - pop.v.d) / (Dtischk - Dtisch)
       END IF
       IF pop.v.d < 0 THEN
       pop.v.d = (ABS(pop.v.d) * Kpop - pop.v.d) * -1
       ELSE
       pop.v.d = ABS(pop.v.d) * Kpop + pop.v.d
       END IF
9400   pop.v.d3 = pop.v.d: Disch = Dt3 + pop.v.d: Disch3 = Disch
        IF q = 35 THEN
                ELSE
                Kpopnap = pop.v.nap. - pop.v.napk
                Kpopnap = ABS(Kpopnap + .001) / ABS(Dtisch - Dtischk)
                IF pop.v.nap. <= 0 AND pop.v.napk >= 0 THEN
                        pop.v.nap. = Kpopnap * ABS(pop.v.d) + pop.v.nap.
                        ELSEIF pop.v.nap. < 0 AND pop.v.napk <= 0 AND pop.v.napk > pop.v.nap. THEN
                        pop.v.nap. = Kpopnap * ABS(pop.v.d) + pop.v.nap.
                        ELSEIF pop.v.nap. < 0 AND pop.v.napk <= 0 AND pop.v.napk < pop.v.nap. THEN
                        pop.v.nap. = (Kpopnap * ABS(pop.v.d) * -1) + pop.v.nap.
                        ELSEIF pop.v.nap. > 0 AND pop.v.napk > 0 AND pop.v.nap. > pop.v.napk THEN
                        pop.v.nap. = (Kpopnap * ABS(pop.v.d) * -1) + pop.v.nap.
                        ELSE
                        pop.v.nap. = Kpopnap * ABS(pop.v.d) + pop.v.nap.
                END IF
       END IF
       pop.v.nap.3 = pop.v.nap.: dov.isch3 = CINT(dovor.t3 + pop.v.nap.)
      dhh = dhh3: dddt = dddt3: dV00 = (v03 + dV0): rep = rep3
      IF rep3 = 1 THEN
        dN = (dN / (Dret3 + .001)) * Dt3
        ELSE
      END IF
IF q = 35 THEN
ELSE
      IF snvz3 = 0 AND stre = 1 THEN
      GOSUB 392.01
      ELSEIF snvz3 = 0 AND stre = 0 THEN
      GOSUB 92.01
      ELSEIF snvz3 = 1 AND stre = 0 THEN
      GOSUB 300
      ELSEIF snvz3 = 2 AND stre = 0 THEN
      GOSUB 400
      ELSEIF snvz3 = 3 AND stre = 0 THEN
      GOSUB 500
      ELSEIF snvz3 = 4 AND stre = 0 THEN
      GOSUB 600
      ELSE
      GOSUB 392.01
      END IF
       IF stre = 1 THEN
        pric3 = Pric.isch - Yr3
        ELSE
        pric3 = Pric.isch + Yr3
       END IF
        Yr = ABS(Yr3): Yrr = Yr3: N3 = N: dNtus3 = dNtus: Ygpad3 = Ygpad: Ygvozv3 = Ygvozv: Vustra3 = Vustra
       IF snvz3 = 0 THEN ts3 = ts: dXtus3 = dXtus
       IF snvz3 = 0 OR snvz = 1 THEN dNtus3 = 0
       IF stre = 1 THEN
       GOSUB 392.331
       daep = kpe * Yr3: pr.eps3 = INT(pric3 - daep)
       ELSE
       GOSUB 92.331
       daep = kpe * Yr3: pr.eps3 = INT(pric3 + daep)
       END IF
END IF
       Xc3 = Xc: Yc3 = Yc: hc3 = hc
       IF ras = 1 THEN
                PRINT TAB(30); "<<POPRAVKI>> "
                PRINT " 1B "; TAB(30); " 2B "; TAB(60); " 3B "
                PRINT "dD="; INT(pop.v.d1); "dDov="; INT(pop.v.nap.1); TAB(30); "dD="; INT(pop.v.d2); "dDov="; INT(pop.v.nap.2); TAB(60); "dD="; INT(pop.v.d3); "dDov="; INT(pop.v.nap.3)
                PRINT "..............................................................................."
                        GOTO 7120
                        ELSE
                END IF
104.19941  GOTO 271
104.1995 IF zo11 <> 1 THEN GOTO 104.2
       IF q = 8 THEN GOTO 104.2
       RETURN
''''''''''''''''''''''''''POPRAVKI''''''''''''''''''''''''''''''''''''''''''''
90
   IF zar = 0 THEN
   OPEN "I", #1, "2C1P"
   ELSEIF zar = 5 THEN
   OPEN "I", #1, "2C1Y"
   ELSEIF zar = 1 THEN
   OPEN "I", #1, "2C11"
   ELSEIF zar = 2 THEN
   OPEN "I", #1, "2C12"
   ELSEIF zar = 3 THEN
   OPEN "I", #1, "2C13"
   ELSEIF zar = 4 THEN
   OPEN "I", #1, "2C14"
   ELSE
   OPEN "I", #1, "2C1P"
END IF
91 IF EOF(1) THEN GOTO 92.2
91.1 INPUT #1, ta1, ta2, ta3, ta4, ta5, ta6, ta7, ta8, ta9, ta10, ta11, ta12, ta13, ta14, ta15, ta16, ta17, ta18, ta19, ta20, ta21, ta22, ta23, ta24, ta25, ta26, ta27, ta28, ta29, ta30, ta31, ta32, ta33, ta34, ta35, ta36, ta37
IF Dt > 15200 THEN Dt = 15200
92 IF ta1 <= Dt THEN GOTO 92.1
 GOTO 91
92.1 Dta = ta1: Prta = ta2: dXtus = ta3: z = ta6: dzw = ta7: dxw = ta8: Ygvozv = ta13
 dxh = ta9: dxt = ta11: dxv0 = ta12: ybyl = ta18: ts = ta16: Ygpad = ta14: Vustra = ta17

92.2 CLOSE #1
   Dtt = Dt + 200
   IF zar = 0 THEN
   OPEN "I", #1, "2C1P"
   ELSEIF zar = 5 THEN
   OPEN "I", #1, "2C1Y"
   ELSEIF zar = 1 THEN
   OPEN "I", #1, "2C11"
   ELSEIF zar = 2 THEN
   OPEN "I", #1, "2C12"
   ELSEIF zar = 3 THEN
   OPEN "I", #1, "2C13"
   ELSEIF zar = 4 THEN
   OPEN "I", #1, "2C14"
   ELSE
   OPEN "I", #1, "2C1P"
END IF
911 IF EOF(1) THEN GOTO 92.21
91.11 INPUT #1, ta1, ta2, ta3, ta4, ta5, ta6, ta7, ta8, ta9, ta10, ta11, ta12, ta13, ta14, ta15, ta16, ta17, ta18, ta19, ta20, ta21, ta22, ta23, ta24, ta25, ta26, ta27, ta28, ta29, ta30, ta31, ta32, ta33, ta34, ta35, ta36, ta37
IF Dtt > 15200 THEN Dtt = 15200
921 IF ta1 <= Dtt THEN GOTO 92.11
 GOTO 911
92.11 dta1 = ta1: prta1 = ta2: dxtus1 = ta3: z1 = ta6: dzw1 = ta7: dxw1 = ta8
 dxh1 = ta9: dxt1 = ta11: dxv01 = ta12: ybyl1 = ta18

92.21 CLOSE #1

zc = ((z1 - z) / 200 * (Dt - Dta) + z) * -1
dzwc = ((dzw1 - dzw) / 200 * (Dt - Dta) + dzw) * -1 / 10
dXwc = ((dxw1 - dxw) / 200 * (Dt - Dta) + dxw) * -1 / 10
dXhc = ((dxw1 - dxw) / 200 * (Dt - Dta) + dxh) / 10
dXtc = ((dxt1 - dxt) / 200 * (Dt - Dta) + dxt) * -1 / 10
dXv0c = ((dxv01 - dxv0) / 200 * (Dt - Dta) + dxv0) * -1
IF met = 0 THEN
 Aw200 = Aw + 100: Aw400 = Aw + 200: Aw800 = Aw + 300: Aw1200 = Aw + 300: Aw1600 = Aw + 400
 Aw2000 = Aw + 400: Aw2400 = Aw + 400: Aw3000 = Aw + 500: Aw4000 = Aw + 500
ELSE
END IF
ybylc = ybyl * 100

 IF ybylc = 200 THEN aww = Aw200
 IF ybylc = 400 THEN aww = Aw400
 IF ybylc = 800 THEN aww = Aw800
 IF ybylc = 1200 THEN aww = Aw1200
 IF ybylc = 1600 THEN aww = Aw1600
 IF ybylc = 2000 THEN aww = Aw2000
 IF ybylc = 2400 THEN aww = Aw2400
 IF ybylc = 3000 THEN aww = Aw3000
 IF ybylc = 4000 THEN aww = Aw4000
IF Ygol.t - aww < 0 THEN
       aws = Ygol.t + 6000 - aww
   ELSE
   aws = Ygol.t - aww
   END IF
 IF ybylc = 200 THEN sw = w200
 IF ybylc = 400 THEN sw = w400
 IF ybylc = 800 THEN sw = w800
 IF ybylc = 1200 THEN sw = w1200
 IF ybylc = 1600 THEN sw = w1600
 IF ybylc = 2000 THEN sw = w2000
 IF ybylc = 2400 THEN sw = w2400
 IF ybylc = 3000 THEN sw = w3000
 IF ybylc = 4000 THEN sw = w4000

 Wx = ABS(sw * COS((aws / 100 * 6) * 3.141596 / 180))
 wz = ABS(sw * SIN((aws / 100 * 6) * 3.14159 / 180))

 IF aws <= 1500 OR aws >= 4500 THEN Wx = Wx * -1
 IF aws >= 3000 THEN wz = wz * -1

 IF ybylc = 200 THEN dddt = t200
 IF ybylc = 400 THEN dddt = t400
 IF ybylc = 800 THEN dddt = t800
 IF ybylc = 1200 THEN dddt = t1200
 IF ybylc = 1600 THEN dddt = t1600
 IF ybylc = 2000 THEN dddt = t2000
 IF ybylc = 2400 THEN dddt = t2400
 IF ybylc = 3000 THEN dddt = t3000
 IF ybylc = 4000 THEN dddt = t4000
 IF dddt >= 50 THEN dddt = (dddt - 50) * -1

  RETURN
'''''''''''''''''''''PRICEL''''''''''''''''''''''''''''''''''''''''
92.01
PRICELOFRGM zar, Disch, ts, dXtus, Ygvozv, Vustra, Pric.isch
92.323 RETURN
''''''''''''''''''''''''''''''KPE'''''''''''''''''''''''''''''''''''''''''
92.331
 Pric = Pric.isch
KPEnast zar, Pric, kpew, kpen, Yrr, kpe
   
  RETURN
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''


''''''''''''''''RYBEGI ZO podprogr'''''''''''''''''''''''''''''''''''''
250
'1B
  Xryb1 = COS(Aatzo / 100 * 6 * 3.141592 / 180) * inter + Xzzo1
  Yryb1 = SIN(Aatzo / 100 * 6 * 3.141592 / 180) * inter + Yzzo1
'2B
  Xryb2 = COS(Aatzo / 100 * 6 * 3.141592 / 180) * inter + Xzzo2
  Yryb2 = SIN(Aatzo / 100 * 6 * 3.141592 / 180) * inter + Yzzo2
'3B
  Xryb3 = COS(Aatzo / 100 * 6 * 3.141592 / 180) * inter + Xzzo3
  Yryb3 = SIN(Aatzo / 100 * 6 * 3.141592 / 180) * inter + Yzzo3

RETURN
228 ''''''''''''''''''''''SOPR podprog.''''''''''''''''''''''''''''''''
'LEV
  IF nnpl = 1 THEN Xl = Xkp1: Yl = Ykp1: hl = hkp1
  IF nnpl = 2 THEN Xl = Xkp2: Yl = Ykp2: hl = hkp2
  IF nnpl = 3 THEN Xl = Xkp3: Yl = Ykp3: hl = hkp3
  IF nnpl = 4 THEN Xl = Xkp4: Yl = Ykp4: hl = hkp4
'PRAV
  IF nnpp = 1 THEN Xp = Xkp1: Yp = Ykp1: hp = hkp1
  IF nnpp = 2 THEN Xp = Xkp2: Yp = Ykp2: hp = hkp2
  IF nnpp = 3 THEN Xp = Xkp3: Yp = Ykp3: hp = hkp3
  IF nnpp = 4 THEN Xp = Xkp4: Yp = Ykp4: hp = hkp4
SOPRIAGENKA Xl, Yl, hl, Xp, Yp, hp, Alev, Aprav, Mcl, Mcp, hc, Xc, Yc
  RETURN
''''''''''''''''''PZO-ZENTR,Aat podprog''''''''''''''''''''''''''''''''''''
234.1   IF Aat + 1500 >= 6000 THEN
                Yg3B = Aat + 1500 - 6000
                ELSE
                Yg3B = Aat + 1500
        END IF
        IF Aat - 1500 < 0 THEN
                Yg1B = Aat + 6000 - 1500
                ELSE
                Yg1B = Aat - 1500
        END IF
IF kto.str = 1 THEN dzo = Front / 3
IF kto.str = 2 THEN dzo = Front / 4
IF kto.str = 3 THEN dzo = Front / 4
IF kto.str = 4 THEN dzo = Front / 4
   Xzzo3 = COS(Yg3B / 100 * 6 * 3.141592 / 180) * dzo + Xze
   Yzzo3 = SIN(Yg3B / 100 * 6 * 3.141592 / 180) * dzo + Yze
   Xzzo1 = COS(Yg1B / 100 * 6 * 3.141592 / 180) * dzo + Xze
   Yzzo1 = SIN(Yg1B / 100 * 6 * 3.141592 / 180) * dzo + Yze
   Xzzo2 = Xze: Yzzo2 = Yze
IF kto.str > 1 THEN
        IF kto.str = 2 THEN Xzzo1 = Xzzo1: Yzzo1 = Yzzo1: Xzzo2 = Xzzo3: Yzzo2 = Yzzo3
        IF kto.str = 3 THEN Xzzo1 = Xzzo1: Yzzo1 = Yzzo1: Xzzo3 = Xzzo3: Yzzo3 = Yzzo3
        IF kto.str = 4 THEN Xzzo2 = Xzzo1: Yzzo2 = Yzzo1: Xzzo3 = Xzzo3: Yzzo3 = Yzzo3
        IF kto.str = 5 THEN Xzzo1 = Xze: Yzzo1 = Yze
        IF kto.str = 6 THEN Xzzo2 = Xze: Yzzo2 = Yze
        IF kto.str = 7 THEN Xzzo3 = Xze: Yzzo3 = Yze
        ELSE
END IF
RETURN

''''''''''''''''''''''dV0 podprog''''''''''''''''''''''''''''''''''''''''''''''
320
dV0111 tz, zar, dV0
 RETURN
'''''''''''''''''''''''DANNUE PO ZELI podprog'''''''''''''''''''''''''''
105.1 IF shkval2 = 1 THEN GOTO 113
INPUT "Zapisat RASCHET - 1, Net - 0 "; vvod
IF vvod = 1 THEN
        ZAPRASCHET Xc1, Xc2, Xc3, Yc1, Yc2, Yc3, hc1, hc2, hc3, opn1$, opn2$, opn3$, OH1, OH2, OH3
        ZAPRASCH1 rep1, rep2, rep3, vsem, zar1, zar2, zar3, snvz1, snvz2, snvz3, pr.eps1, pr.eps2, pr.eps3, N1, N2, N3, dov.isch1, dov.isch2, dov.isch3
        ZAPRASCH2 Veer1B, Veer2B, Veer3B, sk.shk1, sk.shk2, sk.shk3, dXtus11, dNtus1, dXtus2, dXtus3, dNtus2, dNtus3, ts1, ts2, ts3, zo11
        ZAPRASCH3 Dt1, Dt2, Dt3, pop.v.d1, pop.v.d2, pop.v.d3, Ygol.t1, Ygol.t2, Ygol.t3, pop.v.nap.1, pop.v.nap.2, pop.v.nap.3, Yr1, Yr2, Yr3, vrv, pover, Ygpad1, Ygpad2, Ygpad3, snvz1, snvz2, snvz3
        ELSE
END IF
COLOR 12, 0
PRINT TAB(25); " 2C1(GVOZDIKA) DANNUE PO ZELI "
COLOR 15, 0
PRINT "1B"; TAB(30); "2B"; TAB(60); "3B"
PRINT "Xc="; INT(Xc1 + .001); TAB(30); "Xc="; INT(Xc2 + .001); TAB(60); "Xc="; INT(Xc3 + .001)
PRINT "Yc="; INT(Yc1 + .001); TAB(30); "Yc="; INT(Yc2 + .001); TAB(60); "Yc="; INT(Yc3 + .001)
PRINT "hc="; INT(hc1 + .001); TAB(30); "hc="; INT(hc2 + .001); TAB(60); "hc="; INT(hc3 + .001)
105.112 PRINT "N OP="; opn1$; TAB(30); "N OP="; opn2$; TAB(60); "N OP="; opn3$
105.11 PRINT "OH="; OH1; TAB(30); "OH="; OH2; TAB(60); "OH="; OH3
 IF rep1 = 1 OR vsem = 1 THEN PRINT "*PRISTRELANNUE*"; TAB(30);
 IF rep1 = 0 AND vsem = 0 THEN PRINT "*POLNAIA PODG*"; TAB(30);
 IF rep2 = 1 OR vsem = 1 THEN PRINT "*PRISTRELANNUE*"; TAB(60);
 IF rep2 = 0 AND vsem = 0 THEN PRINT "*POLNAIA PODG*"; TAB(60);
 IF rep3 = 1 OR vsem = 1 THEN PRINT "*PRISTRELANNUE*"
 IF rep3 = 0 AND vsem = 0 THEN PRINT "*POLNAIA PODG*"
    IF zar1 = 0 THEN PRINT "ZARIAD=POLNIY"; TAB(30);
    IF zar1 = 5 THEN PRINT "ZARIAD=YMENSH"; TAB(30);
    IF zar1 = 1 THEN PRINT "ZARIAD=PERViY"; TAB(30);
    IF zar1 = 2 THEN PRINT "ZARIAD=VTOROY"; TAB(30);
    IF zar1 = 3 THEN PRINT "ZARIAD=TRETIY"; TAB(30);
    IF zar1 = 4 THEN PRINT "ZARIAD=CHETVERTIY"; TAB(30);
    IF zar2 = 0 THEN PRINT "ZARIAD=POLNIY"; TAB(60);
    IF zar2 = 5 THEN PRINT "ZARIAD=YMENSH"; TAB(60);
    IF zar2 = 1 THEN PRINT "ZARIAD=PERViY"; TAB(60);
    IF zar2 = 2 THEN PRINT "ZARIAD=VTOROY"; TAB(60);
    IF zar2 = 3 THEN PRINT "ZARIAD=TRETIY"; TAB(60);
    IF zar2 = 4 THEN PRINT "ZARIAD=CHETVERTIY"; TAB(60);
    IF zar3 = 0 THEN PRINT "ZARIAD=POLNIY"
    IF zar3 = 5 THEN PRINT "ZARIAD=YMENSH"
    IF zar3 = 1 THEN PRINT "ZARIAD=PERViY"
    IF zar3 = 2 THEN PRINT "ZARIAD=VTOROY"
    IF zar3 = 3 THEN PRINT "ZARIAD=TRETIY"
    IF zar3 = 4 THEN PRINT "ZARIAD=CHETVERTIY"
    IF snvz1 = 0 THEN PRINT "Sn/Vz=OF/RGM"; TAB(30);
    IF snvz1 = 1 THEN PRINT "Sn/Vz=OF/AR5"; TAB(30);
    IF snvz1 = 2 THEN PRINT "Sn/Vz=3SH1/DT"; TAB(30);
    IF snvz1 = 3 THEN PRINT "Sn/Vz=OF/B-90"; TAB(30);
    IF snvz1 = 4 THEN PRINT "Sn/Vz=C4/T-90"; TAB(30);
    IF snvz2 = 0 THEN PRINT "Sn/Vz=OF/RGM"; TAB(60);
    IF snvz2 = 1 THEN PRINT "Sn/Vz=OF/AR5"; TAB(60);
    IF snvz2 = 2 THEN PRINT "Sn/Vz=3SH1/DT"; TAB(60);
    IF snvz2 = 3 THEN PRINT "Sn/Vz=OF/B-90"; TAB(60);
    IF snvz2 = 4 THEN PRINT "Sn/Vz=C4/T-90"; TAB(60);
    IF snvz3 = 0 THEN PRINT "Sn/Vz=OF/RGM"
    IF snvz3 = 1 THEN PRINT "Sn/Vz=OF/AR5"
    IF snvz3 = 2 THEN PRINT "Sn/Vz=3SH1/DT"
    IF snvz3 = 3 THEN PRINT "Sn/Vz=OF/B-90"
    IF snvz3 = 4 THEN PRINT "Sn/Vz=C4/T-90"
    PRINT "PRICEL="; pr.eps1; TAB(30); "PRICEL="; pr.eps2; TAB(60); "PRICEL="; pr.eps3
  IF snvz1 >= 1 THEN
  PRINT "N="; INT(N1 + .001); TAB(30);
  ELSE
  PRINT "0"; TAB(30);
  END IF
  IF snvz2 >= 1 THEN
  PRINT "N="; INT(N2 + .001); TAB(60);
  ELSE
  PRINT "0"; TAB(60);
  END IF
  IF snvz3 >= 1 THEN
  PRINT "N="; INT(N3 + .001)
  ELSE
  PRINT "0"
  END IF
    PRINT "Dovorot OH="; dov.isch1; TAB(30); "Dovorot OH="; dov.isch2; TAB(60); "Dovorot OH="; dov.isch3
    IF zo11 = 0 THEN
    PRINT "Veer="; Veer1B; TAB(30); "Veer="; Veer2B; TAB(60); "Veer="; Veer3B
    PRINT "Sk\Shk="; sk.shk1; TAB(30); "Sk\Shk="; sk.shk2; TAB(60); "Sk\Shk="; sk.shk3
    ELSE
    END IF
    PRINT "dX/dNtus="; dXtus11; "/"; dNtus1; TAB(30); "dX/dNtus="; dXtus2; "/"; dNtus2; TAB(60); "dX/dNtus="; dXtus3; "/"; dNtus3
    PRINT "ts="; ts1; TAB(30); "ts="; ts2; TAB(60); "ts="; ts3
110 PRINT "Dt/dD="; Dt1; "/"; INT(pop.v.d1 + .001); TAB(30); "Dt/dD="; Dt2; "/"; INT(pop.v.d2 + .001); TAB(60); "Dt/dD="; Dt3; "/"; INT(pop.v.d3)
111 PRINT "Yg.t/dDov="; Ygol.t1; "/"; INT(pop.v.nap.1 + .001); TAB(30); "Yg.t/dDov="; Ygol.t2; "/"; INT(pop.v.nap.2); TAB(60); "Yg.t/dDov="; Ygol.t3; "/"; INT(pop.v.nap.3)
112 PRINT "Yroven="; Yr1; TAB(30); "Yroven="; Yr2; TAB(60); "Yroven="; Yr3
IF snvz1 = 3 AND vrv = 15 THEN
PRINT "BNIMANIE VRV > 15!!!"; TAB(30);
ELSEIF snvz1 = 1 AND pover = 0 AND Ygpad1 >= 40 THEN
PRINT "Yst.Vzr=VUSOKI!!!"; TAB(30);
ELSEIF snvz1 = 1 AND pover = 0 AND Ygpad1 < 40 THEN
PRINT "Yst.Vz=NIZKI!!!"; TAB(30);
ELSEIF snvz1 = 1 AND pover = 1 THEN
PRINT "Yst.Vzr=VUSOKI!!!"; TAB(30);
ELSE
PRINT "0"; TAB(30);
END IF
IF snvz2 = 3 AND vrv = 15 THEN
PRINT "BNIMANIE VRV > 15!!!"; TAB(60);
ELSEIF snvz2 = 1 AND pover = 0 AND Ygpad2 >= 40 THEN
PRINT "Yst.Vzr=VUSOKI!!!"; TAB(60);
ELSEIF snvz2 = 1 AND pover = 0 AND Ygpad2 < 40 THEN
PRINT "Yst.Vz=NIZKI!!!"; TAB(60);
ELSEIF snvz2 = 1 AND pover = 1 THEN
PRINT "Yst.Vzr=VUSOKI!!!"; TAB(60);
ELSE
PRINT "0"; TAB(60);
END IF
IF snvz3 = 3 AND vrv = 15 THEN
PRINT "BNIMANIE VRV > 15!!!"
ELSEIF snvz3 = 1 AND pover = 0 AND Ygpad3 >= 40 THEN
PRINT "Yst.Vzr=VUSOKI!!!"
ELSEIF snvz3 = 1 AND pover = 0 AND Ygpad3 < 40 THEN
PRINT "Yst.Vz=NIZKI!!!"
ELSEIF snvz3 = 1 AND pover = 1 THEN
PRINT "Yst.Vzr=VUSOKI!!!"
ELSE
PRINT "0"
END IF
113 IF shkval2 = 1 THEN
        PRINT "1B"; TAB(30); "2B"; TAB(60); "3B"
        PRINT "PRICEL="; pr.eps1; TAB(30); "PRICEL="; pr.eps2; TAB(60); "PRICEL="; pr.eps3
        PRINT "KORR.DOV="; ABS(INT(dov.isch21 - dov.isch1)); TAB(30); "KORR.DOV="; ABS(INT(dov.isch22 - dov.isch2)); TAB(60); "KORR.DOV="; ABS(INT(dov.isch23 - dov.isch3))
        PRINT "Vremia na zariadky ="; INT(ts21 - ts1); TAB(30); INT(ts22 - ts2); TAB(60); INT(ts23 - ts3)
        shkval = 0: shkval2 = 0
        GOTO 0.42
        ELSE
END IF
IF shkval = 1 THEN
        stre = 0: pr.eps21 = pr.eps1: pr.eps22 = pr.eps2: pr.eps23 = pr.eps3
        dov.isch21 = dov.isch1: dov.isch22 = dov.isch2: dov.isch23 = dov.isch3
        ts21 = ts1: ts22 = ts2: ts23 = ts3
        shkval2 = 1
        SLEEP
        GOTO 17
        ELSE
END IF
  RETURN
'''''''''''''''''''DANNUE PO ZO podprogr'''''''''''''''''''''''''''''''
240.11 IF Yg.s1 > 750 THEN PRINT "ZO-FLANG"; TAB(30);
       IF Yg.s1 <= 750 THEN PRINT "ZO-FRONTAL"; TAB(30);
       IF Yg.s2 > 750 THEN PRINT "ZO-FLANG"; TAB(60);
       IF Yg.s2 <= 750 THEN PRINT "ZO-FRONTAL"; TAB(60);
       IF Yg.s3 > 750 THEN PRINT "ZO-FLANG"
       IF Yg.s3 <= 750 THEN PRINT "ZO_FRONTAL"
       IF Yg.s1 > 750 THEN PRINT "shk="; sk1; TAB(30);
       IF Yg.s1 <= 750 THEN PRINT "Veer.bat="; int.ve1; TAB(30);
       IF Yg.s2 > 750 THEN PRINT "shk="; sk2; TAB(60);
       IF Yg.s2 <= 750 THEN PRINT "Veer.bat="; int.ve2; TAB(60);
       IF Yg.s3 > 750 THEN PRINT "shk="; sk3
       IF Yg.s3 <= 750 THEN PRINT "Veer.bat="; int.ve3

  RETURN
'''''''''''''''''''''''''''''''AR-5 podprog''''''''''''''''''''''''''''''''''
300
PRICAR5 zar, Disch, Pric.isch, N
 RETURN

'''''''''''''''''''''''''''3SH1 podprog'''''''''''''''''''''''''''''''''''''''''
400 IF Disch > 15200 THEN Disch = 15200
IF zar = 0 THEN
  OPEN "I", #1, "3sh-P"
  ELSE
   OPEN "I", #1, "3sh-Y"
END IF
401 IF EOF(1) THEN GOTO 403
  INPUT #1, ta1, ta2, ta3, ta4, ta5, ta6, ta7, ta8
  IF ta1 <= Disch AND ta1 + 200 >= Disch THEN GOTO 402
      GOTO 401
402 Pric = ta2: Dta = ta1: N = ta3: dNtus = ta4: dNw = ta5: dNh = ta6: dNt = ta7: dNv0 = ta8
403 CLOSE #1
  Dischh = Disch + 200
  IF Dischh > 15000 THEN Dischh = 15200
  IF zar = 0 THEN
  OPEN "I", #1, "3sh-P"
  ELSE
   OPEN "I", #1, "3sh-Y"
END IF
404 IF EOF(1) THEN GOTO 406
   INPUT #1, ta1, ta2, ta3, ta4, ta5, ta6, ta7, ta8
   IF ta1 <= Dischh AND ta1 + 200 >= Dischh THEN GOTO 405
   GOTO 404
405 Pricc = ta2: Nn = ta3: dNww = ta5: dNhh = ta6: dNtt = ta7: dNv00 = ta8
406  CLOSE #1
    Pric.isch = (Pricc - Pric) / 200 * (Disch - Dta) + Pric
    dNw = (dNww - dNw) / 200 * (Disch - Dta) + dNw
    dNh = (dNhh - dNh) / 200 * (Disch - Dta) + dNh
    dNt = (dNtt - dNt) / 200 * (Disch - Dta) + dNt
    dNv0 = (dNv00 - dNvo) / 200 * (Disch - Dta) + dNv0
    IF rep = 1 OR vsem = 1 THEN
        dN = dN
        ELSE
        dN = ((dNw / 10) * Wx) + ((dNh / 10 * -1) * dhh) + ((dNt / 10) * dddt) + (dNv0 * dV00)
    END IF
    N = (Nn - N) / 200 * (Disch - Dta) + N + dN - 3
  
 RETURN

'''''''''''''''''''''''''''B-90 podprog''''''''''''''''''''''''''''''''''''''''''''
500
    IF zar = 0 THEN
    OPEN "B-90p" FOR INPUT AS #1
    ELSEIF zar = 5 THEN
    OPEN "B-90Y" FOR INPUT AS #1
    ELSEIF zar = 1 THEN
    OPEN "B-901" FOR INPUT AS #1
    ELSEIF zar = 2 THEN
    OPEN "B-902" FOR INPUT AS #1
    ELSE
    OPEN "B-903" FOR INPUT AS #1
    END IF
501 IF EOF(1) THEN GOTO 503
  INPUT #1, ta1, ta2, ta3, ta4, ta5, ta6, ta7, ta8
  IF Disch > 14800 THEN Disch = 14800
  IF ta1 <= Disch AND ta1 + 200 >= Disch THEN GOTO 502
      GOTO 501
502 Pric = ta2: Dta = ta1: N = ta3: dNtus = ta4: dNw = ta5: dNh = ta6: dNt = ta7: dNv0 = ta8
503 CLOSE #1
  Dischh = Disch + 200
  IF Dischh > 14800 THEN Dischh = 14800
    IF zar = 0 THEN
    OPEN "B-90p" FOR INPUT AS #1
    ELSEIF zar = 5 THEN
    OPEN "B-90Y" FOR INPUT AS #1
    ELSEIF zar = 1 THEN
    OPEN "I", #1, "B-901"
    ELSEIF zar = 2 THEN
    OPEN "B-902" FOR INPUT AS #1
    ELSE
    OPEN "B-903" FOR INPUT AS #1
    END IF
504 IF EOF(1) THEN GOTO 506
   INPUT #1, ta1, ta2, ta3, ta4, ta5, ta6, ta7, ta8
   IF ta1 <= Dischh AND ta1 + 200 >= Dischh THEN GOTO 505
   GOTO 504
505 Pricc = ta2: Nn = ta3: dNww = ta5: dNhh = ta6: dNtt = ta7: dNv00 = ta8
506  CLOSE #1
    Pric.isch = (Pricc - Pric) / 200 * (Disch - Dta) + Pric + 2
    dNw = (dNww - dNw) / 200 * (Disch - Dta) + dNw
    dNh = (dNhh - dNh) / 200 * (Disch - Dta) + dNh
    dNt = (dNtt - dNt) / 200 * (Disch - Dta) + dNt
    dNv0 = (dNv00 - dNv0) / 200 * (Disch - Dta) + dNv0
    IF rep = 1 OR vsem = 1 THEN
        dN = dN
        ELSE
        dN = ((dNw / 10) * Wx) + ((dNh / 10 * -1) * dhh) + ((dNt / 10) * dddt) + (dNv0 * dV00)
    END IF
    N = (Nn - N) / 200 * (Disch - Dta) + N + dN
510 IF zar = 0 AND Disch >= 5200 THEN
  vrv = 15
 ELSEIF zar = 5 AND Disch >= 4400 THEN
         vrv = 15
                ELSEIF zar = 1 AND Disch >= 3800 THEN
                vrv = 15
                        ELSEIF zar = 2 AND Disch >= 3400 THEN
                       
                        vrv = 15
                                ELSEIF zar = 3 AND Disch >= 3000 THEN
                                vrv = 15
         ELSE
          vrv = 0

 END IF
 RETURN
''''''''''''''''''''''''''''''T-90 podprogr''''''''''''''''''''''''''''''''''
600 T90 Disch, zar, dNtus, Pric.isch, N
 RETURN

''''''''''''''''''''''''MORTIRNAIA''''''''''''''''''''''''''''''''''''''''''''''
390
   IF zar = 0 THEN
   OPEN "I", #1, "2C1MORTP"
   ELSEIF zar = 5 THEN
   OPEN "I", #1, "2C1MORTY"
   ELSEIF zar = 1 THEN
   OPEN "I", #1, "2C1MORT1"
   ELSEIF zar = 2 THEN
   OPEN "I", #1, "2C1MORT2"
   ELSEIF zar = 3 THEN
   OPEN "I", #1, "2C1MORT3"
   ELSEIF zar = 4 THEN
   OPEN "I", #1, "2C1MORT4"
   ELSE
   OPEN "I", #1, "2C1MORTP"
   END IF
391 IF EOF(1) THEN GOTO 392.2
391.1 INPUT #1, ta1, ta2, ta3, ta4, ta5, ta6, ta7, ta8, ta9, ta10

392 IF ta1 <= Dt THEN GOTO 392.1
 GOTO 391
392.1 Dta = ta1: Prta = ta2: dXtus = ta3: z = ta4: dzw = ta5: dxw = ta6
 dxh = ta7: dxt = ta8: dxv0 = ta9: ybyl = 40: ts = ta10

392.2 CLOSE #1
   Dtt = Dt + 200
   IF zar = 0 THEN
   OPEN "I", #1, "2C1MORTP"
   ELSEIF zar = 5 THEN
   OPEN "I", #1, "2C1MORTY"
   ELSEIF zar = 1 THEN
   OPEN "I", #1, "2C1MORT1"
   ELSEIF zar = 2 THEN
   OPEN "I", #1, "2C1MORT2"
   ELSEIF zar = 3 THEN
   OPEN "I", #1, "2C1MORT3"
   ELSEIF zar = 4 THEN
   OPEN "I", #1, "2C1MORT4"
   ELSE
   OPEN "I", #1, "2C1MORTP"
   END IF
3911 IF EOF(1) THEN GOTO 392.21
391.11 INPUT #1, ta1, ta2, ta3, ta4, ta5, ta6, ta7, ta8, ta9, ta10

3921 IF ta1 <= Dtt THEN GOTO 392.11
 GOTO 3911
392.11 dta1 = ta1: prta1 = ta2: dxtus1 = ta3: z1 = ta4: dzw1 = ta5: dxw1 = ta6
 dxh1 = ta7: dxt1 = ta8: dxv01 = ta9

392.21 CLOSE #1

zc = ((z1 - z) / 200 * (Dt - Dta) + z) * -1
dzwc = ((dzw1 - dzw) / 200 * (Dt - Dta) + dzw) * -1 / 10
dXwc = ((dxw1 - dxw) / 200 * (Dt - Dta) + dxw) * -1 / 10
dXhc = ((dxw1 - dxw) / 200 * (Dt - Dta) + dxh) / 10
dXtc = ((dxt1 - dxt) / 200 * (Dt - Dta) + dxt) * -1 / 10
dXv0c = ((dxv01 - dxv0) / 200 * (Dt - Dta) + dxv0) * -1
IF met = 0 THEN
 Aw200 = Aw + 100: Aw400 = Aw + 200: Aw800 = Aw + 300: Aw1200 = Aw + 300: Aw1600 = Aw + 400
 Aw2000 = Aw + 400: Aw2400 = Aw + 400: Aw3000 = Aw + 500: Aw4000 = Aw + 500
ELSE
END IF
  ybylc = 4000
 IF ybylc = 4000 THEN aww = Aw4000
IF Ygol.t - aww < 0 THEN
       aws = Ygol.t + 6000 - aww
   ELSE
   aws = Ygol.t - aww
   END IF
  ybylc = 4000
 IF ybylc = 4000 THEN sw = w4000

 Wx = ABS(sw * COS((aws / 100 * 6) * 3.141596 / 180))
 wz = ABS(sw * SIN((aws / 100 * 6) * 3.14159 / 180))

 IF aws <= 1500 OR aws >= 4500 THEN Wx = Wx * -1
 IF aws >= 3000 THEN wz = wz * -1

  ybylc = 4000
 IF ybylc = 4000 THEN dddt = t4000
 IF dddt >= 50 THEN dddt = (dddt - 50) * -1

  RETURN
'''''''''''''''''''''PRICEL MORTIRNAIA''''''''''''''''''''''''''''''''''''''''
392.01
 PRICMORT zar, Disch, ts, Pric.isch
392.323 RETURN
        
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''''''''''''''''''''''''''''''KPE'''''''''''''''''''''''''''''''''''''''''
392.331
KKPEE zar, Pric.isch, kpew, kpen, Yrr, kpe
  RETURN
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
''''''''''''''''''''''''PO REPERY podprogramma''''''''''''''''''''''''''''''''''''''''
2000
POREPERY vsem, dDr1, dDr, dDov1, dDovre, Dret1, Dret, dDr2, dDov2, Dret2, dDr3, dDov3, Dret3, Nop, dN, dN1, dN2, dN3
RETURN
''''''''''''''''''''''''''''''''TABLIZA ISCH YST'''''''''''''''''''''''''''''''''''
3200
TABISCHYST zar1, zar2, zar3, pr.eps1, pr.eps2, pr.eps3, dov.isch1, dov.isch2, dov.isch3, sk.shk1, sk.shk2, sk.shk3, opn1$, opn2$, opn3$, OH1, OH2, OH3, Xop1, Xop2, Xop3, Yop1, Yop2, Yop3, hop1, hop2, hop3
GOTO 0.42
'''''''''''''''''''''''''''TOPO'''''''''''''''''''''''''''''''''''''''''''
6000 ZAPISOP
GOTO 0.42
6010 ZAPISNP
GOTO 0.42
'''''''''''''''''''''''POSMOTRET V0''''''''''''''''''''''''''''''''''''''''''''
7000
POSMOTRETV0 (v0pol1), (v0ymen1), (v0perv1), (v0vtor1), (v0tret1), (v0chetv1), (v0pol2), (v0ymen2), (v0perv2), (v0vtor2), (v0tret2), (v0chetv2), (v0pol3), (v0ymen3), (v0perv3), (v0vtor3), (v0tret3), (v0chetv3)
GOTO 0.42

SUB BALISTIKA (tz1 AS SINGLE, v0pol1 AS SINGLE, v0ymen1 AS SINGLE, v0perv1 AS SINGLE, v0vtor1 AS SINGLE, v0tret1 AS SINGLE, v0chetv1 AS SINGLE, tz2 AS SINGLE, v0pol2 AS SINGLE, v0ymen2 AS SINGLE, v0perv2 AS SINGLE, v0vtor2 AS SINGLE, v0tret2 AS SINGLE, v0chetv2 AS SINGLE, tz3 AS SINGLE, v0pol3 AS SINGLE, v0ymen3 AS SINGLE, v0perv3 AS SINGLE, v0vtor3 AS SINGLE, v0tret3 AS SINGLE, v0chetv3 AS SINGLE)
PRINT "<<BALISTIKA>>"
PRINT " TEMPERATYRY ZARIADA "
INPUT " 1B Tz = "; tz1
INPUT " 2B Tz = "; tz2
INPUT " 3B Tz = "; tz3
PRINT "<<POTERIA NACH SKOR. Vo>>"
INPUT " Vo - Vvodit 1 - Da 0 - Net "; vvod
IF vvod = 1 THEN
        INPUT " 1B Vvodit - 1, Net - 0 "; vvod
        IF vvod = 1 THEN
                PRINT "<<Vo 1B>>"
                INPUT " Vo s faila - 0, Svoi dannue - 1 "; vnyl
                        IF vnyl = 0 THEN
                                OPEN "vnyl1.bet" FOR INPUT AS #1
                                INPUT #1, v1, v2, v3, v4, v5, v6
                                CLOSE #1
                                v0pol1 = v1: v0ymen1 = v2: v0perv1 = v3: v0vtor1 = v4: v0tret1 = v5: v0chetv1 = v6
                                ELSE
                                INPUT " Vo-Poln "; v0pol1
                                INPUT " Vo-Ymen "; v0ymen1
                                INPUT " Vo-Perv "; v0perv1
                                INPUT " Vo-Vtor "; v0vtor1
                                INPUT " Vo-Tret "; v0tret1
                                INPUT " Vo-Chetvert "; v0chetv1
                        END IF
        ELSE
        END IF
        INPUT " 2B Vvodit - 1, Net - 0 "; vvod
        IF vvod = 1 THEN
                PRINT "<<Vo 2B>>"
                INPUT " Vo s faila - 0, Svoi dannue - 1 "; vnyl
                IF vnyl = 0 THEN
                        OPEN "vnyl2.bet" FOR INPUT AS #1
                        INPUT #1, v1, v2, v3, v4, v5, v6
                        CLOSE #1
                        v0pol2 = v1: v0ymen2 = v2: v0perv2 = v3: v0vtor2 = v4: v0tret2 = v5: v0chetv2 = v6
                        ELSE
                        INPUT " Vo-Poln "; v0pol2
                        INPUT " Vo-Ymen "; v0ymen2
                        INPUT " Vo-Perv "; v0perv2
                        INPUT " Vo-Vtor "; v0vtor2
                        INPUT " Vo-Tret "; v0tret2
                        INPUT " Vo-Chetvert "; v0chetv2
                END IF
        ELSE
        END IF
        INPUT " 3B Vvodit - 1, Net - 0 "; vvod
        IF vvod = 1 THEN
                PRINT "<<Vo 3B>>"
                INPUT " Vo s faila - 0, Svoi dannue - 1 "; vnyl
                IF vnyl = 0 THEN
                        OPEN "vnyl3.bet" FOR INPUT AS #1
                        INPUT #1, v1, v2, v3, v4, v5, v6
                        CLOSE #1
                        v0pol3 = v1: v0ymen3 = v2: v0perv3 = v3: v0vtor3 = v4: v0tret3 = v5: v0chetv3 = v6
                        ELSE
                        INPUT " Vo-Poln "; v0pol3
                        INPUT " Vo-Ymen "; v0ymen3
                        INPUT " Vo-Perv "; v0perv3
                        INPUT " Vo-Vtor "; v0vtor3
                        INPUT " Vo-Tret "; v0tret3
                        INPUT " Vo-Chetvert "; v0chetv3
                END IF
                ELSE
        END IF
ELSE
END IF
END SUB

SUB BBODOH (OH1 AS SINGLE, OH2 AS SINGLE, OH3 AS SINGLE)
PRINT "<<BBOD OH>>"
INPUT " 1B OH = "; OH1
INPUT " 2B OH = "; OH2
INPUT " 3B OH = "; OH3

END SUB

  SUB DOBAVITBP (Xkp1 AS SINGLE, Ykp1 AS SINGLE, hkp1 AS SINGLE, Xkp2 AS SINGLE, Ykp2 AS SINGLE, hkp2 AS SINGLE, Xkp3 AS SINGLE, Ykp3 AS SINGLE, hkp3 AS SINGLE, Xkp4 AS SINGLE, Ykp4 AS SINGLE, hkp4 AS SINGLE, Xop1 AS SINGLE, Yop1 AS SINGLE, hop1 AS SINGLE, Xop2 AS SINGLE, Yop2 AS SINGLE, hop2 AS SINGLE, Xop3 AS SINGLE, Yop3 AS SINGLE, hop3 AS SINGLE, opn1 AS SINGLE, opn2 AS SINGLE, opn3 AS SINGLE)
INPUT " Dobavit BP 0-Net, 1-Da "; dob
IF dob = 1 THEN
        INPUT " OP-0, KP-1 "; opkp
                IF opkp = 1 THEN
                        INPUT " Plan. - 0, Ne plan. - 1 "; vvod
                        INPUT " kakoi KP dobavit 0-Perv, 2-Vtor, 3-Tret, 4-Chetv "; kakp
                        IF vvod = 0 THEN
                                OPEN "knptabl" FOR INPUT AS #1
                                INPUT " N KNP = "; nkp$
6050                            IF EOF(1) THEN GOTO 6055
                                INPUT #1, t1$, t2, t3, t4
                                IF t1$ = nkp$ THEN GOTO 6052
                                GOTO 6050
6052                            Xkp = t2: Ykp = t3: hkp = t4
6055                            CLOSE #1
                                IF kakp = 0 THEN
                                        Xkp1 = Xkp: Ykp1 = Ykp: hkp1 = hkp
                                        ELSEIF kakp = 2 THEN
                                        Xkp2 = Xkp: Ykp2 = Ykp: hkp2 = hkp
                                        ELSEIF kakp = 3 THEN
                                        Xkp3 = Xkp: Ykp3 = Ykp: hkp3 = hkp
                                        ELSE
                                        Xkp4 = Xkp: Ykp4 = Ykp: hkp4 = hkp
                                END IF
                        ELSE

                                IF kakp = 0 THEN
                                        INPUT " KP1 X, Y, h "; Xkp1, Ykp1, hkp1
                                        ELSEIF kakp = 2 THEN
                                        INPUT " KP2 X, Y, h "; Xkp2, Ykp2, hkp2
                                        ELSEIF kakp = 3 THEN
                                        INPUT " KP3 X, Y, h "; Xkp3, Ykp3, hkp3
                                        ELSEIF kakp = 4 THEN
                                        INPUT " KP4 X, Y, h "; Xkp4, Ykp4, hkp4
                                        ELSE
                                END IF
                        END IF
                ELSE
                INPUT " Planovaia - 0, Ne planov. - 1 "; vvod
                        IF vvod = 1 THEN
                        INPUT " kakyu OP vvodit 0-Perv, 2-Vtor, 3-Tret "; kaop
                                IF kaop = 0 THEN
                                INPUT " OP1 X, Y, h "; Xop1, Yop1, hop1
                                ELSEIF kaop = 2 THEN
                                INPUT " OP2 X, Y, h "; Xop2, Yop2, hop2
                                ELSE
                                INPUT " OP3 X, Y, h "; Xop3, Yop3, hop3
                                END IF
                        ELSE
                        INPUT "kakyu OP vvodit 0-Perv, 2-Vtor, 3-Tret "; kaop
                        INPUT " N OP = "; Nop$
                        OPEN "optabl" FOR INPUT AS #1
5035                    IF EOF(1) THEN GOTO 5050
                        INPUT #1, t1$, t2, t3, t4
                        IF t1$ = Nop$ THEN GOTO 5045
                        GOTO 5035
5045                    Xop = t2: Yop = t3: hop = t4
5050                    CLOSE #1
                        IF kaop = 0 THEN
                        Xop1 = Xop: Yop1 = Yop: hop1 = hop
                        ELSEIF kaop = 2 THEN
                        Xop2 = Xop: Yop2 = Yop: hop2 = hop
                        ELSEIF kaop = 3 THEN
                        Xop3 = Xop: Yop3 = Yop: hop3 = hop
                        ELSE
                        Xop1 = Xop: Yop1 = Yop: hop1 = hop
                        END IF
               END IF
        
END IF
END IF
END SUB

SUB dV0111 (tz AS SINGLE, zar AS SINGLE, dV0 AS SINGLE)
OPEN "I", #1, "tz2c"
324 IF EOF(1) THEN GOTO 327
325 INPUT #1, t1, t2, t3, t4, t5
326 IF t1 <= tz THEN GOTO 326.1
 GOTO 324
326.1 IF zar = 0 THEN
        dV0 = t2
      ELSEIF zar = 5 OR zar = 1 THEN
      dV0 = t3
      ELSEIF zar = 2 OR zar = 3 THEN
      dV0 = t4
      ELSEIF zar = 4 THEN
      dV0 = t5
      ELSE
      dV0 = t2
      END IF
      tz0 = t1
327 CLOSE #1

IF tz < 0 THEN tz11 = tz - 5
IF tz >= 0 THEN tz11 = tz + 5
    OPEN "I", #1, "tz2c"
424 IF EOF(1) THEN GOTO 427
425 INPUT #1, t1, t2, t3, t4, t5
426 IF t1 <= tz11 THEN GOTO 426.1
 GOTO 424
426.1 IF zar = 0 THEN
        dV01 = t2
      ELSEIF zar = 5 OR zar = 1 THEN
      dV01 = t3
      ELSEIF zar = 2 OR zar = 3 THEN
      dV01 = t4
      ELSEIF zar = 4 THEN
      dV01 = t5
      ELSE
      dV01 = t2
      END IF
427 CLOSE #1
 IF tz >= 0 THEN dV0 = (dV01 - dV0) / 5 * (tz - tz0) + dV0
 IF tz < 0 THEN dV0 = ((dV01 - dV0) / 5 * (tz - tz0) - dV0) * -1

END SUB

SUB KKPEE (zar AS SINGLE, Pric.isch AS SINGLE, kpew AS SINGLE, kpen AS SINGLE, Yrr AS SINGLE, kpe AS SINGLE)
IF zar = 0 THEN
        OPEN "I", #1, "2c1kpemp"
        ELSEIF zar = 5 THEN
        OPEN "I", #1, "2c1kpemy"
        ELSEIF zar = 1 THEN
        OPEN "I", #1, "2c1kpem1"
        ELSEIF zar = 2 THEN
        OPEN "I", #1, "2c1kpem2"
        ELSEIF zar = 3 THEN
        OPEN "I", #1, "2c1kpem3"
        ELSEIF zar = 4 THEN
        OPEN "I", #1, "2c1kpem4"
        ELSE
        OPEN "I", #1, "2c1kpemp"
END IF
392.332 IF EOF(1) THEN GOTO 392.333
  INPUT #1, e1, e2, e3
   IF Pric.isch >= e1 AND e1 + 20 >= Pric.isch THEN kpew = e2: kpen = e3: GOTO 392.333
   GOTO 392.332
392.333 CLOSE #1
    IF Yrr >= 0 THEN kpe = kpew * .1
    IF Yrr < 0 THEN kpe = kpen * .1

END SUB

SUB KPEnast (zar AS SINGLE, Pric AS SINGLE, kpew AS SINGLE, kpen AS SINGLE, Yrr AS SINGLE, kpe AS SINGLE)
223  IF zar = 0 THEN
        OPEN "I", #1, "2c1kpep"
        ELSEIF zar = 5 THEN
        OPEN "I", #1, "2c1kpey"
        ELSEIF zar = 1 THEN
        OPEN "I", #1, "2c1kpe1"
        ELSEIF zar = 2 THEN
        OPEN "I", #1, "2c1kpe2"
        ELSEIF zar = 3 THEN
        OPEN "I", #1, "2c1kpe3"
        ELSEIF zar = 4 THEN
        OPEN "I", #1, "2c1kpe4"
        ELSE
        OPEN "I", #1, "2c1kpep"
        END IF
223.1 IF EOF(1) THEN GOTO 223.2
  INPUT #1, e1, e2, e3, e4, e5
   IF Pric >= e1 AND e1 + 20 >= Pric THEN kpew = e2: kpen = e3: GOTO 223.2
   GOTO 223.1
223.2 CLOSE #1
    IF Yrr >= 0 THEN kpe = kpew * .1
    IF Yrr < 0 THEN kpe = kpen * .1

END SUB

SUB OBIEKTATAKI
PRINT " OBEKT ATAKI "
INPUT " Zel 1-Grypovaia, 2-Otdelnaia "; kakz
INPUT " Front, Glybina "; Fr, Gl
INPUT " K-vo oryd "; kor
INPUT " K-vo yst. na oryd. "; korys
Razmz = (Fr * Gl) / 10000
Max = kor * .5
IF Razmz > Max THEN PRINT "NE XVATAET OGNEVUX VOZMOGNOSTEI"
IF Razmz > Max THEN GOTO 290.10
INPUT " Kto atakyet 1-Tanki, 2-Pex.na.BMP, 3-Pexota"; kto
INPUT " Rybeg bezop. ydalen"; Rbezy
INPUT " Rybeg perexoda v ataky"; Rper
INPUT " Skor. vudvig km/ch"; svud
INPUT " Skor. ataki km/ch"; sat
INPUT " Nach. ataki "; nat
IF kakz = 1 THEN Rsm = 4
IF kakz = 2 THEN Rsm = 8
IF kto = 1 THEN Rby = 200
IF kto = 2 THEN Rby = 300
IF kto = 3 THEN Rby = 400
Vrogn = (Rbezy - Rper) / ((svud + .001) * 1000 / 60) + (Rper - Rby) / ((sat + .001) * 1000 / 60)
IF Vrogn < 5 THEN Vrogn = 5
Razmz = (Fr * Gl) / 10000
Ranz = Vrogn * Rsm * Razmz
temp = (Vrogn - 1) * 60 / ((Ranz + .001) - (kor * 2))
Vrogdoat = (Rbezy - Rper) / ((svud + .001) * 1000 / 60)
Nachna = nat - Vrogdoat
Rnorys = Ranz / ((korys + .001) * (kor + .001))
PRINT "............................................................................"
PRINT "Rasx.na.zel="; CINT(Ranz + .001); "K-vo.oryd.yst="; CINT(korys * kor + .001)
PRINT "KOMANDA: Ognevoi nalet"; CINT(Vrogn + .001); "min Po"; CINT(Rnorys + .001); "sn 2sn beglum ostalnue"; CINT(temp + .001); "sek vustrel!!!"
PRINT "NACHALO Ognevogo naleta="; CINT(Nachna)
PRINT ".........................................................................."
290.10
END SUB

SUB OCHISTKA (chza AS SINGLE)
IF chza = 0 THEN OPEN "Zeli" FOR OUTPUT AS #1
IF chza = 1 THEN OPEN "NZO" FOR OUTPUT AS #1
IF chza = 2 THEN OPEN "Toch.Vst" FOR OUTPUT AS #1
IF chza = 3 THEN OPEN "PZO" FOR OUTPUT AS #1
CLOSE #1

END SUB

SUB OGNZADmeny
PRINT "BBOD 14 ZO"
PRINT "BBOD 15 KOLONNA"
PRINT "BBOD 16 RAZMER ZELI"
PRINT "BBOD 20 KOG.PRIV"
END SUB

SUB PECHSNAR (nb AS SINGLE, snvz1 AS SINGLE, snvz2 AS SINGLE, snvz3 AS SINGLE, snvz$)
IF nb = 1 THEN
        snvz = snvz1
        ELSEIF nb = 2 THEN
        snvz = snvz2
        ELSEIF nb = 3 THEN
        snvz = snvz3
        ELSE
END IF
IF snvz = 0 THEN
        snvz$ = " OF/RGM"
        ELSEIF snvz = 1 THEN
        snvz$ = " OF/AR5 "
        ELSEIF snvz = 2 THEN
        snvz$ = " 3SH1/DTM-75 "
        ELSEIF snvz = 3 THEN
        snvz$ = " OF/V-90 "
        ELSEIF snvz = 4 THEN
        snvz$ = " C4T-90 "
        ELSE
END IF
END SUB

SUB PODGOTOVKAmeny
PRINT "BBOD 1 ZAN.OP"
PRINT "BBOD 2 ZAN.NP"
PRINT "BBOD 4 METEO"
PRINT "BBOD 44 MET.GRYP"
PRINT "BBOD 6 BALISTIKA"
PRINT "BBOD 7 VUBOR ZAR"
PRINT "BBOD 5 SMEN.OH"
PRINT "BBOD 19 VUBOR SN/VZ"
PRINT "BBOD 24 STR.MORT/NAST"
PRINT "BBOD 32 ZAPISAT Vo"
PRINT "BBOD 33 DOBAVIT BP"
PRINT "BBOD 34 POKAZAT BP"
PRINT "BBOD 35 RASCHET POPRAVOK"
PRINT "BBOD 37 POSMOTR.OP,NP"
PRINT "BBOD 41 POSMOTRET dVo"
END SUB

SUB POKAZBP (Xkp1 AS SINGLE, Ykp1 AS SINGLE, hkp1 AS SINGLE, Xkp2 AS SINGLE, Ykp2 AS SINGLE, hkp2 AS SINGLE, Xkp3 AS SINGLE, Ykp3 AS SINGLE, hkp3 AS SINGLE, Xkp4 AS SINGLE, Ykp4 AS SINGLE, hkp4 AS SINGLE, Xop1 AS SINGLE, Yop1 AS SINGLE, hop1 AS SINGLE, Xop2 AS SINGLE, Yop2 AS SINGLE, hop2 AS SINGLE, Xop3 AS SINGLE, Yop3 AS SINGLE, hop3 AS SINGLE, OH1 AS SINGLE, OH2 AS SINGLE, OH3 AS SINGLE)
PRINT TAB(25); "BOEVOI PORIADOK"
PRINT "1BAT X="; Xop1; " Y="; Yop1; " h="; hop1; " OH="; OH1
PRINT "2BAT X="; Xop2; " Y="; Yop2; " h="; hop2; " OH="; OH2
PRINT "3BAT X="; Xop3; " Y="; Yop3; " h="; hop3; " OH="; OH3
PRINT "KNP1 X="; Xkp1; " Y="; Ykp1; " h="; hkp1
PRINT "KNP2 X="; Xkp2; " Y="; Ykp2; " h="; hkp2
PRINT "KNP3 X="; Xkp3; " Y="; Ykp3; " h="; hkp3
PRINT "KNP4 X="; Xkp4; " Y="; Ykp4; " h="; hkp4

END SUB

SUB PORAGNENABZELI
PRINT "1-Batar.byksir.YKRUT"
PRINT "2-RLS,Bat.ZYR.OTKRUT"
PRINT "3-Giv.sil.og.sred.KP.YKRUT.Tanki,BMP,BTR.v.PC"
PRINT "4-Giv.sila.OTKRUT"
PRINT "5-KP.na.avto.OTKRUT"
PRINT "6-Otdel.nebron.zel.OTKRUT"
PRINT "7-KOLONNA"
PRINT "8-Bat.sam.BRON.oryd"
PRINT "9-Bat.sam.NEBRON.oryd"
PRINT "10-Pysk.yst.Bat.i.ot.pysk.yst.Yst.ZYR.Vert.na.pos.plosch.OTKRUT"
INPUT har
INPUT "Zad.strelbu 1-Podavit,2-Ynichtog"; zad
INPUT "Razmer zeli Front,Glybina,Dt"; Fr, Gl, Dto
280.1 INPUT "Stepen zascitu 1-Otkr,Nebron,2-Ykrut,Bron"; stz
INPUT "K-vo oryd."; kor
INPUT " K-vo Batar. "; bat
INPUT "PODGOTOVKA 1-Polnaia,2-Sokrasch,3-Perenos,Posl.pristr,4-V xode.str.na.porag"; pod
IF pod = 4 THEN INPUT "Ko.or.yst="; korysf
INPUT "Dolia rashod 1-Norma,2-1/2nor,3-1/3nor,4-1/4nor,5-1/5nor,6-1/6nor"; dol
 IF har = 1 THEN RnZ = 240
 IF har = 2 THEN RnZ = 200
 IF har = 6 THEN RnZ = 300
 IF har = 3 THEN RnGa = 180
 IF har = 4 THEN RnGa = 40
 IF har = 5 THEN RnGa = 50
 IF har = 7 THEN RnOr = 8
 IF har = 8 THEN RnOr = 16
 IF har = 9 THEN RnOr = 16
 IF har = 10 THEN RnOr = 10
 IF har = 1 AND zad = 2 THEN
 RnZ = RnZ * 3
 ELSE
 RnZ = RnZ
 END IF
 IF har = 2 AND zad = 2 THEN
 RnZ = RnZ * 3
 ELSE
 RnZ = RnZ
 END IF
 IF har = 3 AND zad = 2 THEN
 RnGa = RnGa * 3
 ELSE
 RnGa = RnGa
 END IF
 IF har = 4 AND zad = 1 THEN
 RnGa = RnGa / 3
 ELSE
 RnGa = RnGa
 END IF
 IF har = 5 AND zad = 1 THEN
 RnGa = RnGa / 3
 ELSE
 RnGa = RnGa
 END IF
 IF har = 5 AND zad = 1 THEN
 RnZ = RnZ / 3
 ELSE
 RnZ = RnZ
 END IF
 Razm = Fr * Gl / 10000
 IF har = 3 OR har = 4 OR har = 5 THEN RnGa = RnGa * Razm
 IF Dto > 10000 THEN RnZ = RnZ / 10000 * Dto
 IF Dto > 10000 THEN RnGa = RnGa / 10000 * Dto
 IF har = 1 AND stz = 1 THEN
 RnZ = RnZ / 3
 ELSE
 RnZ = RnZ
 END IF
 IF har = 2 AND stz = 2 THEN
 RnZ = RnZ * 3
 ELSE
 RnZ = RnZ
 END IF
 IF har = 3 AND stz = 1 THEN
 RnGa = RnGa / 3
 ELSE
 RnGa = RnGa
 END IF
 IF har = 4 AND stz = 2 THEN
 RnGa = RnGa * 3
 ELSE
 RnGa = RnGa
 END IF
 IF har = 5 AND stz = 2 THEN
 RnGa = RnGa * 3
 ELSE
 RnGa = RnGa
 END IF
 IF har = 6 AND stz = 2 THEN
 RnZ = RnZ * 3
 ELSE
 RnZ = RnZ
 END IF
 IF pod = 2 THEN RnZ = RnZ * 1.5: RnGa = RnGa * 1.5
 IF pod = 3 THEN RnZ = RnZ * .75: RnGa = RnGa * .75
 IF pod = 4 THEN RnZ = RnZ * .75: RnGa = RnGa * .75
 IF dol = 2 THEN RnZ = RnZ * .5: RnGa = RnGa * .5
 IF dol = 3 THEN RnZ = RnZ * .33: RnGa = RnGa * .33
 IF dol = 4 THEN RnZ = RnZ * .25: RnGa = RnGa * .25
 IF dol = 5 THEN RnZ = RnZ * .2: RnGa = RnGa * .2
 IF dol = 6 THEN RnZ = RnZ * .17: RnGa = RnGa * .17
 IF Gl >= 100 THEN
 korys = kor * 3
 ELSE
 korys = kor
 END IF
 IF Fr <= 150 THEN korys1 = korys
IF har = 1 AND stz = 1 THEN korys = korys
IF har = 1 AND stz = 2 THEN korys = korys * 2
IF har = 2 AND stz = 1 THEN korys = korys
IF har = 2 AND stz = 2 THEN korys = korys * 2
IF har = 3 AND stz = 1 THEN korys = korys
IF har = 3 AND stz = 2 THEN korys = korys * 2
IF har = 4 AND stz = 1 THEN korys = korys
IF har = 4 AND stz = 2 THEN korys = korys * 2
IF har = 5 AND stz = 1 THEN korys = korys
IF har = 5 AND stz = 2 THEN korys = korys * 2
IF har = 6 AND stz = 1 THEN korys = korys
IF har = 6 AND stz = 2 THEN korys = korys * 2
IF Fr <= 150 THEN korys = korys1
IF har = 7 OR har = 8 OR har = 9 OR har = 10 THEN korys = kor
IF pod = 4 THEN korys = korysf
 IF har = 1 OR har = 2 OR har = 6 THEN Rashod = RnZ
 IF har = 3 OR har = 4 OR har = 5 THEN Rashod = RnGa
 IF har = 7 OR har = 8 OR har = 9 OR har = 10 THEN Rashod = RnOr * kor
 IF har = 1 OR har = 2 OR har = 3 OR har = 4 OR har = 5 OR har = 6 THEN
 Rnorys = Rashod / (korys + .001)
 ELSE
 Rnorys = RnOr
 END IF

 PRINT "K.or.yst."; korys
 PRINT "..........................................................................."
PRINT "RASHOD NA ZEL="; INT(Rashod + .001), "RASHOD NA ORYD.YST="; CINT(Rnorys + .001)
PRINT "........................................................................."
INPUT "Metodicheski ogon raschitat? 1-Da,0-Net"; me
IF me = 1 THEN
GOTO 281
ELSE
GOTO 282
END IF
IF bat = 0 THEN bat = 1
281 INPUT "Vremia ognev.naleta="; vr
 Rbeg = kor * 2
 Rnamet = Rashod - Rbeg
 vrnamets = (vr - 1) * 60
 temp = CINT(vrnamets / Rnamet) * bat
PRINT "............................................................................."
PRINT "KOMANDA: Po"; CINT(Rnorys); "sn 2sn beglum ostalnue"; temp; "sek vustrel!!!"
PRINT "..........................................................................."
282

END SUB

SUB POREPERY (vsem AS SINGLE, dDr1 AS SINGLE, dDr AS SINGLE, dDov1 AS SINGLE, dDovre AS SINGLE, Dret1 AS SINGLE, Dret AS SINGLE, dDr2 AS SINGLE, dDov2 AS SINGLE, Dret2 AS SINGLE, dDr3 AS SINGLE, dDov3 AS SINGLE, Dret3 AS SINGLE, Nop AS SINGLE, dN AS SINGLE, dN1 AS SINGLE, dN2 AS SINGLE, dN3 AS SINGLE)
        IF Nop = 1 THEN
        dDr1 = dDr: dDov1 = dDovre: Dret1 = Dret: dN1 = dN
        ELSE
        dDr1 = dDr1: dDov1 = dDov1: Dret1 = Dret1: dN1 = dN1
        END IF
        IF Nop = 2 THEN
        dDr2 = dDr: dDov2 = dDovre: Dret2 = Dret: dN2 = dN
        ELSE
        dDr2 = dDr2: dDov2 = dDov2: Dret2 = Dret2: dN2 = dN2
        END IF
        IF Nop = 3 THEN
        dDr3 = dDr: dDov3 = dDovre: Dret3 = Dret: dN3 = dN
        ELSE
        dDr3 = dDr3: dDov3 = dDov3: Dret3 = Dret3: dN3 = dN3
        END IF


END SUB

SUB POSMOTRETOP
INPUT "OP-0, KNP-1"; vvod
IF vvod = 1 THEN
        GOTO 941
        ELSE
END IF
931 OPEN "OPTABL" FOR INPUT AS #1
DO WHILE NOT EOF(1)
FOR i = 1 TO 20
IF EOF(1) THEN GOTO 932
LINE INPUT #1, rec$
PRINT rec$
NEXT i
SLEEP
LOOP
932 CLOSE #1
GOTO 943
941 OPEN "KNPTABL" FOR INPUT AS #1
DO WHILE NOT EOF(1)
FOR i = 1 TO 20
IF EOF(1) THEN GOTO 942
LINE INPUT #1, rec$
PRINT rec$
NEXT i
SLEEP
LOOP
942 CLOSE #1
943
END SUB

SUB POSMOTRETV0 (v0pol1 AS SINGLE, v0ymen1 AS SINGLE, v0perv1 AS SINGLE, v0vtor1 AS SINGLE, v0tret1 AS SINGLE, v0chetv1 AS SINGLE, v0pol2 AS SINGLE, v0ymen2 AS SINGLE, v0perv2 AS SINGLE, v0vtor2 AS SINGLE, v0tret2 AS SINGLE, v0chetv2 AS SINGLE, v0pol3 AS SINGLE, v0ymen3 AS SINGLE, v0perv3 AS SINGLE, v0vtor3 AS SINGLE, v0tret3 AS SINGLE, v0chetv3 AS SINGLE)
INPUT " Vo s faila - 1, Net - 0"; vvod
IF vvod = 1 THEN
OPEN "vnyl1.bet" FOR INPUT AS #1
INPUT #1, v1, v2, v3, v4, v5, v6
v0pol1 = v1: v0ymen1 = v2: v0perv1 = v3: v0vtor1 = v4: v0tret1 = v5: v0chetv1 = v6
CLOSE #1
OPEN "vnyl2.bet" FOR INPUT AS #1
INPUT #1, v1, v2, v3, v4, v5, v6
v0pol2 = v1: v0ymen2 = v2: v0perv2 = v3: v0vtor2 = v4: v0tret2 = v5: v0chetv2 = v6
CLOSE #1
OPEN "vnyl3.bet" FOR INPUT AS #1
INPUT #1, v1, v2, v3, v4, v5, v6
v0pol3 = v1: v0ymen3 = v2: v0perv3 = v3: v0vtor3 = v4: v0tret3 = v5: v0chetv3 = v6
CLOSE #1
PRINT TAB(25); " << dVo >>"
PRINT " 1B "; TAB(30); " 2B "; TAB(60); " 3B "
PRINT " Pol = "; v0pol1; TAB(30); " Pol = "; v0pol2; TAB(60); " Pol = "; v0pol3
PRINT " Ymen = "; v0ymen1; TAB(30); " Ymen = "; v0ymen2; TAB(60); " Ymen = "; v0ymen3
PRINT " Perv = "; v0perv1; TAB(30); " Perv = "; v0perv2; TAB(60); " Perv = "; v0perv3
PRINT " Vtor = "; v0vtor1; TAB(30); " Vtor = "; v0vtor2; TAB(60); " Vtor = "; v0vtor3
PRINT " Tret = "; v0tret1; TAB(30); " Tret = "; v0tret2; TAB(60); " Tret = "; v0tret3
PRINT " Chetv = "; v0chetv1; TAB(30); " Chetv = "; v0chetv2; TAB(60); " Chetv = "; v0chetv3
ELSE
PRINT TAB(25); " << dVo >>"
PRINT " 1B "; TAB(30); " 2B "; TAB(60); " 3B "
PRINT " Pol = "; v0pol1; TAB(30); " Pol = "; v0pol2; TAB(60); " Pol = "; v0pol3
PRINT " Ymen = "; v0ymen1; TAB(30); " Ymen = "; v0ymen2; TAB(60); " Ymen = "; v0ymen3
PRINT " Perv = "; v0perv1; TAB(30); " Perv = "; v0perv2; TAB(60); " Perv = "; v0perv3
PRINT " Vtor = "; v0vtor1; TAB(30); " Vtor = "; v0vtor2; TAB(60); " Vtor = "; v0vtor3
PRINT " Tret = "; v0tret1; TAB(30); " Tret = "; v0tret2; TAB(60); " Tret = "; v0tret3
PRINT " Chetv = "; v0chetv1; TAB(30); " Chetv = "; v0chetv2; TAB(60); " Chetv = "; v0chetv3
END IF
END SUB

SUB POSMOTRETZELI
INPUT " Zel-0, NZO-1, Tochk.Vstrech-2, PZO-3 "; chza
IF chza = 0 THEN GOTO 901
IF chza = 1 THEN GOTO 902
IF chza = 2 THEN GOTO 903
IF chza = 3 THEN GOTO 904

901
OPEN "Zeli" FOR INPUT AS #1
DO WHILE NOT EOF(1)
FOR i = 1 TO 20
IF EOF(1) THEN GOTO 1111
LINE INPUT #1, rec$
PRINT rec$
NEXT i
SLEEP
LOOP
1111 CLOSE #1
        GOTO 904.1
902
OPEN "NZO" FOR INPUT AS #1
DO WHILE NOT EOF(1)
FOR i = 1 TO 20
IF EOF(1) THEN GOTO 1112
LINE INPUT #1, rec$
PRINT rec$
NEXT i
SLEEP
LOOP
1112 CLOSE #1
        GOTO 904.1
903
OPEN "Toch.Vst" FOR INPUT AS #1
DO WHILE NOT EOF(1)
FOR i = 1 TO 20
IF EOF(1) THEN GOTO 1113
LINE INPUT #1, rec$
PRINT rec$
NEXT i
SLEEP
LOOP
1113 CLOSE #1
        GOTO 904.1
904
OPEN "PZO" FOR INPUT AS #1
DO WHILE NOT EOF(1)
FOR i = 1 TO 20
IF EOF(1) THEN GOTO 1114
LINE INPUT #1, rec$
PRINT rec$
NEXT i
SLEEP
LOOP
1114 CLOSE #1
904.1
END SUB

SUB PRICAR5 (zar AS SINGLE, Disch AS SINGLE, Pric.isch AS SINGLE, N AS SINGLE)
  IF zar = 0 THEN
  OPEN "I", #1, "ar5-P"
  ELSEIF zar = 5 THEN
  OPEN "I", #1, "ar5-Y"
  ELSEIF zar = 1 THEN
  OPEN "I", #1, "ar5-1"
  ELSEIF zar = 2 THEN
  OPEN "I", #1, "ar5-2"
  ELSEIF zar = 3 THEN
  OPEN "I", #1, "ar5-3"
  ELSEIF zar = 4 THEN
  OPEN "I", #1, "ar5-4"
  ELSE
  OPEN "I", #1, "ar5-P"
  END IF
301 IF EOF(1) THEN GOTO 303
  INPUT #1, ta1, ta2, ta3
  IF ta1 <= Disch THEN GOTO 302
      GOTO 301
302 Pric = ta2: Dta = ta1: N = ta3
303 CLOSE #1
  Dischh = Disch + 200
  IF zar = 0 THEN
  OPEN "I", #1, "ar5-P"
  ELSEIF zar = 5 THEN
  OPEN "I", #1, "ar5-Y"
  ELSEIF zar = 1 THEN
  OPEN "I", #1, "ar5-1"
  ELSEIF zar = 2 THEN
  OPEN "I", #1, "ar5-2"
  ELSEIF zar = 3 THEN
  OPEN "I", #1, "ar5-3"
  ELSEIF zar = 4 THEN
  OPEN "I", #1, "ar5-4"
  ELSE
  OPEN "I", #1, "ar5-P"
  END IF
304 IF EOF(1) THEN GOTO 306
   INPUT #1, ta1, ta2, ta3
   IF ta1 <= Dischh THEN GOTO 305
   GOTO 304
305 Pricc = ta2: Nn = ta3
306  CLOSE #1
    Pric.isch = (Pricc - Pric) / 200 * (Disch - Dta) + Pric
    N = (Nn - N) / 200 * (Disch - Dta) + N

END SUB

SUB PRICELOFRGM (zar AS SINGLE, Disch AS SINGLE, ts AS SINGLE, dXtus AS SINGLE, Ygvozv AS SINGLE, Vustra AS SINGLE, Pric.isch AS SINGLE)
   IF zar = 0 THEN
   OPEN "I", #1, "2C1P"
   ELSEIF zar = 5 THEN
   OPEN "I", #1, "2C1Y"
   ELSEIF zar = 1 THEN
   OPEN "I", #1, "2C11"
   ELSEIF zar = 2 THEN
   OPEN "I", #1, "2C12"
   ELSEIF zar = 3 THEN
   OPEN "I", #1, "2C13"
   ELSEIF zar = 4 THEN
   OPEN "I", #1, "2C14"
   ELSE
   OPEN "I", #1, "2C1P"
END IF
IF Disch > 15200 THEN
Disch = 15200
ELSE
Disch = Disch
END IF

92.31 IF EOF(1) THEN GOTO 92.32
  INPUT #1, ta1, ta2, ta3, ta4, ta5, ta6, ta7, ta8, ta9, ta10, ta11, ta12, ta13, ta14, ta15, ta16, ta17, ta18, ta19, ta20, ta21, ta22, ta23, ta24, ta25, ta26, ta27, ta28, ta29, ta30, ta31, ta32, ta33, ta34, ta35, ta36, ta37
  IF ta1 <= Disch THEN GOTO 92.311
      GOTO 92.31
92.311 Pric = ta2: Dta = ta1: ts = ta16: dXtus = ta3: Ygvozv = ta13: Vustra = ta17
92.32 CLOSE #1
  Dischh = Disch + 200
IF Dischh > 15200 THEN
Dischh = 15200
ELSE
Dischh = Dischh
END IF
   IF zar = 0 THEN
   OPEN "I", #1, "2C1P"
   ELSEIF zar = 5 THEN
   OPEN "I", #1, "2C1Y"
   ELSEIF zar = 1 THEN
   OPEN "I", #1, "2C11"
   ELSEIF zar = 2 THEN
   OPEN "I", #1, "2C12"
   ELSEIF zar = 3 THEN
   OPEN "I", #1, "2C13"
   ELSEIF zar = 4 THEN
   OPEN "I", #1, "2C14"
   ELSE
   OPEN "I", #1, "2C1P"
END IF
92.321 IF EOF(1) THEN GOTO 92.322
   INPUT #1, ta1, ta2, ta3, ta4, ta5, ta6, ta7, ta8, ta9, ta10, ta11, ta12, ta13, ta14, ta15, ta16, ta17, ta18, ta19, ta20, ta21, ta22, ta23, ta24, ta25, ta26, ta27, ta28, ta29, ta30, ta31, ta32, ta33, ta34, ta35, ta36, ta37
   IF ta1 <= Dischh THEN GOTO 92.3211
   GOTO 92.321
92.3211 Pricc = ta2
92.322  CLOSE #1
    Pric.isch = (Pricc - Pric) / 200 * (Disch - Dta) + Pric

END SUB

SUB PRICMORT (zar AS SINGLE, Disch AS SINGLE, ts AS SINGLE, Pric.isch AS SINGLE)
  IF zar = 0 THEN
  OPEN "I", #1, "2C1MORTP"
  ELSEIF zar = 5 THEN
  OPEN "I", #1, "2C1MORTY"
  ELSEIF zar = 1 THEN
  OPEN "I", #1, "2C1MORT1"
  ELSEIF zar = 2 THEN
  OPEN "I", #1, "2C1MORT2"
  ELSEIF zar = 3 THEN
  OPEN "I", #1, "2C1MORT3"
  ELSEIF zar = 4 THEN
  OPEN "I", #1, "2C1MORT4"
  ELSE
  OPEN "I", #1, "2C1MORTP"
  END IF
392.31 IF EOF(1) THEN GOTO 392.32
  INPUT #1, ta1, ta2, ta3, ta4, ta5, ta6, ta7, ta8, ta9, ta10
  IF ta1 <= Disch THEN GOTO 392.311
      GOTO 392.31
392.311 Pric = ta2: Dta = ta1: ts = ta10
392.32 CLOSE #1
  Dischh = Disch + 200
  IF zar = 0 THEN
  OPEN "I", #1, "2C1MORTP"
  ELSEIF zar = 5 THEN
  OPEN "I", #1, "2C1MORTY"
  ELSEIF zar = 1 THEN
  OPEN "I", #1, "2C1MORT1"
  ELSEIF zar = 2 THEN
  OPEN "I", #1, "2C1MORT2"
  ELSEIF zar = 3 THEN
  OPEN "I", #1, "2C1MORT3"
  ELSEIF zar = 4 THEN
  OPEN "I", #1, "2C1MORT4"
  ELSE
  OPEN "I", #1, "2C1MORTP"
  END IF
392.321 IF EOF(1) THEN GOTO 392.322
   INPUT #1, ta1, ta2, ta3, ta4, ta5, ta6, ta7, ta8, ta9, ta10
   IF ta1 <= Dischh THEN GOTO 392.3211
   GOTO 392.321
392.3211 Pricc = ta2
392.322  CLOSE #1
    Pric.isch = (Pricc - Pric) / 200 * (Disch - Dta) + Pric

END SUB

SUB REPERmeny
 PRINT "BBOD 12 REPER"
 PRINT "BBOD 13 PRISTRELANNUE POPRAVKI"
END SUB

SUB REPERN (snvz AS SINGLE, zar AS SINGLE, Pric.pris AS SINGLE, dN AS SINGLE, N AS SINGLE, dXtus AS SINGLE, Dprisn AS SINGLE)
IF snvz = 2 THEN
       IF zar = 0 THEN
       OPEN "B-90P" FOR INPUT AS #1
       ELSEIF zar = 5 THEN
       OPEN "B-90y" FOR INPUT AS #1
       ELSEIF zar = 1 THEN
       OPEN "B-901" FOR INPUT AS #1
       ELSEIF zar = 2 THEN
       OPEN "B-902" FOR INPUT AS #1
       ELSEIF zar = 3 THEN
       OPEN "B-903" FOR INPUT AS #1
       ELSE
       OPEN "B-90P" FOR INPUT AS #1
       END IF
       ELSEIF snvz = 0 THEN
       GOTO 226.001
       ELSE
       IF zar = 0 THEN OPEN "3sh-P" FOR INPUT AS #1
       IF zar = 5 THEN OPEN "3SH-Y" FOR INPUT AS #1
END IF
225.1 IF EOF(1) THEN GOTO 225.5
INPUT #1, ta1, ta2, ta3, ta4, ta5, ta6, ta7, ta8
IF ta2 >= Pric.pris THEN GOTO 225.2
GOTO 225.1
225.2   Dta = ta1: Prta = ta2: dNtus = ta4: Nta = ta3: GOTO 225.5
225.5 CLOSE
Nrp = (Pric.pris - Prta) * dNtus + Nta
dN = N - Nrp - (daep * dNtus)
Dprisn = (Pric.pris - Prta) * dXtus + Dta
226.001
END SUB

SUB SERVZADmeny
     PRINT "BBOD 21 SPRAVKA"
     PRINT "BBOD 17 POR.NEN.ZELI"
     PRINT "BBOD 18 OBIEKT ATAKI"
     PRINT "BBOD 22 ZAPIS.ZELI"
     PRINT "BBOD 23 POSMOTR.ZELI"
     PRINT "BBOD 25 RASCH.A.ATAKI"
     PRINT "BBOD 27 SHKVAL!!!"
     PRINT "BBOD 28 KNP PO ZELI"
     PRINT "BBOD 29 OCHISTKA PLAN.ZEL"
     PRINT "BBOD 31 ZAP.ZEL V TAB.ISCH.YST"
     PRINT "BBOD 39 ZAPISAT OP"
     PRINT "BBOD 40 ZAPISAT NP"
END SUB

SUB SOPRIAGENKA (Xl AS SINGLE, Yl AS SINGLE, hl AS SINGLE, Xp AS SINGLE, Yp AS SINGLE, hp AS SINGLE, Alev AS SINGLE, Aprav AS SINGLE, Mcl AS SINGLE, Mcp AS SINGLE, hc AS SINGLE, Xc AS SINGLE, Yc AS SINGLE)
  dxso = Xp - Xl: dyso = Yp - Yl
  baz = SQR(dxso ^ 2 + dyso ^ 2)
  aso = ABS(ATN(dyso / (dxso + .1)) / 3.141592 * 30) * 100

  IF dxso > 0 AND dyso > 0 THEN ygol.baz = INT(aso)
  IF dxso < 0 AND dyso > 0 THEN ygol.baz = INT(3000 - aso)
  IF dxso < 0 AND dyso < 0 THEN ygol.baz = INT(3000 + aso)
  IF dxso > 0 AND dyso < 0 THEN ygol.baz = INT(6000 - aso)
  IF Alev < 1500 AND Aprav > 4500 THEN
  fi = ABS(Alev + 6000 - Aprav)
  ELSEIF Alev > 4500 AND Aprav < 1500 THEN
  fi = ABS(Alev - (Aprav + 6000))
  ELSE
   fi = ABS(Alev - Aprav)
  END IF
  IF Alev < 1500 AND ygol.baz > 4500 THEN
  blev = ABS(Alev + 6000 - ygol.baz)
  ELSEIF Alev > 4500 AND ygol.baz < 1500 THEN
  blev = ABS(Alev - (ygol.baz + 6000))
  ELSE
  blev = ABS(Alev - ygol.baz)
  END IF

  IF ygol.baz - 3000 < 0 THEN
  ybazp = ygol.baz + 3000
  ELSE
  ybazp = ygol.baz - 3000
  END IF

  IF Aprav < 1500 AND ybazp > 4500 THEN
  bprav = ABS(Aprav + 6000 - ybazp)
  ELSEIF Aprav > 4500 AND ybazp < 1500 THEN
  bprav = ABS(Aprav - (ybazp + 6000))
  ELSE
  bprav = ABS(Aprav - ybazp)
  END IF
 
  Dlev = baz / (SIN(fi / 100 * 6 * 3.141592 / 180) + .001) * SIN(bprav / 100 * 6 * 3.141592 / 180)
  Dprav = baz / (SIN(fi / 100 * 6 * 3.141592 / 180) + .001) * SIN(blev / 100 * 6 * 3.141592 / 180)
  Xcso = COS(Alev / 100 * 6 * 3.141592 / 180) * Dlev + Xl
  Ycso = SIN(Alev / 100 * 6 * 3.141592 / 180) * Dlev + Yl
  IF Mcl = 0 THEN hc = Mcp * (Dprav * .001) * 1.05 + hp
  IF Mcp = 0 THEN hc = Mcl * (Dlev * .001) * 1.05 + hl
  Xc = Xcso: Yc = Ycso

END SUB

SUB SPRAVKA
COLOR 10, 0
PRINT "OF/RGM"
COLOR 14, 0
PRINT " Zar=P Rikoshet do 8200, Maks. Daln 15200, Mortir s 15200 do 10000"
PRINT " Zar=Y Rikoshet do 7000, Maks. Daln 12800, Mortir s 12800 do 8400"
PRINT " Zar=1 Rikoshet do 6200, Maks. Daln 11400, Mortir s 11400 do 7600"
PRINT " Zar=2 Rikoshet do 5800, Maks. Daln 10000, Mortir s 10000 do 6600"
PRINT " Zar=3 Rikoshet do 5200, Maks. Daln 8200, Mortir s 8200 do 5400"
PRINT " Zar=4 Rikoshet do 4000, Maks. Daln 6200, Mortir s 6200 do 4000"
COLOR 10, 0
PRINT "OF/B-90 Maks Dal privedena dla VRV = < 15"
COLOR 14, 0
PRINT "Zar=P Maks Dal 5200; Zar=Y Maks Dal 4400; Zar=1 Maks Dal 3800"
PRINT "Zar=2 Maks Dal 3400; Zar=3 Maks Dal 3000"
COLOR 10, 0
PRINT "OF/AR-5 Smotret OF/RGM"
PRINT "3SH1/DT-75"
COLOR 14, 0
PRINT "Zar=P Maks Dal 15000; Zar=Y Maks Dal 12400"
COLOR 10, 0
PRINT "C4/T-90"
COLOR 14, 0
PRINT "Zar=P na Dalnostiah s 6200 po 15000; Zar=Y na Dalnostiah s 5200 po 12400"
PRINT "Zar=1 na Dalnostiah s 5000 po 10800; Zar=2 na Dalnostiah s 4400 po 9200"
PRINT "Zar=3 na Dalnostiah s 4000 po 7200; Zar=4 na Dalnostiah s 3200 po 5400"

END SUB

 SUB T90 (Disch AS SINGLE, zar AS SINGLE, dNtus AS SINGLE, Pric.isch AS SINGLE, N AS SINGLE)
IF Disch > 15000 THEN Disch = 15000
    IF zar = 0 THEN
    OPEN "T-90p" FOR INPUT AS #1
    ELSEIF zar = 5 THEN
    OPEN "T-90Y" FOR INPUT AS #1
    ELSEIF zar = 1 THEN
    OPEN "T-901" FOR INPUT AS #1
    ELSEIF zar = 2 THEN
    OPEN "T-902" FOR INPUT AS #1
    ELSEIF zar = 3 THEN
    OPEN "T-903" FOR INPUT AS #1
    ELSE
    OPEN "T-904" FOR INPUT AS #1
    END IF
601 IF EOF(1) THEN GOTO 603
  INPUT #1, ta1, ta2, ta3, ta4
  IF ta1 <= Disch AND ta1 + 200 >= Disch THEN GOTO 602
      GOTO 601
602 Pric = ta2: Dta = ta1: N = ta3: dNtus = ta4
603 CLOSE #1
  Dischh = Disch + 200
  IF Dischh > 15000 THEN Dischh = 15000
    IF zar = 0 THEN
    OPEN "T-90p" FOR INPUT AS #1
    ELSEIF zar = 5 THEN
    OPEN "T-90Y" FOR INPUT AS #1
    ELSEIF zar = 1 THEN
    OPEN "I", #1, "T-901"
    ELSEIF zar = 2 THEN
    OPEN "T-902" FOR INPUT AS #1
    ELSEIF zar = 3 THEN
    OPEN "T-903" FOR INPUT AS #1
    ELSE
    OPEN "T-904" FOR INPUT AS #1
    END IF
604 IF EOF(1) THEN GOTO 606
   INPUT #1, ta1, ta2, ta3, ta4
   IF ta1 <= Dischh AND ta1 + 200 >= Dischh THEN GOTO 605
   GOTO 604
605 Pricc = ta2: Nn = ta3
606  CLOSE #1
    Pric.isch = (Pricc - Pric) / 200 * (Disch - Dta) + Pric
    N = (Nn - N) / 200 * (Disch - Dta) + N


END SUB

 SUB TABISCHYST (zar1 AS SINGLE, zar2 AS SINGLE, zar3 AS SINGLE, pr.eps1 AS SINGLE, pr.eps2 AS SINGLE, pr.eps3 AS SINGLE, dov.isch1 AS SINGLE, dov.isch2 AS SINGLE, dov.isch3 AS SINGLE, sk.shk1 AS SINGLE, sk.shk2 AS SINGLE, sk.shk3 AS SINGLE, opn1$, opn2$, opn3$, OH1 AS SINGLE, OH2 AS SINGLE, OH3 AS SINGLE, Xop1 AS SINGLE, Xop2 AS SINGLE, Xop3 AS SINGLE, Yop1 AS SINGLE, Yop2 AS SINGLE, Yop3 AS SINGLE, hop1 AS SINGLE, hop2 AS SINGLE, hop3 AS SINGLE)
INPUT "Ochistit predudyschie zapisi 0-Net, 1-Da"; ochist
INPUT "Buxod-1, 0-Net"; vux
IF vux = 1 THEN
        GOTO 3250
        ELSE
END IF
IF ochist = 1 THEN
        OPEN "tabisch.yst" FOR OUTPUT AS #1
        CLOSE #1
        ELSE
END IF
INPUT "N Batarei="; nbat
IF nbat = 1 THEN
        zar = zar1: Pric = pr.eps1: dov = dov.isch1: skach = sk.shk1: opn$ = opn1$: OH = OH1: Xop = Xop1: Yop = Yop1: hop = hop1
        ELSEIF nbat = 2 THEN
        zar = zar2: Pric = pr.eps2: dov = dov.isch2: skach = sk.shk2: opn$ = opn2$: OH = OH2: Xop = Xop2: Yop = Yop2: hop = hop2
        ELSEIF nbat = 3 THEN
        zar = zar3: Pric = pr.eps3: dov = dov.isch3: skach = sk.shk3: opn$ = opn3$: OH = OH3: Xop = Xop3: Yop = Yop3: hop = hop3
        ELSE
        zar = zar1: Pric = pr.eps1: dov = dov.isch1: skach = sk.shk1: opn$ = opn1$: OH = OH1: Xop = Xop1: Yop = Yop1: hop = hop1
END IF
IF zar = 0 THEN
        zarr$ = "POLNIY"
        ELSEIF zar = 5 THEN
        zarr$ = "YMENSHENIY"
        ELSEIF zar = 1 THEN
        zarr$ = "PERVIY"
        ELSEIF zar = 2 THEN
        zarr$ = "VTOROI"
        ELSEIF zar = 3 THEN
        zarr$ = "TRETIY"
        ELSE
        zarr$ = "CHETVERTUI"
END IF
INPUT "Zapis Zel-0, OP i Daty -1"; zapis
IF zapis = 1 THEN
        OPEN "tabisch.yst" FOR APPEND AS #1
        INPUT " Data = "; t1$
        PRINT #1, t1$
        t1$ = "******************************************************"
        PRINT #1, t1$
        PRINT #1, nbat; " BATAREIA "
        t1$ = "N OP = ": t2$ = opn$: t3$ = " OH = ": t4 = OH: t5$ = " Xop = ": t6 = Xop: t7$ = " Yop = ": t8 = Yop: t9$ = " hop = ": t10 = hop
        PRINT #1, t1$; t2$; t3$; t4; t5$; t6; t7$; t8; t9$; t10
        t1$ = "******************************************************"
        PRINT #1, t1$
        CLOSE #1
        ELSE
END IF
INPUT "N Zeli="; Nzeli$
INPUT "Veer="; veerr$
INPUT "K-vo ystanovok"; ystan$
INPUT "Vzrivatel="; vzriv$
t1$ = "N ZELI": t2$ = Nzeli$: t3$ = "ZARIAD": t4$ = zarr$: t5$ = "PRICEL": t6 = Pric: t7$ = "OH": t8 = dov: t9$ = "VEER = ": t10$ = veerr$: t11$ = "Y.Y. = ": t12$ = ystan$: t13$ = "VZRIVATEL = ": t14$ = vzriv$: t15$ = "SKACHEK = ": t16 = skach: t17$ = "YGLOMER"
OPEN "tabisch.yst" FOR APPEND AS #1
PRINT #1, t1$, t5$, t7$, t17$
PRINT #1, t2$, t6, t8
PRINT #1, t3$
PRINT #1, t4$
PRINT #1, t9$; t10$
PRINT #1, t11$; t12$
PRINT #1, t13$; t14$
PRINT #1, t15$; t16
t1$ = "---------------------------------------------------------------"
PRINT #1, t1$
CLOSE #1
3250
END SUB

SUB VVODVO
INPUT "2B vvodit 1-Da, 0-Net"; vvod
IF vvod = 1 THEN
OPEN "vnyl1.bet" FOR OUTPUT AS #1
INPUT " Vo = Pol, Ymen, Perv, Vtor, Tret, Chetv "; v0pol1, v0ymen1, v0perv1, v0vtor1, v0tret1, v0chetv1
v1 = v0pol1: v2 = v0ymen1: v3 = v0perv1: v4 = v0vtor1: v5 = v0tret1: v6 = v0chetv1
WRITE #1, v1, v2, v3, v4, v5, v6
CLOSE #1
ELSE
END IF
INPUT "2B vvodit 1-Da, 0-Net"; vvod
IF vvod = 1 THEN
OPEN "vnyl2.bet" FOR OUTPUT AS #1
INPUT " Vo = Pol, Ymen, Perv, Vtor, Tret, Chetv "; v0pol2, v0ymen2, v0perv2, v0vtor2, v0tret2, v0chetv2
v1 = v0pol2: v2 = v0ymen2: v3 = v0perv2: v4 = v0vtor2: v5 = v0tret2: v6 = v0chetv2
WRITE #1, v1, v2, v3, v4, v5, v6
CLOSE #1
ELSE
END IF
INPUT "3B vvodit 1-Da 0-Net"; vvod
IF vvod = 1 THEN
OPEN "vnyl3.bet" FOR OUTPUT AS #1
INPUT " Vo = Pol, Ymen, Perv, Vtor, Tret, Chetv "; v0pol3, v0ymen3, v0perv3, v0vtor3, v0tret3, v0chetv3
v1 = v0pol3: v2 = v0ymen3: v3 = v0perv3: v4 = v0vtor3: v5 = v0tret3: v6 = v0chetv3
WRITE #1, v1, v2, v3, v4, v5, v6
CLOSE #1
ELSE
END IF

END SUB

SUB WETER (vvod AS SINGLE, W AS SINGLE, Dsnos AS SINGLE, w200 AS SINGLE, w400 AS SINGLE, w800 AS SINGLE, w1200 AS SINGLE, w1600 AS SINGLE, w2000 AS SINGLE, w2400 AS SINGLE, w3000 AS SINGLE, w4000 AS SINGLE)
IF vvod = 0 THEN
    OPEN "I", #1, "weter"
2.54    IF EOF(1) THEN GOTO 2.55
        INPUT #1, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10
        IF W = w1 THEN w200 = w2: w400 = w3: w800 = w4: w1200 = w5: w1600 = w6: w2000 = w7: w2400 = w8: w3000 = w9: w4000 = w10
        IF w200 <> 0 THEN GOTO 2.55
        GOTO 2.54
2.55    CLOSE #1
        ELSE
        IF Dsnos < 30 THEN
                Dsnos = 0
                ELSEIF Dsnos >= 30 AND Dsnos < 40 THEN
                Dsnos = 30
                ELSEIF Dsnos >= 40 AND Dsnos < 50 THEN
                Dsnos = 40
                ELSEIF Dsnos >= 50 AND Dsnos < 60 THEN
                Dsnos = 50
                ELSEIF Dsnos >= 60 AND Dsnos < 70 THEN
                Dsnos = 60
                ELSEIF Dsnos >= 70 AND Dsnos < 80 THEN
                Dsnos = 70
                ELSEIF Dsnos >= 80 AND Dsnos < 90 THEN
                Dsnos = 80
                ELSEIF Dsnos >= 90 AND Dsnos < 100 THEN
                Dsnos = 90
                ELSEIF Dsnos >= 100 AND Dsnos < 110 THEN
                Dsnos = 100
                ELSEIF Dsnos >= 110 AND Dsnos < 120 THEN
                Dsnos = 110
                ELSEIF Dsnos >= 120 AND Dsnos < 130 THEN
                Dsnos = 120
                ELSEIF Dsnos >= 130 AND Dsnos < 140 THEN
                Dsnos = 130
                ELSEIF Dsnos >= 140 AND Dsnos < 150 THEN
                Dsnos = 140
                ELSE
                Dsnos = 150
        END IF
        OPEN "weter.wr2" FOR INPUT AS #1
2.551  IF EOF(1) THEN GOTO 2.552
        INPUT #1, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10
        IF Dsnos = w1 THEN
        w200 = w2: w400 = w3: w800 = w4: w1200 = w5: w1600 = w6: w2000 = w7: w2400 = w8: w3000 = w9: w4000 = w10
        GOTO 2.552
        ELSE
        GOTO 2.551
        END IF
2.552   CLOSE #1
END IF
END SUB

SUB YGLUKNP (Xc AS SINGLE, Yc AS SINGLE, hc AS SINGLE, Dtkp AS SINGLE, Yrkp AS SINGLE, Ygol.tkp AS SINGLE, Xkp AS SINGLE, Ykp AS SINGLE, hkp AS SINGLE)
   dx = Xc - Xkp
 DY = Yc - Ykp
 dh = hc - hkp
   Pi = 3.14159265358#
 Dtkp = INT(SQR(dx ^ 2 + DY ^ 2))
 Yrkp = INT((dh / (Dtkp * .001 + .1)) * .95)
 A = ABS(ATN(DY / (dx + .1)) / Pi * 30) * 100
 IF dx > 0 AND DY > 0 THEN Ygol.tkp = INT(A)
 IF dx < 0 AND DY > 0 THEN Ygol.tkp = INT(3000 - A)
 IF dx < 0 AND DY < 0 THEN Ygol.tkp = INT(3000 + A)
 IF dx > 0 AND DY < 0 THEN Ygol.tkp = INT(6000 - A)

END SUB

SUB ZAPISATZEL
INPUT " Zel-0, NZO-1, Tochk.Vstrech-2, PZO-3 "; chza
IF chza = 0 THEN GOTO 801
IF chza = 1 THEN GOTO 802
IF chza = 2 THEN GOTO 803
IF chza = 3 THEN GOTO 804
801 OPEN "Zeli" FOR APPEND AS #1
        DO
        INPUT " N i Xar.zeli, X, Y, h"; Xar$, X, Y, h
        WRITE #1, Xar$, X, Y, h
        INPUT " prodolgit 0-da, 1-net "; pro
        LOOP WHILE pro = 0
        CLOSE #1
        GOTO 804.1
802 OPEN "NZO" FOR APPEND AS #1
        DO
        INPUT " N i Xar.zeli, Xl, Yl, Xp, Yp, hc "; Xar$, Xl, Yl, Xp, Yp, hc
         WRITE #1, Xar$, Xl, Yl, Xp, Yp, hc
         INPUT " prodolgit 0-da, 1-net "; pro
         LOOP WHILE pro = 0
        CLOSE #1
        GOTO 804.1
803 OPEN "Toch.Vst" FOR APPEND AS #1
        DO
        INPUT " N i Xar.zeli, X, Y, h "; Xar$, X, Y, h
        WRITE #1, Xar$, X, Y, h
        INPUT " prodolgit 0-da, 1-net "; pro
        LOOP WHILE pro = 0
        CLOSE #1
        GOTO 804.1
804 OPEN "PZO" FOR APPEND AS #1
        DO
        INPUT " N i Xar.zeli, X, Y, h, Aat "; Xar$, X, Y, h, Aat
        WRITE #1, Xar$, X, Y, h, Aat
        INPUT " prodolgit 0-da, 1-net "; pro
        LOOP WHILE pro = 0
        CLOSE #1
804.1
END SUB

SUB ZAPISNP
PRINT " <<ZAPIS NP>> "
DO
INPUT " N NP, X, Y, h "; N$, X, Y, h
OPEN "KNPtabl" FOR APPEND AS #1
WRITE #1, N$, X, Y, h
INPUT " prodolgit 0-da, 1-net "; pro
CLOSE #1
LOOP WHILE pro = 0
END SUB

SUB ZAPISOP
PRINT " <<ZAPIS OP>> "
DO
INPUT " N OP, X, Y, h "; N$, X, Y, h
OPEN "optabl" FOR APPEND AS #1
WRITE #1, N$, X, Y, h
INPUT " prodolgit 0-da, 1-net "; pro
CLOSE #1
LOOP WHILE pro = 0
END SUB

SUB ZAPRASCH1 (rep1 AS SINGLE, rep2 AS SINGLE, rep3 AS SINGLE, vsem AS SINGLE, zar1 AS SINGLE, zar2 AS SINGLE, zar3 AS SINGLE, snvz1 AS SINGLE, snvz2 AS SINGLE, snvz3 AS SINGLE, pr.eps1 AS SINGLE, pr.eps2 AS SINGLE, pr.eps3 AS SINGLE, N1 AS SINGLE, N2 AS SINGLE, N3 AS SINGLE, dov.isch1 AS SINGLE, dov.isch2 AS SINGLE, dov.isch3 AS SINGLE)
OPEN "zaprasch.arx" FOR APPEND AS #1
 IF rep1 = 1 OR vsem = 1 THEN PRINT #1, "*PRISTRELANNUE*"; TAB(30);
 IF rep1 = 0 AND vsem = 0 THEN PRINT #1, "*POLNAIA PODG*"; TAB(30);
 IF rep2 = 1 OR vsem = 1 THEN PRINT #1, "*PRISTRELANNUE*"; TAB(60);
 IF rep2 = 0 AND vsem = 0 THEN PRINT #1, "*POLNAIA PODG*"; TAB(60);
 IF rep3 = 1 OR vsem = 1 THEN PRINT #1, "*PRISTRELANNUE*"
 IF rep3 = 0 AND vsem = 0 THEN PRINT #1, "*POLNAIA PODG*"
    IF zar1 = 0 THEN PRINT #1, "ZARIAD=POLNIY"; TAB(30);
    IF zar1 = 5 THEN PRINT #1, "ZARIAD=YMENSH"; TAB(30);
    IF zar1 = 1 THEN PRINT #1, "ZARIAD=PERViY"; TAB(30);
    IF zar1 = 2 THEN PRINT #1, "ZARIAD=VTOROY"; TAB(30);
    IF zar1 = 3 THEN PRINT #1, "ZARIAD=TRETIY"; TAB(30);
    IF zar1 = 4 THEN PRINT #1, "ZARIAD=CHETVERTIY"; TAB(30);
    IF zar2 = 0 THEN PRINT #1, "ZARIAD=POLNIY"; TAB(60);
    IF zar2 = 5 THEN PRINT #1, "ZARIAD=YMENSH"; TAB(60);
    IF zar2 = 1 THEN PRINT #1, "ZARIAD=PERViY"; TAB(60);
    IF zar2 = 2 THEN PRINT #1, "ZARIAD=VTOROY"; TAB(60);
    IF zar2 = 3 THEN PRINT #1, "ZARIAD=TRETIY"; TAB(60);
    IF zar2 = 4 THEN PRINT #1, "ZARIAD=CHETVERTIY"; TAB(60);
    IF zar3 = 0 THEN PRINT #1, "ZARIAD=POLNIY"
    IF zar3 = 5 THEN PRINT #1, "ZARIAD=YMENSH"
    IF zar3 = 1 THEN PRINT #1, "ZARIAD=PERViY"
    IF zar3 = 2 THEN PRINT #1, "ZARIAD=VTOROY"
    IF zar3 = 3 THEN PRINT #1, "ZARIAD=TRETIY"
    IF zar3 = 4 THEN PRINT #1, "ZARIAD=CHETVERTIY"
    IF snvz1 = 0 THEN PRINT #1, "Sn/Vz=OF/RGM"; TAB(30);
    IF snvz1 = 1 THEN PRINT #1, "Sn/Vz=OF/AR5"; TAB(30);
    IF snvz1 = 2 THEN PRINT #1, "Sn/Vz=3SH1/DT"; TAB(30);
    IF snvz1 = 3 THEN PRINT #1, "Sn/Vz=OF/B-90"; TAB(30);
    IF snvz1 = 4 THEN PRINT #1, "Sn/Vz=C4/T-90"; TAB(30);
    IF snvz2 = 0 THEN PRINT #1, "Sn/Vz=OF/RGM"; TAB(60);
    IF snvz2 = 1 THEN PRINT #1, "Sn/Vz=OF/AR5"; TAB(60);
    IF snvz2 = 2 THEN PRINT #1, "Sn/Vz=3SH1/DT"; TAB(60);
    IF snvz2 = 3 THEN PRINT #1, "Sn/Vz=OF/B-90"; TAB(60);
    IF snvz2 = 4 THEN PRINT #1, "Sn/Vz=C4/T-90"; TAB(60);
    IF snvz3 = 0 THEN PRINT #1, "Sn/Vz=OF/RGM"
    IF snvz3 = 1 THEN PRINT #1, "Sn/Vz=OF/AR5"
    IF snvz3 = 2 THEN PRINT #1, "Sn/Vz=3SH1/DT"
    IF snvz3 = 3 THEN PRINT #1, "Sn/Vz=OF/B-90"
    IF snvz3 = 4 THEN PRINT #1, "Sn/Vz=C4/T-90"
    PRINT #1, "PRICEL="; pr.eps1; TAB(30); "PRICEL="; pr.eps2; TAB(60); "PRICEL="; pr.eps3
  IF snvz1 >= 1 THEN
  PRINT #1, "N="; INT(N1 + .001); TAB(30);
  ELSE
  PRINT #1, "0"; TAB(30);
  END IF
  IF snvz2 >= 1 THEN
  PRINT #1, "N="; INT(N2 + .001); TAB(60);
  ELSE
  PRINT #1, "0"; TAB(60);
  END IF
  IF snvz3 >= 1 THEN
  PRINT #1, "N="; INT(N3 + .001)
  ELSE
  PRINT #1, "0"
  END IF
    PRINT #1, "Dovorot OH="; dov.isch1; TAB(30); "Dovorot OH="; dov.isch2; TAB(60); "Dovorot OH="; dov.isch3
CLOSE #1
END SUB

SUB ZAPRASCH2 (Veer1B AS SINGLE, Veer2B AS SINGLE, Veer3B AS SINGLE, sk.shk1 AS SINGLE, sk.shk2 AS SINGLE, sk.shk3 AS SINGLE, dXtus11 AS SINGLE, dNtus1 AS SINGLE, dXtus2 AS SINGLE, dXtus3 AS SINGLE, dNtus2 AS SINGLE, dNtus3 AS SINGLE, ts1 AS SINGLE, ts2 AS SINGLE, ts3 AS SINGLE, zo11 AS SINGLE)
OPEN "zaprasch.arx" FOR APPEND AS #1
 IF zo11 = 0 THEN
    PRINT #1, "Veer="; Veer1B; TAB(30); "Veer="; Veer2B; TAB(60); "Veer="; Veer3B
    PRINT #1, "Sk\Shk="; sk.shk1; TAB(30); "Sk\Shk="; sk.shk2; TAB(60); "Sk\Shk="; sk.shk3
    ELSE
    END IF
    PRINT #1, "dX/dNtus="; dXtus11; "/"; dNtus1; TAB(30); "dX/dNtus="; dXtus2; "/"; dNtus2; TAB(60); "dX/dNtus="; dXtus3; "/"; dNtus3
    PRINT #1, "ts="; ts1; TAB(30); "ts="; ts2; TAB(60); "ts="; ts3
 CLOSE #1
END SUB

SUB ZAPRASCH3 (Dt1 AS SINGLE, Dt2 AS SINGLE, Dt3 AS SINGLE, pop.v.d1 AS SINGLE, pop.v.d2 AS SINGLE, pop.v.d3 AS SINGLE, Ygol.t1 AS SINGLE, Ygol.t2 AS SINGLE, Ygol.t3 AS SINGLE, pop.v.nap.1 AS SINGLE, pop.v.nap.2 AS SINGLE, pop.v.nap.3 AS SINGLE, Yr1 AS SINGLE, Yr2 AS SINGLE, Yr3 AS SINGLE, vrv AS SINGLE, pover AS SINGLE, Ygpad1 AS SINGLE, Ygpad2 AS SINGLE, Ygpad3 AS SINGLE, snvz1 AS SINGLE, snvz2 AS SINGLE, snvz3 AS SINGLE)
OPEN "zaprasch.arx" FOR APPEND AS #1
 PRINT #1, "Dt/dD="; Dt1; "/"; INT(pop.v.d1 + .001); TAB(30); "Dt/dD="; Dt2; "/"; INT(pop.v.d2 + .001); TAB(60); "Dt/dD="; Dt3; "/"; INT(pop.v.d3)
 PRINT #1, "Yg.t/dDov="; Ygol.t1; "/"; INT(pop.v.nap.1 + .001); TAB(30); "Yg.t/dDov="; Ygol.t2; "/"; INT(pop.v.nap.2); TAB(60); "Yg.t/dDov="; Ygol.t3; "/"; INT(pop.v.nap.3)
 PRINT #1, "Yroven="; Yr1; TAB(30); "Yroven="; Yr2; TAB(60); "Yroven="; Yr3
IF snvz1 = 3 AND vrv = 15 THEN
PRINT #1, "BNIMANIE VRV > 15!!!"; TAB(30);
ELSEIF snvz1 = 1 AND pover = 0 AND Ygpad1 >= 40 THEN
PRINT #1, "Yst.Vzr=VUSOKI!!!"; TAB(30);
ELSEIF snvz1 = 1 AND pover = 0 AND Ygpad1 < 40 THEN
PRINT #1, "Yst.Vz=NIZKI!!!"; TAB(30);
ELSEIF snvz1 = 1 AND pover = 1 THEN
PRINT #1, "Yst.Vzr=VUSOKI!!!"; TAB(30);
ELSE
PRINT #1, "0"; TAB(30);
END IF
IF snvz2 = 3 AND vrv = 15 THEN
PRINT #1, "BNIMANIE VRV > 15!!!"; TAB(60);
ELSEIF snvz2 = 1 AND pover = 0 AND Ygpad2 >= 40 THEN
PRINT #1, "Yst.Vzr=VUSOKI!!!"; TAB(60);
ELSEIF snvz2 = 1 AND pover = 0 AND Ygpad2 < 40 THEN
PRINT #1, "Yst.Vz=NIZKI!!!"; TAB(60);
ELSEIF snvz2 = 1 AND pover = 1 THEN
PRINT #1, "Yst.Vzr=VUSOKI!!!"; TAB(60);
ELSE
PRINT #1, "0"; TAB(60);
END IF
IF snvz3 = 3 AND vrv = 15 THEN
PRINT #1, "BNIMANIE VRV > 15!!!"
ELSEIF snvz3 = 1 AND pover = 0 AND Ygpad3 >= 40 THEN
PRINT #1, "Yst.Vzr=VUSOKI!!!"
ELSEIF snvz3 = 1 AND pover = 0 AND Ygpad3 < 40 THEN
PRINT #1, "Yst.Vz=NIZKI!!!"
ELSEIF snvz3 = 1 AND pover = 1 THEN
PRINT #1, "Yst.Vzr=VUSOKI!!!"
ELSE
PRINT #1, "0"
END IF
CLOSE #1
END SUB

SUB ZAPRASCHET (Xc1 AS SINGLE, Xc2 AS SINGLE, Xc3 AS SINGLE, Yc1 AS SINGLE, Yc2 AS SINGLE, Yc3 AS SINGLE, hc1 AS SINGLE, hc2 AS SINGLE, hc3 AS SINGLE, opn1$, opn2$, opn3$, OH1 AS SINGLE, OH2 AS SINGLE, OH3 AS SINGLE)
INPUT "Ochistit zapisi - 1, Net - 0 "; vvod
IF vvod = 1 THEN OPEN "zaprasch.arx" FOR OUTPUT AS #1: CLOSE #1
OPEN "zaprasch.arx" FOR APPEND AS #1
t1$ = "-------------------------------------------------------------------------"
PRINT #1, t1$
INPUT " Daty Pomeniat - 1, Net - 0 "; vvod
IF vvod = 1 THEN INPUT " VVOD DATA = "; data$: PRINT #1, data$
INPUT "VVOD N, i Xarakter Zeli"; nz$
PRINT #1, nz$
PRINT #1, "1B"; TAB(30); "2B"; TAB(60); "3B"
PRINT #1, "Xc="; INT(Xc1 + .001); TAB(30); "Xc="; INT(Xc2 + .001); TAB(60); "Xc="; INT(Xc3 + .001)
PRINT #1, "Yc="; INT(Yc1 + .001); TAB(30); "Yc="; INT(Yc2 + .001); TAB(60); "Yc="; INT(Yc3 + .001)
PRINT #1, "hc="; INT(hc1 + .001); TAB(30); "hc="; INT(hc2 + .001); TAB(60); "hc="; INT(hc3 + .001)
 PRINT #1, "N OP="; opn1$; TAB(30); "N OP="; opn2$; TAB(60); "N OP="; opn3$
 PRINT #1, "OH="; OH1; TAB(30); "OH="; OH2; TAB(60); "OH="; OH3
CLOSE #1
END SUB

SUB ZASGRYPZELI (Gl1 AS SINGLE, Fr1 AS SINGLE, A AS SINGLE, D AS SINGLE, Mc AS SINGLE)
PRINT " << GRYPOVAIA ZASECHKA >>"
        INPUT " Prav gran Zeli v DY = "; prav
        INPUT " Lev gran Zeli v DY = "; lev
        INPUT " Daln dran Zeli v Metr = "; daln
        INPUT " Blign dran Zeli v Metr = "; blig
        INPUT " Mc = "; Mc
        IF prav < lev THEN
                prav = prav + 6000
                ELSE
        END IF
        Fr1 = CINT(((prav - lev) * (((daln - blig) / 2 + blig) / 1000) * 1.05) + .001)
        Gl1 = daln - blig
        A = (prav - lev) / 2 + lev
        IF A > 6000 THEN
                A = A - 6000
                ELSE
        END IF
        D = (daln - blig) / 2 + blig
        PRINT " Front = "; Fr1; " Glybina = "; Gl1; " A = "; CINT(A + .001); " D = "; D
END SUB

